kiegroup/droolsjbpm-integration

- kie-server/kie-server-distribution-wars/src/main/shared-resources/WEB-INF/web.xml
- kie-server/kie-server-distribution-wars/src/main/shared-resources/WEB-INF/weblogic.xml
- kie-server/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java
- kie-server/kie-server-services/src/main/java/org/kie/server/services/KieServerApplication.java
- kie-server/kie-server-services/src/main/java/org/kie/server/services/api/KieServer.java
Small changes which allows deployment of execution server on Weblogic.
- raised version of web.xml (caused problem to weblogic) so content become valid
- added weblogic.xml to map security role from web.xml to role group defined in Weblogic
- added destinationJndiName property for JMS - Weblogic use this one for finding out queue JNDI name
- added @ApplicationPath with default value, is overwritten in web.xml - was needed by Weblogic
- removed @Path annotation from REST interface, this annotation in interface caused problems to Weblogic, is duplicated in implementation class anyway
> BZ1193122: Various fixes to allow running execution server on Weblogic

- drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features.xml
* the commit needs to be cherry-picked into 6.2.x as well
> drools-karaf-features: update cxf-specs version range to support Fuse 6.2

- .gitignore
- kie-performance-kit/pom.xml
- kie-performance-kit/src/main/java/org/kie/perf/Executor.java
- kie-performance-kit/src/main/java/org/kie/perf/SharedMetricRegistry.java
- kie-performance-kit/src/main/java/org/kie/perf/TestConfig.java
- kie-performance-kit/src/main/java/org/kie/perf/annotation/KPKLimit.java
- kie-performance-kit/src/main/java/org/kie/perf/metrics/CsvSingleReporter.java
- kie-performance-kit/src/main/java/org/kie/perf/metrics/MemoryUsageGaugeSet.java
- kie-performance-kit/src/main/java/org/kie/perf/metrics/ThreadStatesGaugeSet.java
- kie-performance-kit/src/main/java/org/kie/perf/run/Duration.java
- kie-performance-kit/src/main/java/org/kie/perf/run/IRunType.java
- kie-performance-kit/src/main/java/org/kie/perf/run/Iteration.java
- kie-performance-kit/src/main/java/org/kie/perf/scenario/IPerfTest.java
- kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java
- kie-performance-kit/src/main/java/org/kie/perf/suite/ITestSuite.java
- kie-performance-kit/src/main/java/org/kie/perf/suite/LoadSuite.java
- pom.xml
This is kie-performance-kit for performance tests of jbpm engine, remote APIs and other internal tests. It needs to be built together with other modules to be in the Maven repository, so the kit could be used anywhere.
kie-performance-kit: refactoring of executor
kie-performance-kit: Added warmup
kie-performance-kit: added runtimeManagerStrategy
kie-performance-kit: Fixed metrics during warmup
kie-performance-kit: added pessimistic locking and concurrent user count properties
kie-performance-kit: Added CsvSingleReporter and MemoryUsageGaugeSet
kie-performance-kit: extended TestConfig, added support for optional measures MemoryUsage, FileDescriptors and ThreadStates
kie-performance-kit: Format report output
> KIE Performance Kit

- droolsjbpm-bpms-distribution/pom.xml
- droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml
* the BZ is already closed as the artifact was manually added into the maven repo, but this should be the proper fix
> [BZ-1203351] add jbpm-services-cdi into bpms-distribution

- drools-osgi/drools-karaf-itests/README
PR contains readme for org.drools.karaf.itest. This readme describes Java system properties for running tests on custom karaf or karaf like container.
> Readme for org.drools.karaf.itest.

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/KieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerContainerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/jpa/PersistenceUnitInfoImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/pom.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/weblogic-ejb-jar.xml
PersistenceUnitInfoImpl changes done because Hibernate in Ejb3Configuration class stores content of persistence unit info into log when debugging enabled (see LogHelper.logPersistenceUnitInfo(info)). 
There are invoked getJtaDataSource and getNonJtaDataSource which caused issues as they aren't set or contain default value.
Just a suggestions for fix, feel free to improve/make better.
<kie.server.controller.context.http.url> removed as it isn't needed after unification of controller URL.
> DROOLS-733 - added removing services when disposing container, other small fixes

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
One small thing found, error returned in testGetProcessDefinitionByContainerAndNonExistingId test has response code 500, I think some 4xx should be better in this case.
> DROOLS-733 - fixed NPE when looking for nonexisting process definition

- kie-remote/kie-remote-client/pom.xml
@mrietveld could you please double check this? I believe it is safe as we are using the same on master and 6.3.x for some time now.
> kie-remote-client: use explicit dependency to fix parallel builds

- kie-remote/kie-remote-client/pom.xml
- kie-remote/kie-remote-services/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
* all touched modules already contain mockito-core,
which is sufficient
> [DROOLS-999] remove usage of mockito-all uberjar

- kie-maven-plugin/pom.xml
* this is only temporary until there is a proper 1.11.12 release
directly from Takari
> [BZ-1305206] kie-maven-plugin: upgrade takari-lifecycle-plugin to 1.11.11.jbossorg-1

- kie-maven-plugin/pom.xml
* this is only temporary until there is a proper 1.11.12 release
directly from Takari
> [6.4.x] [BZ-1305206] kie-maven-plugin: upgrade takari-lifecycle-plugin to 1.11.11.jbossorg-1

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
* no need to include thhose additional dependencies, they are already
brought in by the kie-maven-plugin by default
> kie-server tests: remove additional dependencies for kie-maven-plugin

- drools-osgi/drools-osgi-integration/pom.xml
- drools-osgi/drools-osgi-integration/src/main/java/org/drools/osgi/compiler/OsgiKieModule.java
- drools-osgi/drools-osgi-integration/src/main/test/org/drools/osgi/compiler/OsgiKieModuleTest.java
* so far we only supported jar-based bundles. WARs
are, however, supported as well on Karaf/Fuse.
The code is a hack basically. It tries to search
search resources with WEB-INF/classes prefix to
cover the WAR use case. For 7.x we should look
into making this easier to undersntad, by e.g.
having two (or more) different classes
- OsgiJarKieModule and OsgiWarKieModule. They
would then hide the implementation details
of WEB-INF/classes, etc. Implementing this for
6.x is a risk at this stage.
This is a forward port of #368. We need to come up with better approach, bot for now let's at least keep in sync with 6.4.x
> [ENTESB-5152] add support for OSGi WAR bundles

- drools-osgi/drools-karaf-features/pom.xml
* this is just to synp up with non-osgi world which uses
version 3.13 for quite some time now
> [6.4.x] [DROOLS-1060] osgi: upgrade Apache POI from 3.11_1 to 3.13_2

- drools-osgi/drools-karaf-features/pom.xml
* this is just to synp up with non-osgi world which uses
version 3.13 for quite some time now
> [DROOLS-1060] osgi: upgrade Apache POI from 3.11_1 to 3.13_2

- kie-aries-blueprint/pom.xml
- kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/KieNamespaceHandler.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/KieBlueprintContainer.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintBPMNTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintBasicTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintCommandsTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintEnvironmentTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintGAVTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintKModuleBasicTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintListenerTest.java
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/tests/KieBlueprintLoggerTest.java
@mariofusco please take a look
Many thanks to @winklerm for the fixes around the BundleContext mocking.
> [6.4.x] [DROOLS-967] re-enable kie-aries-blueprint tests

- drools-osgi/drools-karaf-features/pom.xml
- drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-core.xml
- drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-fuse-6_3.xml
* we need different servlet-api bundle for Fuse 6.2
and Fuse 6.3. Separate feature files seem to be the
only way to do so. From now on, the feature files
should include the target Fuse version in the name.
Keeping features.xml (for Fuse 6.2) because of
backward compatibility
@mariofusco please take a look
@dvirgiln could you please double check this is what you meant?
@winklerm, @jiripetrlik FYI
> [6.4.x] [ENTESB-5168] create different features file for Fuse 6.3

- drools-osgi/drools-karaf-features/pom.xml
- drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-core.xml
- drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-fuse-6_3.xml
* we need different servlet-api bundle for Fuse 6.2
and Fuse 6.3. Separate feature files seem to be the
only way to do so. From now on, the feature files
should include the target Fuse version in the name.
Keeping features.xml (for Fuse 6.2) because of
backward compatibility
> [ENTESB-5168] create different features file for Fuse 6.3

- kie-spring/pom.xml
- kie-spring/src/main/java/org/kie/spring/KModuleBeanFactoryPostProcessor.java
- kie-spring/src/test/java/org/kie/spring/KModuleBeanFactoryPostProcessorTest.java
* TLDR; URLs can only contain forward slashes - '/' and
filesystem pathas contain os-specific hashes. The code
needs to deal with URLs and paths slightly differently!
@mariofusco could you please take a look?
> [BZ-1324017] fix dealing with URL suffix on Windows

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
@porcelli @etirelli @csadilek see the change ... I might be stupid and don't understand this but how it can work on one wildfly version and not the other....????
> make a RemoteKieServerOperation class protected instead of public

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/util/RestUtils.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/test/java/org/kie/server/remote/rest/common/util/RestUtilsTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java
Also refactored conversation Id integration tests: moved conversation Id check to separated test method in common module.
> DROOLS-1128 - Concurrent call fails when creating container

- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContext.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContextManager.java
See https://bugzilla.redhat.com/show_bug.cgi?id=1326805
For the reviewer: both this pr and https://github.com/droolsjbpm/kie-wb-distributions/pull/268 are necessary for this. 
The `org.apache.wink.jaxbcontextcache` property (set to `off`) makes sure that JAXB contexts are not cached (otherwise, changes in the deployment would not be "caught" and user-defined serialized class instances _incorrectly_ de/serialized). 
This change makes sure that the (apache wink/websphere) JAX-RS implementation framework gets a real `JAXBContext` instance: it looks like the openwebbeans CDI implementation that websphere uses simply interferes too much for us to use the `DynamicJaxbContext` as the `JAXBContext` instance. 
Lastly, given that the `DynamicJaxbContext` is already caching `JAXBContext` instances, …
> BZ-1326805 - Serialization problems on websphere as a result of BZ-1299549

- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContext.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContextManager.java
See https://bugzilla.redhat.com/show_bug.cgi?id=1326806
For the reviewer: both this pr and https://github.com/droolsjbpm/kie-wb-distributions/pull/268 are necessary for this. 
The `org.apache.wink.jaxbcontextcache` property (set to `off`) makes sure that JAXB contexts are not cached (otherwise, changes in the deployment would not be "caught" and user-defined serialized class instances _incorrectly_ de/serialized). 
This change makes sure that the (apache wink/websphere) JAX-RS implementation framework gets a real `JAXBContext` instance: it looks like the openwebbeans CDI implementation that websphere uses simply interferes too much for us to use the `DynamicJaxbContext` as the `JAXBContext` instance. 
Lastly, given that the `DynamicJaxbContext` is already caching `JAXBContext` instances, …
> BZ-1326806 - Serialization problems on websphere as a result of BZ-1310739

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestOnlyIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/ImageServiceRestOnlyIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerKieServerBaseIntegrationTest.java
- raised timeout for QueryDataServiceIntegrationTest and OptaPlanner integration tests, current ones were low for case when is used slower repo(improvement idea - separate API to reduce to reduce dependency tree complexity and size)
- updated JobServiceIntegrationTest - to remove dependency on job order returned by Kie server
- updated ProcessServiceIntegrationTest - to remove dependency on job order returned by Kie server, also some DBs round timestamp so test became unreliable for them
- response code changes in REST tests - some containers like WebLogic 12.1.3 use jersey 1.x. In such case response code for DELETE requests from Kie server is 200 instead of 204. It seems to be caused by setting of response entity for these requests, see …
> kie-server: test improvements and stabilization

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
@sutaakar, @mswiderski please take a look. This is basically hack/workaround to make sure the test modules are not executed in parallel. Ultimately we could fix this by configuring cargo to use random available ports instead of the defaults. But that will take some time to get properly done. This is I think a good workaround for now.
> kie-server-tests: run modules one at a time, even for parallel builds

- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
* was introduced by mistake via
3a92c621a2e400a
> Remove duplicated dependency

- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/api/RemoteRestRuntimeEngineBuilder.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbCommandsResponse.java
- kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/RemoteRestRuntimeEngineBuilderImpl.java
- kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/AbstractRemoteCommandObject.java
- kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/RemoteConfiguration.java
- kie-remote/kie-remote-client/src/test/java/org/kie/remote/client/ws/AuthenticatorTest.java
- kie-remote/kie-remote-client/src/test/java/org/kie/remote/services/ws/command/CommandServiceTest.java
- kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/RemoteClientBuilderTest.java
- kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/http/AvailablePortFinder.java
- kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/http/HeaderTest.java
- kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/http/RedirectTest.java
See https://bugzilla.redhat.com/show_bug.cgi?id=1327632
Please only merge once there is a + on the bpms-rollup-3-6.2.x flag.
> BZ-1327632 - Support for custom authentication in RemoteRuntimeEngine configuration

- kie-server-parent/kie-server-tests/pom.xml
* artifact-installer allows better caching (inside ~./m2)
* the Tomcat download URLs were also causing issues on JDK 6
(Could not generate DH keypair: Prime size must be multiple of 64,
and can only range from 512 to 1024 (inclusive))
@mswiderski, @sutaakar please take a look.
> kie-server-tests: use Cargo's artifact-installer instead of url-installer

- drools-osgi/drools-osgi-integration/pom.xml
- kie-aries-blueprint/pom.xml
- kie-remote/kie-remote-client/pom.xml
- kie-remote/kie-remote-common/pom.xml
- kie-server-parent/kie-server-api/pom.xml
- kie-server-parent/kie-server-remote/kie-server-client/pom.xml
- kie-spring/pom.xml
Depends on:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/183
> [DROOLS-1129] consistent OSGi Bundle-SymbolicName for all jars

- kie-remote/kie-remote-client/pom.xml
- kie-remote/kie-remote-common/pom.xml
- kie-remote/kie-remote-common/src/test/java/org/kie/remote/common/rest/KieRemoteHttpRequestTest.java
- kie-remote/kie-remote-common/src/test/java/org/kie/remote/common/rest/ServerTestCase.java
- kie-remote/kie-remote-common/src/test/resources/logback-test.xml
* Jetty was upgraded from 8.x to 9.x and those two
versions are not 100% compatible.
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/201
@mrietveld could ouy please take a look?
> Jetty + CXF related fixes after upgrade to IP BOM 7.0.0.CR3

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
wildfly-controller-client is needed by Cargo, used in JmsQueueIntegrationTest.
Updated group Id and aligned to use version defined in WildFly bom.
Separated path to Kie server WAR file to be possible to define custom Kie server WAR file when running custom container.
> kie-server-tests: on-demand deployment/undeployment updates

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerBaseIntegrationTest.java
Allow external definition of kie-server-testing-client-deployment-settings.xml - for case when we need to use custom private repositories for kjar dependencies.
Side note: using 2 different approaches for creating kjars in tests(by MavenCLI and kie-ci) makes things complicated. I would like to remove one of them in future. What do you think, which one should stay? I think that kie-ci provides more flexibility, could be more useful to keep it.
> kie-server-tests: custom client-deployment-settings.xml

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerBaseIntegrationTest.java
Allow external definition of kie-server-testing-client-deployment-settings.xml - for case when we need to use custom private repositories for kjar dependencies.
> [6.4.x] kie-server-tests: custom client-deployment-settings.xml

- kie-remote/kie-remote-jaxb-gen/pom.xml
* the plugin was bound to non-existing phase inititalize
(typo, should be initialize). Because of that it was
never executed and thus is not needed at all
> kie-remote-jaxb-gen: remove unused plugin config (thanks @baldimir)

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/call-evaluation.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/customtask.bpmn
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/signal-start.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
@psiroky What do you think, is it good to use this platform BOM or I should rather use several specific BOMs for drools/jbpm/optaplanner...
> kie-server-tests: use BOM for kjar dependencies

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/call-evaluation.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/customtask.bpmn
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/signal-start.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/493
> [6.4.x] kie-server-tests: use BOM for kjar dependencies

- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/KieServerInstanceList.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerIntegrationTest.java
When is created `KieServerInstanceList` with no `KieServerInstance` and then try get all server instances by `getKieServerInstances()` then KieServerList created with Json marshalling return _empty array_ and  list created with Jaxb marshalling return _null_.
This is caused by content of response: Jaxb ( `<kie-server-instance-list/>` ), JSON (` "kie-server-instance" : [ ] `) so there are used different constructors.
Empty `KieServerInstances` in `KieServerInstanceList` should be empty and not null.
> kie-server: controller - empty KieServerInstanceList fix

- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/OptaplannerKieServerExtension.java
it throws an IllegalArgumentException on ThreadPoolExecutor
> PLANNER-562 DROOLS-1203 OptaPlanner ext doesn't run on a 1 CPU machine

- kie-server-parent/kie-server-api/pom.xml
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/SolverInstance.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/package-info.java
With JAXB this is impossible, but we add the package-info anyway so it works for our kie-server-api classes at least.
This PR also points out a TODO related PLANNER-604 that were already there (and aren't being fixed now), but at least it brings that TODO away from hiding.
> Scores should automatically marshall correctly with XStream - 

- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbCommandsResponse.java
This pull request is focused on resolving occurrences of Sonar rule
squid:UselessImportCheck - Useless imports should be removed.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:UselessImportCheck
Please let me know if you have any questions.
George Kankava
> squid:UselessImportCheck - Useless imports should be removed

- drools-benchmark/src/main/java/org/drools/benchmark/model/waltz/Edge.java
- drools-benchmark/src/main/java/org/drools/benchmark/model/waltz/Stage.java
- kie-infinispan/jbpm-infinispan-persistence/src/main/java/org/jbpm/persistence/processinstance/InfinispanProcessInstanceManager.java
- kie-performance-kit/src/main/java/org/kie/perf/metrics/ThreadStatesGaugeSet.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/api/RemoteRuntimeEngineFactory.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/internal/RemoteCommandWebserviceClientBuilderImpl.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbWrapper.java
- kie-remote/kie-remote-common/src/main/java/org/kie/remote/common/rest/Base64Util.java
- kie-remote/kie-remote-common/src/main/java/org/kie/remote/common/rest/KieRemoteHttpRequest.java
- kie-remote/kie-remote-jaxb/src/main/java/org/kie/services/client/serialization/JaxbSerializationProvider.java
- kie-remote/kie-remote-jaxb/src/main/java/org/kie/services/client/serialization/JsonSerializationProvider.java
- kie-remote/kie-remote-jaxb/src/main/java/org/kie/services/client/serialization/jaxb/impl/runtime/JaxbCorrelationKeyFactory.java
- kie-remote/kie-remote-jaxb/src/main/java/org/kie/services/shared/ServicesVersion.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/ResourceBase.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContext.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/query/RemoteServicesAuditQueryCriteriaUtil.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/query/RemoteServicesQueryData.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/query/RemoteServicesTaskQueryCriteriaUtil.java
- kie-remote/kie-remote-ws/kie-remote-ws-impl/src/main/java/org/kie/services/remote/ws/deployment/DeploymentWebServiceImpl.java
- kie-remote/kie-remote-ws/kie-remote-ws-impl/src/main/java/org/kie/services/remote/ws/history/HistoryWebServiceImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
- kie-spring/src/main/java/org/kie/spring/annotations/AnnotationsPostProcessor.java
This pull request is focused on resolving occurrences of Sonar rule
squid:ModifiersOrderCheck - Modifiers should be declared in the correct order.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:ModifiersOrderCheck
Please let me know if you have any questions.
George Kankava
> squid:ModifiersOrderCheck - Modifiers should be declared in the correct order

- kie-infinispan/jbpm-infinispan-persistence/src/main/java/org/jbpm/persistence/processinstance/InfinispanProcessInstanceManager.java
- kie-infinispan/jbpm-infinispan-persistence/src/main/java/org/jbpm/persistence/processinstance/InfinispanProcessInstanceManagerFactory.java
- kie-infinispan/jbpm-infinispan-persistence/src/main/java/org/jbpm/persistence/processinstance/InfinispanSignalManager.java
- kie-infinispan/jbpm-infinispan-persistence/src/main/java/org/jbpm/persistence/processinstance/InfinispanSignalManagerFactory.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1161 - '@Override' annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava
> squid:S1161 - '@Override' annotation should be used on any method overriding (since Java 5) or implementing (since Java 6) another one

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessDefinitionIntegrationTest.java
test alignment for https://github.com/droolsjbpm/jbpm/pull/496
> JBPM-5191 - Task properties doesn't include values - only data types

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessDefinitionIntegrationTest.java
test alignment for https://github.com/droolsjbpm/jbpm/pull/497
> [6.5.x] JBPM-5191 - Task properties doesn't include values - only data types

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessDefinitionIntegrationTest.java
test alignment for https://github.com/droolsjbpm/jbpm/pull/498
> [6.4.x] JBPM-5191 - Task properties doesn't include values - only data types

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessDefinitionIntegrationTest.java
test alignment for https://github.com/droolsjbpm/jbpm/pull/499
> [6.3.x] JBPM-5191 - Task properties doesn't include values - only data types

- jbpm-simulation/src/main/java/org/jbpm/simulation/converter/JSONPathFormatConverter.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/converter/SimulationFilterPathFormatConverter.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/handler/ActivityElementHandler.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/handler/AdHocSubProcessElementHandler.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/handler/DefaultElementHandler.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/handler/EventElementHandler.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/handler/ThrowEventElementHandler.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/impl/BPMN2PathFinderImpl.java
- jbpm-simulation/src/main/java/org/jbpm/simulation/impl/BPMN2SimulationDataProvider.java
- kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/factorybeans/KieSessionFactoryBeanHelper.java
- kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/namespace/KieObjectsInjector.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/internal/command/AbstractRemoteCommandObject.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/internal/command/InternalJmsCommandHelper.java
- kie-remote/kie-remote-jaxb/src/main/java/org/kie/services/client/serialization/jaxb/impl/audit/JaxbHistoryLogList.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContext.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerAssert.java
- kie-spring/src/main/java/org/kie/spring/factorybeans/EnvironmentDefFactoryBean.java
- kie-spring/src/main/java/org/kie/spring/factorybeans/KSessionFactoryBean.java
- kie-spring/src/main/java/org/kie/spring/namespace/KBaseDefinitionParser.java
- kie-spring/src/main/java/org/kie/spring/namespace/KModuleDefinitionParser.java
- kie-spring/src/main/java/org/kie/spring/namespace/LoggerUtil.java
- kie-spring/src/main/java/org/kie/spring/persistence/HumanTaskSpringTransactionManager.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1155 - Collection.isEmpty() should be used to test for emptiness.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Please let me know if you have any questions.
George Kankava
> squid:S1155 - Collection.isEmpty() should be used to test for emptiness

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
Raise timeout for synchronization between controller and Kie server.
If controller is integrated as part of workbench then starting of containers is executed asynchronously. This cause delays between returning of response from controller and actual start of container. Low timeout threshold  cause test instability.
> kie-server-tests: raise timeout for sync with controller

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementBaseTest.java
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/540
> [6.5.x] kie-server-tests: raise timeout for sync with controller

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementBaseTest.java
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/540
Change just in tests.
> [6.4.x] kie-server-tests: raise timeout for sync with controller

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/category/Unstable.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java
This test become unstable for slower databases, causing false positives. Caused by starting of task more than 2 seconds after process was started - reassignment already triggered.
Removing of this test will save us more than 18 seconds.
I think that this test doesn't bring us so much value.
@mswiderski  What do you think about it?
> kie-server-tests: update unstable escalation test

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/category/Unstable.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/543
> [6.4.x] kie-server-tests: update unstable escalation test

- kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/AbstractRemoteCommandObject.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/util/ExecuteCommandUtil.java
Tested via this code: 
- https://github.com/droolsjbpm/kie-tests/commit/982e830620e744f2747fee4d133c7d5684643fc6#diff-308e0f502097849c0745cffc88160b9aR1341?w=1
- https://github.com/droolsjbpm/kie-tests/commit/982e830620e744f2747fee4d133c7d5684643fc6#diff-ed7496f3242fedf28fbc556124b5d9beR23
> 6.4.x: RHBPMS-397 - Allow insecure Remote task operations (not only limited to GetTask* commands)

- kie-server-parent/kie-server-tests/pom.xml
Needed for JmsQueueIntegrationTest.
> kie-server-tests: add deploy synchronization to WildFly10 and EAP7

- kie-remote/kie-remote-jaxb-gen/pom.xml
* the upgrade should fix random failures recently seen when
building with JDK8
* similar upgrade was done on master few months back and everything seems to work there
@mbiarnes, @mrietveld could you please take a look?
> [6.5.x] kie-remote-jaxb-gen: upgrade jaxb2-maven-plugin from 1.6 to 2.2

- kie-server-parent/kie-server-api/pom.xml
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/CommandScript.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/DisposeContainerCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/ListContainersCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/KieContainerResourceFilter.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/KieContainerStatusFilter.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ReleaseIdFilter.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/KieContainerResourceFilterMatchTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/KieContainerResourceFilterTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/KieContainerStatusFilterTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/MarshallingRoundTripTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/ReleaseIdFilterTest.java
- kie-server-parent/kie-server-api/src/test/resources/logback-test.xml
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/KieServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerRestImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerCommandServiceImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerContainerCRUDIntegrationTest.java
* filtering is (currently) possible based on releaseId (and
its individual parts) and status
There are still few things I am not sure about:
* is the package `*.model` OK for the filter classes? Or should they go into own package (e.g. model.filter)?
* I added method `listContainers(kieContainerFilter)`. Should we also have methods like `listContainers(ReleaseId)` or `listContainers(Status)`. I am not sure since this can easily explode into quite a few new methods.
* there is no `isDeployed()` functionality implemented. It is I believe  equal to `status=STARTED`, so not sure it is worth adding new param just as an alias to existing one.
* I added `toString()`, `equals()` and `hashcode` to few `*.model` classes. I believe we could do that for all the classes? (unless there is good reason …
> [JBPM-5220] kie-server: implement filtering for listContainers()

- kie-server-parent/kie-server-api/pom.xml
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/CommandScript.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/DisposeContainerCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/ListContainersCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/KieContainerResourceFilter.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/KieContainerStatusFilter.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ReleaseIdFilter.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/KieContainerResourceFilterMatchTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/KieContainerResourceFilterTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/KieContainerStatusFilterTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/MarshallingRoundTripTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/ReleaseIdFilterTest.java
- kie-server-parent/kie-server-api/src/test/resources/logback-test.xml
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/KieServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerRestImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerCommandServiceImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerContainerCRUDIntegrationTest.java
* filtering is (currently) possible based on releaseId (and
its individual parts) and status
Backport of #563
> [6.5.x] [JBPM-5220] kie-server: implement filtering for listContainers()

- drools-osgi/drools-karaf-itests/src/test/resources/logback-test.xml
* logback defaults to DEBUG logging in case
there is no explicit config. That in turn
leads to bloated logs.
> karaf-itests: disable debug logging

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerEnvironment.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/KieScannerStatus.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/KieServerState.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplServerTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
Backport of #578 
Cherry-pick into 6.4.x is not clean. Will fix the conflicts later and create one more PR.
> [JBPM-5263,RHBPMS-4086] kie-server: persist active scanner state

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
Depends on droolsjbpm/droolsjbpm-knowledge#150 .
Depends on droolsjbpm/drools#866 .
* KieServer cascade containerId while creating via KieServices
> DROOLS-1235 MBean naming rework

- drools-osgi/drools-karaf-itests/README
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/AbstractKarafIntegrationTest.java
Allows user to specify additional Maven repositories for pax-exam tests. This can be useful when running pax-exam tests against binaries which are not available in public Maven repositories.
> Allows user to specify additional Maven repositories for pax-exam tests.

- drools-osgi/drools-karaf-itests-kjar/pom.xml
* there is no need to deploy
the kjar as it's just used for
testing
This should fix the deploy we are seeing. However, it's just quick&dirty fix. We need to come with a better solution.
cc @mariofusco, @baldimir
> Skip deploy for testing kjar

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
findProcessInstances tests took into account number of completed process instances - assuming that there is no process instance finished. This made tests influenced by other tests. This problem was spotted in https://github.com/droolsjbpm/droolsjbpm-integration/pull/598.
> kie-server-tests: improve findProcessInstances tests

- drools-rhq-plugin/src/main/resources/META-INF/rhq-plugin.xml
Requires droolsjbpm/drools#890.
This version align the RHQ/JON plug-in to the separation of MBean for Stateful Vs Stateless as introduced in DROOLS-1236.
This version has the same RHQ/JON limitations as described in #600 (duplicated KieBases under KieContainer hierarchies, and not just under the real parent KieContainer)
The RHQ/JON plug-in now exposes the correct statistics which are common across both types of MBean for Stateful Vs Stateless (as before, unchanged) but additionally exposes the statistic which are specific for each type of MBean for the sessions; specifically:
- `Total Facts Count` for (stateful) Kie Session
- `Total Objects Inserted` and `Total Objects Deleted` for Stateless Kie Session.
Example:
In the screenshot, the JVisualVM is used to highlight the actual statistics …
> DROOLS-1236 alignment of RHQ/JON plug-in.

- drools-rhq-plugin/pom.xml
- drools-rhq-plugin/src/main/java/org/drools/rhq/plugin/ExposeKCIDValueFromParentDiscoveryComponent.java
- drools-rhq-plugin/src/main/resources/META-INF/rhq-plugin.xml
Fixed for correct nesting and correct hierarchy display by cascading
manually the {kcontainId} variable. Specifically, the hiearchy now is:
```
KieContainer
+ KieBase
+ KieSession
```
The KieBase: take the `{kcontainId}` variable from the parent, and
re-exposes it as a new variable "kcId", at the level of the KieBase
itself. In turn, now the KieSession can access to `{kcId}` variable,
effectively and for any pragmatic effect representing the KieContainer
from the grand-parent.
Functional test result on RHQ / JON : 
In the screenshot, the JVisualVM is show the correct nesting of the KieSession under their respective KieBases. Now the hierarchy is correctly reflected on the RHQ/JON plug-in, and the KieSession are correctly nested only under the KieBase they actually belongs to.
Depends on …
> DROOLS-1269 - RHQ / JON plug-in display wrong hierarchy and repeatedly nesting KieSession under KieBase

- kie-server-parent/kie-server-tests/pom.xml
Needed for cases when external environment doesn't support specific functionality.
> [6.5.x] kie-server-tests: allow external configuration of excluded groups

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/category/Transactional.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerAssert.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/jms/ContainerJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/jms/DroolsJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/KieServerXAConnectionFactory.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/pom.xml
I have added more tests for 'fire and forget' feature. I tried to cover various methods from different `*ServicesClient` implementations.
Some tests are failing and I think those are potential bugs. Please, look at failed tests when the build is finished and tell me your opinion.
> [6.5.x] JBPM-5228 - Add more tests for 'fire and forget' feature

- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/AcceptedClientCommands.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbCommandsRequest.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/AcceptedServerCommands.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/jaxb/JaxbCommandsRequest.java
This fixes the problem with the list of accepted commands which was not updated before and causes fails of all requests with `GetTasksByGroupCommand`.
> [6.4.x] JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/AcceptedClientCommands.java
- kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbCommandsRequest.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/AcceptedServerCommands.java
- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/jaxb/JaxbCommandsRequest.java
Cherry-pick of commit 5e9dcbdc335ce0bca0f6e8c56e05a98ecada959e from #635 (6.4.x)
Please note that this feature has not been cherry-picked to **master** branch so I am also not fixing this issue there. Should we not delete `kie-remote` module on master branch?
> [6.5.x] JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

- droolsjbpm-integration-tests/pom.xml
- droolsjbpm-integration-tests/src/test/java/org/drools/droolsjbpm/integrations/tests/MBeansMonitoringWithJBpmTest.java
- droolsjbpm-integration-tests/src/test/resources/logback-test.xml
- pom.xml
Adding a new module for integration _test_ of Drools + jBPM.
- As discussed with @mswiderski , this looked the most sensible place (excluding separate repo `kie-tests` which missing 6.5.x branch and not under Jenkins CI).
- As discussed with @psiroky , this module does not produce the standard .jar .
This module actually only produce the -test[s|-sources] classifiers.
```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ droolsjbpm-integration-tests ---
[INFO] No primary artifact to install, installing attached artifacts instead.
[INFO] Installing /home/mmortari/git/droolsjbpm-integration/droolsjbpm-integration-tests/pom.xml to /home/mmortari/.m2/repository/org/drools/droolsjbpm-integration-tests/7.0.0-SNAPSHOT/droolsjbpm-integration-tests-7.0.0-SNAPSHOT.pom
[INFO] …
```
> DROOLS-1278 Test coverage of MBean for processes

- pom.xml
> droolsjbpm-integration-tests module temporarily disabled in build.

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
I have fixed some tests that caused problems on slower databases.
> [6.5.x] kie-server-tests: fix response handler tests on slow databases

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
Here is the same fix for `master` branch as the one introduced in pull-request #655 for `6.5.x`.
> kie-server-tests: fix response handler tests on slow databases

- kie-server-parent/kie-server-api/pom.xml
* the version 2.2.11 should be used everywhere. This is the one we
support. In case no jaxb impl is available on classpath, JDK will
use the one available together with the JDK installation (which is
slightly different for each JDK version). So using own version makes
sure we always test and run against the exactly same libs
Forward-port of #663
> [JBPM-5327,RHBPMS-4273] use correct jaxb impl version

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerInstanceImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplTest.java
* the refactoring also makes sure the scanner status is always
consistent between InternalKieScanner and KieScannerResource
(both as fields of KieContainerInstanceImpl)
This is an alternative solution to https://github.com/droolsjbpm/droolsjbpm-integration/pull/658 (with more refactorings).
@jakubschwan, @mswiderski, @etirelli please let me know what you think.
> [JBPM-5288,RHBPMS-4087] manage scanner lifecycle directly by KieContainerInstanceImpl

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerInstanceImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplTest.java
* the refactoring also makes sure the scanner status is always
consistent between InternalKieScanner and KieScannerResource
(both as fields of KieContainerInstanceImpl)
Forward port of #667
> [JBPM-5288] manage scanner lifecycle directly by KieContainerInstanceImpl

- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
To allow setting custom javassist version for product tests.
> kie-server-tests: manage javassist dependency

- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/679
> [6.5.x] kie-server-tests: manage javassist dependency

- kie-eap-integration/pom.xml
- kie-identity-session-provider/pom.xml
- kie-server-parent/pom.xml
- pom.xml
@mbiarnes @mariofusco this should in theory fix the issues with the OSGi blueprint test failures.
> Reorganize imported BOMs to avoid unnecessary dependencies

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/698.
> kie-server-tests: remove response handler from test name

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
Response handler doesn't implement toString() method, so it shouldn't be shown in test name.
In result it mess our internal tools which rely on test name.
> [6.5.x] kie-server-tests: remove response handler from test name

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
To prevent synchronization issues when using FireAndForgetResponseHandler.
Test was false positive occasionally, as for example: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/kie-all-master/job/kie-all-kie-server-matrix-master/container=wildfly10,jdk=jdk1.8,label_exp=linux%20&&%20mem4g/284/testReport/junit/org.kie.server.integrationtests.optaplanner.jms/OptaPlannerJmsResponseHandlerIntegrationTest/testSolverWithFireAndForgetResponseHandler_2__XSTREAM_/
> [6.5.x] kie-server-tests: add solver dispose synchronization

- kie-server-parent/kie-server-tests/pom.xml
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/636 .
Affects tests only.
> kie-server-tests: allow external configuration of excluded groups

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/BARuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java
Some tests failed on Oracle RAC database due id ordering from db.
> [6.5.x] kie-server-tests: test improvement for Oracle RAC

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- cleanup of test properties as part of Cargo update preparation - new Cargo doesn't like system properties with null value
- fixed instability of KieServerDroolsIntegrationTest - there were 2 different containers with same GAV created, our KeepLatestOnly policy was randomly disposing one of them
> kie-server-tests: minor cleanup and update

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
Current implementation caused random failures, for example [1]. This seems to be caused by complete task request reaching engine before start task command was completed.
Added waiting for task status change to prevent such failures.
[1] https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/droolsjbpm-integration/org.kie.server$kie-server-integ-tests-jbpm/1625
> kie-server-tests: stabilize and update JmsResponseHandlerIntegrationTest

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/ScoreWrapper.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/SolverInstance.java
- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/SolverServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudBalance.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/META-INF/cloudbalance-solver.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
Introduce ScoreWrapper to make sure the unmarshaller has enough information to convert string representation of the score into object representation.
Provide toScore() method with the support of out-of-box score implementations.
This PR also includes removal of deprecated Solution interface occurrences.
@ge0ffrey Could you please have a look at this?
> PLANNER-661 PLANNER-604 Execution Server: SolverInstance.score doesn't use the ScoreJaxbXmlAdapaters?

- kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/weblogic-ejb-jar.xml
`JMSSignalReceiver` configuration for WebLogic incorrectly used `KIE.SIGNAL` queue and connection factory instead of `KIE.SERVER.SIGNAL`.
> Fix JMS signal queue and connection factory for WebLogic

- kie-server-parent/kie-server-remote/kie-server-client/pom.xml
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/KieServicesHttpException.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/KieServicesClientErrorHandlingTest.java
To allow clients to better handle the different type of errors that could be thrown while executing http requests to the Kie Server.
> New exception type for kie server http related errors

- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouterConstants.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/KieServerInfoHandler.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/handlers/KieServerInfoHandlerTest.java
Sometimes Kie server router needs to return different URL
in its kie-server-info response than he actually listens to locally.
This can happen in case Kie server router is placed behind
another router, for example if it is deployed in OpenShift.
Grouped all system properties to one constant class.
> JBPM-5454: Add support for external URL configuration

- kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/KieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerContainerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/JBPMUIKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/OptaplannerKieServerExtension.java
Case-Mgmt KIE Server extension and jBPM-UI KIE Server extension can't be registered without a jBPM extension.
Actual state of the server output make no sense:
...
WARN  [org.kie.server.services.casemgmt.CaseKieServerExtension] (ServerService Thread Pool -- 97) jBPM extension not found, Case Management cannot work without jBPM extension, disabling itself
INFO  [org.kie.server.services.impl.KieServerImpl] (ServerService Thread Pool -- 97) Case-Mgmt KIE Server extension has been successfully registered as server extension
...
> Fix KIE Server output for not registered extensions

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/RestJbpmBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/KieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/RestJbpmBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/src/test/java/org/kie/server/integrationtests/policy/KieServerPolicyBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/KieServerRouterBaseIntegrationTest.java
Lately I noticed that some Kie server tests are skipped in Jenkins PR job. It is caused by failure in container creation [1] which is caused by failing of container dispose [2] - caused by containers having active process instances.
Fix for this issue consists of aborting of all active processes instances right after every test case (for tests using jBPM extension). Also added aborting for JbpmRestIntegrationTest.
[1] https://github.com/sutaakar/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/KieServerBaseIntegrationTest.java#L128
[2] https://github.com/sutaakar/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/or …
> kie-server-tests: Abort processes after test cases

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/rest/RestMalformedRequestIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/rest/RestMalformedRequestIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
To reveal real issue thrown when sending request.
> kie-server-tests: Avoid NPE when closing JAX-RS response

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
So failure in maven build for test resources doesn't affect other tests.
> kie-server-tests: Reset class loader before failing maven build

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
Sometimes JMS messages returned from Kie server come back in different order than expected when using AsyncResponseHandler, causing false positives like [1].
To stabilize tests I removed asynchronous start of process, it is checked in test method testStartProcessUseOfAsyncResponseHandlerWithMarshaller anyway.
[1] https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/droolsjbpm-integration-pullrequests/746/testReport/junit/org.kie.server.integrationtests.jbpm.jms/JmsResponseHandlerIntegrationTest/testGetProcessInstancesUseOfAsyncResponseHandlerWithMarshaller_2__XSTREAM_/
> kie-server-tests: stabilize JmsResponseHandlerIntegrationTest

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/777
> [6.5.x] kie-server-tests: stabilize JmsResponseHandlerIntegrationTest

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/772
> [6.5.x] kie-server-tests: Reset class loader before failing maven build

- kie-aries-blueprint/pom.xml
- kie-aries-blueprint/src/test/java/org/kie/aries/blueprint/mocks/MockEntityManager.java
- kie-infinispan/pom.xml
- kie-osgi/kie-karaf-features/pom.xml
- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintjBPMPersistenceKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/resources/META-INF/persistence.xml
- kie-osgi/kie-karaf-itests/src/test/resources/org/kie/karaf/itest/blueprint/processpersistence/persistence.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/resources/META-INF/persistence.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/resources/META-INF/persistence.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee6-container.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
- kie-spring/pom.xml
- kie-spring/src/test/filtered-resources/kie-custom-settings.xml
- kie-spring/src/test/resources/META-INF/persistence.xml
- kie-spring/src/test/resources/jbpm/persistence-jta.xml
- kie-spring/src/test/resources/jbpm/persistence-local.xml
* custom settings.xml needed for builds
that use "-Dmaven.repo.local", as otherwise
KIE Maven support looks into the default ~./m2
repo where the artifacts are not present
* the mapping-file "META-INF/ProcessInstanceInfo.hbm.xml"
is not needed (likely just copy&paste error). Hibernate
was complaining it can not find the file and would refuse
to initialize
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.
> Fixes after JPA 2.0 to 2.1 upgrade

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/CommandScript.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/GetReleaseIdCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/KieServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/BaseKieServicesClientTest.java
- kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/KieServicesClientTest.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerCommandServiceImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerContainerCRUDIntegrationTest.java
I have added missing `getReleaseId` method to `KieServicesClient`.
> JBPM-5504: Missing getReleaseId method in KieServicesClient

- droolsjbpm-integration-examples/pom.xml
- kie-eap-integration/kie-eap-tests/pom.xml
- kie-server-parent/kie-server-api/pom.xml
As per http://maven.apache.org/plugins/maven-eclipse-plugin/:
"Plugin is retired. Users are advised to use m2e, the Eclipse Maven
Integration instead of this plugin, as it can more closely resemble the
actual build and runtime classpaths as described in the project pom.xml
- among other advantages."
Also Eclipse comes win m2e by default nowadays, so there is no need
for this plugin anymore.
> Fix POMs after IP BOM 7.0.0.CR6 upgrade

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/ContainerRemoteController.java
- kie-server-parent/kie-server-tests/pom.xml
To make Kie server tests compatible with new Cargo version, see https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/349 .
> kie-server-tests: Add user for remote deployment of Kie server

- kie-server-parent/kie-server-wars/kie-server/pom.xml
This artifact is brought by Hibernate 5. Cause issues with Tomcat.
Kie server should use jboss-transaction-api artifact.
@psiroky FYI
> Exclude geronimo-jta_1.1_spec artifact from Kie server

- kie-server-parent/kie-server-api/pom.xml
- kie-server-parent/kie-server-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-api/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-rest/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/pom.xml
- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json
Hi, @psiroky,
here is another introduction of revapi to our codebase. Following modules are currently covered:
- kie-server-api - whole module
- kie-server-controller-api - whole module
- kie-server-controller-rest - classes with javax.ws.rs REST annotations
- kie-server-client - just interfaces
- kie-server-rest-(case-mgmt | common | drools | jbpm | jbpm-ui | optaplanner) - classes with javax.ws.rs REST annotations
I have found another API packages in 2 more modules: kie-server-services-(common | jbpm-ui). Should we check them too? Besides that, I need help from @mswiderski or somebody else who can justify ignores which I had to add to revapi config. Just simply put down a comment on the specific file here on GitHub and I will push your justifications.
Thanks,
Marian
> Add revapi plugin to check public, client and REST APIs

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
User info properties file is available just in jbpm test module.
> kie-server-tests: move user info properties config to jbpm tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/KieServerRouterJbpmIntegrationTest.java
This method can return different number of queries in case of managed
Kie server as Workbench registers there own queries.
Deleting of all queries before test execution isn't optimal solution
as some tests rely on queries defined in containers.
> kie-server-tests: Reduce usage of getQueries method

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerUtil.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/DocumentServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
Test testUploadListDownloadDocument() was affected by documents left by DocumentServiceIntegrationTest.
> kie-server-tests: Delete document storage before tests

- drools-android/pom.xml
- droolsjbpm-bpms-distribution/pom.xml
- droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml
- droolsjbpm-brms-distribution/pom.xml
- droolsjbpm-brms-distribution/src/main/assembly/pre-bin.xml
- kie-aries-blueprint/pom.xml
- kie-eap-integration/kie-eap-distribution/pom.xml
- kie-eap-integration/pom.xml
- kie-identity-session-provider/pom.xml
- kie-infinispan/drools-infinispan-persistence/pom.xml
- kie-infinispan/jbpm-infinispan-persistence/pom.xml
- kie-maven-plugin/pom.xml
- kie-osgi/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-test-war/pom.xml
- kie-server-parent/kie-server-remote/kie-server-client/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
- kie-server-parent/kie-server-wars/kie-server/pom.xml
- kie-spring/pom.xml
- pom.xml
brms-distribution and bpms-distribution cleaned-up in the process
as well. They did contain some jars which really should not be
part of the engine distributiosn (kie-maven-plugin, kie-ci-osgi).
> [DROOLS-936] clean-up dependencies to fix duplicated classes issue

- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
Importing the kie-platform-bom somehow confuses the KIE Maven builder
as it is not able to find the droolsjbpm-integration.pom during the
test execution. Since this branch (6.4.x) is no longer being supported,
it does not make sense to invest more time into proper solution.
@ksuta could you please take a look? I know this is not ideal solution, but its IMO good enough considering this branch is no longer actively maintained (+ the tests are working on 6.5.x and master).
> [6.4.x] Workaround for dependency issues in OptaPlanner kie-server test

- kie-server-parent/kie-server-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json
Hi,
this PR is related to droolsjbpm/droolsjbpm-build-bootstrap#393. Revapi config JSON files were divided into filter and ignores parts.
Marian
> Split revapi configuration into filter and ignores

- kie-eap-integration/kie-eap-tests/pom.xml
- kie-eap-integration/kie-eap-tests/src/test/java/org/kie/eap/test/KieEapModulesSmokeIT.java
- kie-eap-integration/kie-eap-tests/src/test/resources/arquillian.xml
Since the rule contains "String()", the resulting knowledge
base also contains a KiePackage "java.lang" with the property
reactive info there.
@tarilabs this is the test we talked about, could you please quickly review?
> [DROOLS-1445] fix the kie-eap-modules smoke test

- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
.. this comment may have been accidentaly removed by commit 22f0dc0 [here](https://github.com/droolsjbpm/droolsjbpm-integration/commit/22f0dc0c8db1848cb79a60568effb58244ade87e#diff-e19734e25078062ec3c61cea48fb1eecL164).
> Re instantiate pom comment explaining artificial dependency motivation

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
I think the listeners registration should be configurable only globally and so they should be retrieved directly from the system properties. Correct me if I am wrong.
> JBPM-5750: Cannot disable registration of process event listeners

- kie-spring/src/test/java/org/kie/spring/jbpm/KieSpringProcessInstanceMigrationServiceImplTest.java
@mswiderski test was not cleaning up spring context which sometimes caused tests executed after it to fail.
> RHBPMS-4636 - clean up spring context in tests properly

- kie-spring/src/test/java/org/kie/spring/tests/persistence/JPASingleSessionCommandServiceFactoryTest.java
Temporarily ignore unstable tests.
> kie-spring-tests: ignore unstable test

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshallerExtension.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/json/JSONMarshallerExtensionTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/json/extension/JSONMarshallerExtensionGregorianCalendar.java
- kie-server-parent/kie-server-api/src/test/resources/META-INF/services/org.kie.server.api.marshalling.json.JSONMarshallerExtension
It's possible to extend the JSON Marshaller providing a `JSONMarshallerExtension` implementation.
It is loaded with the service loader mechanism, adding the following file in `META-INF/services`:
`org.kie.server.api.marshalling.json.JSONMarshallerExtension`
> JBPM-5776 - Extension mechanism for the JSON Marshaller

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/policy/KeepLatestContainerOnlyPolicy.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/policy/KeepLatestContainerOnlyPolicyTest.java
It could be fixed by not disposing containers in CREATING state or disposing just containers with earlier version. @mswiderski What do you think?
> JBPM-5835: Test coverage for KeepLatestContainerOnlyPolicy

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/DMNServicesClientImpl.java
.. to ensure proper marshaller is used.
It should use container marshaller, and without this fix it would
wrongly use the default server marshaller which maybe unaware of
custom classes added inside the container one.
> Fix DMN kie-server client to properly instruct JMS containerId ..

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/humanTaskEscalation.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java
Also UserTaskEscalationIntegrationTest will run now just with REST/JAXB combination to compensate longer test run. There is no need to test different transport/marshalling protocols as tested functionality use standard responses, they are covered by other tests.
> kie-server-tests: Stabilize UserTaskEscalationIntegrationTest

- kie-camel/src/main/java/org/kie/camel/KieConfiguration.java
- kie-camel/src/test/java/org/kie/camel/KieComponentIntegrationTest.java
- kie-camel/src/test/java/org/kie/camel/KieComponentOpOnUriTest.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNContextKS.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/DMNServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/DMNServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-dmn/src/main/java/org/kie/server/remote/rest/dmn/ModelEvaluatorResource.java
- kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNInputDataStringIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNTwoDMNModelsIntegrationTest.java
and API nomenclature alignments (e.g.: `evaluateAll`)
> Add support to evaluate a specific decision for DMN kie-server extension

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshallerExtension.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/xstream/HibernateXStreamMarshallerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/META-INF/services/org.kie.server.api.marshalling.xstream.XStreamMarshallerExtension
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/xstream/HibernateXStreamMarshallerExtensionTest.java
- kie-server-parent/kie-server-tests/pom.xml
This is needed to make sure that KIE Server is not sending away the
marshalled inernal hibernate types (like e.g. PersistentBag). Those
then can not be un-marshalled unless hibernate is on classpath.
This was an issue in workench where the hibernate was recently removed
from WEB-INF/lib.
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/428
@mswiderski could you please take a look?
> [GUVNOR-2991] use custom xstream-hibernate converters

- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Cat.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Dog.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Person.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Pet.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/resources/META-INF/kmodule.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/resources/org/kie/integration/testcoverage/instrumentation/rules.drl
- kie-integration-test-coverage/kie-maven-plugin-tests/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/filtered-resources/test-kie-maven-settings.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/filtered-resources/test.properties
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/InstrumentationTest.java
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/TestUtil.java
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/resources/logback-test.xml
- kie-integration-test-coverage/pom.xml
- pom.xml
This PR creates a new project _kie-integration-test-coverage_ - an analogy of _drools/drools-testcoverage_ and _jbpm/jbpm-testcoverage_ projects. The new project will contain additional QE tests for the code in _droolsjbpm-integration_ repository.
The project currently contains a draft of _kie-maven-plugin_ model classes instrumentation tests, more tests will follow.
> KIE integration test coverage

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/ImageServiceIncludedKieBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/filtered-resources/kjars-sources/stateless-session-kjar101/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/filtered-resources/kjars-sources/stateless-session-kjar101/src/main/resources/META-INF/kmodule.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/ContainerConfigPropagationIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerStartupIntegrationTest.java
Also moved ProcessConfig configuration items to constants to get rid of hardcoded values in the code.
> kie-server-tests: Add container config test coverage

- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Cat.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Dog.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Person.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/java/org/kie/integration/testcoverage/model/instrumentation/Pet.java
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/resources/META-INF/kmodule.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/src/test/resources/kjar-with-instrumentation/src/main/resources/org/kie/integration/testcoverage/instrumentation/rules.drl
- kie-integration-test-coverage/kie-maven-plugin-tests/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/filtered-resources/test-kie-maven-settings.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/filtered-resources/test.properties
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/InstrumentationTest.java
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/TestUtil.java
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/resources/logback-test.xml
- kie-integration-test-coverage/pom.xml
- pom.xml
Creates a new project (analogy to drools/drools-test-coverage and jbpm/jbpm-test-coverage)
in droolsjbpm-integration repository.
The new project will contain more QE tests, starting with additional integration tests
of kie-maven-plugin model classes instrumentation.
Artificial dependencies on kie-maven-plugin and kjar-with-instrumentation-wrapper
have been added to make sure that the required project are built before the projects that
depend on them, even during Maven parallel build (-T).
> Re-introduce project for QE droolsjbpm-integration tests

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshallerExtension.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/xstream/HibernateXStreamMarshallerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/META-INF/services/org.kie.server.api.marshalling.xstream.XStreamMarshallerExtension
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/xstream/HibernateXStreamMarshallerExtensionTest.java
- kie-server-parent/kie-server-tests/pom.xml
This is needed to make sure that KIE Server is not sending away the
marshalled inernal hibernate types (like e.g. PersistentBag). Those
then can not be un-marshalled unless hibernate is on classpath.
This was an issue in workench where the hibernate was recently removed
from WEB-INF/lib.
Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/429.
Backport of #901
> [7.0.x][GUVNOR-2991] use custom xstream-hibernate converters

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/QueryFilterSpec.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
Enhancing the advanced queries provided by REST and JMS to support a full SQL ORDER BY clause. This ensures the sort order can be selected per column of ordering.
> JBPM-5468 - Enable multiple column sorting on advanced queries

- kie-server-parent/kie-server-controller/kie-server-controller-test-war/src/main/assembly/assembly-ee7-container.xml
- kie-server-parent/kie-server-tests/pom.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
Initial implementation, to be discussed.
Contains own WebSphere platform implementation as implementation provided by Hibernate doesn't work - throwing UnsupportedOperationException.
Transaction API exclusion - will check if this works with WildFly/WLS.
cxf-rt-ws-policy - was causing issues with WebSphere's own cxf.  It is brought by jbpm-workitems, I am not sure what functionality depends on it.
> JBPM-5887: Add support for WebSphere 9

- kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/pom.xml
Functionality is now same as for other servers (WildFly, WLS)
> kie-server-tests: Remove deprecated was85x profile

- kie-server-parent/kie-server-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json
Hi, @mswiderski,
this is only a minor change to the revapi-config.json file, since these files are no more only on master branch, but on 7.0.x as well.
Marian
> Change revapi-config.json comment to be more general

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java
Behaviour changed by fixing DROOLS-1562: https://github.com/kiegroup/drools/pull/1270
> DROOLS-1562: Fix failing testUpdateContainerNonValidReleaseId

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerContainerCRUDIntegrationTest.java
Added test coverage for https://issues.jboss.org/browse/DROOLS-1562.
Removed testUpdateReleaseIdForExistingContainer as it was duplicated by testUpdateReleaseIdForExistingContainerAndCheckServerState.
> kie-server-tests: improve update release id tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
Interval set to 20ms is too small, it causes issues on IBM java.
Scanning consumed so many resources making JMS tests occasionally timed out.
> kie-server-tests: Raise scanning poll interval

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/MarshallingFormat.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/MarshallingFormatTest.java
Accodring to rfc2616 a http media type may contain
a type/subtype followed by one or more parameters delimited by
semicolons.
> RHBPMS-4592 Fix content-type from http header

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java
testUpdateContainerNonValidReleaseId() sometimes failed on Eap 7 container due race condition. Test tried to get message from controller about update, but this message was not yet in controller. For avoid this random failing is added synchronization for Messages.
> Improve Kie Server Controller tests stability

- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/resources/org/kie/server/controller/api/KieServerControllerAPI.gwt.xml
Add storage package to fix error 'No source code is available for type org.kie.server.controller.api.storage.KieServerTemplateStorage'
> Fix GWT compilation error

- kie-server-parent/kie-server-controller/kie-server-controller-standalone-impl/pom.xml
Greatly reduces size of the controller war.
> JBPM-5946: Delete unused dependency on kie-server-rest-common

- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/HistoryResourceImpl.java
- kie-remote/kie-remote-services/src/test/java/org/kie/remote/services/rest/HistoryResourceRestParamTest.java
@krisv @mswiderski it's not much,  but it does test that the regex from the Path annotation works for a given test value.
> [GSS](6.4.x)Endpoint /history/variable/{varId}/value/{value} not working for variables with space

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/hiring-taskform.form
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/ContainerUpdateUiIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FormServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/ImageServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/signal-process.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/package-names-white-list
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/project.imports
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/src/main/resources/META-INF/kmodule.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/src/main/resources/WorkDefinitions.wid
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/different-gav-definition-project/src/main/resources/evaluation.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RollingUpdateProcessServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RollingUpdateUserTaskServiceIntegrationTest.java
Hi,
here are additional tests which cover alias functionality as described in BPMSPL-543. Tests focus on the following:
Process Service
- starting processes within containers with different GAVs using the same aliases
- signalling processes
- setting/getting process variables
- completing work items
User Task Service
- getting input/output of tasks using alias
- getting/setting task attachments
- getting/setting task comments
Form and Image Service
- getting process and task forms
- getting process and process instance images
Thanks,
Marian
> JBPM-5336 Add test coverage for container aliases

- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/InstallFeaturesAbstractKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/KieSpringDependencyKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/KieSpringOnKarafKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/KieSpringjBPMPersistenceOnKarafKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/RuntimeManagerFeatureKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/WorkbenchModelsKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintDependencyKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintImportIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintProcessDependencyKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintScannerReimportIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintjBPMPersistenceKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/BaseKieServerClientOnKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/KieServerClientKarafIntegrationJaxbIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/KieServerClientKarafIntegrationJsonIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/KieServerClientKarafIntegrationXstreamIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/remoteclient/BaseRemoteClientOnKarafIntegrationTest.java
- drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/remoteclient/RemoteClientKarafIntegrationJaxbIntegrationTest.java
Folder with containers may grow quite fast in pax-exam folder (few gigabytes). It is not good to keep these folders in default build. This commit disables keeping these folders. It is possible to keep folders using karaf.keep.runtime.folder property. See more details in README in karaf-itests folder.
> Do not keep folders with Karaf containers in target folder.

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/ProcessSearchServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/TaskSearchServiceIntegrationTest.java
Contains fixes for issues revealed while testing different databases.
Makes tests send correlation key as string.
_Note: This seems to happen only on postgresql and other databases seem to handle correlation key even when sent as number, without 500 error being returned_
Updates tests using date in filter to use equalsTo rather than greaterThan
filter, since they tend to return more results and desired instance wouldn't get in the result.
> Advanced search integration tests fixes

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/ProcessInstanceSearchResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/TaskSearchResource.java
Adding default constructors to fix the following jrapidoc errors (which means that those 2 classes are not added to the documentation).
NOTE that this change required that I changed 2 `private final` fields to non-final - Is that ok?
```
[INFO] --- jrapidoc-rest-plugin:0.5.0.Final:run (run) @ kie-server ---
[INFO] 
[INFO] Introspection started
[INFO] 
[INFO] Loading class org.projectodd.jrapidoc.model.type.provider.JacksonJsonProvider
[INFO] Service group REMOTE-URL/services/rest processing started
[INFO] org.kie.server.remote.rest.jbpm.RuntimeDataResource preprocessing started
[INFO] org.kie.server.remote.rest.jbpm.RuntimeDataResource preprocessing finished
[INFO] org.kie.server.remote.rest.jbpm.search.ProcessInstanceSearchResource preprocessing started
[ERROR] Problem during …
```
> Add default constructors to fix jrapidoc errors

- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/DecisionTablesIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/InstallFeaturesKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieDMNKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringDependencyKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringMetaInfAppContextKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringjBPMPersistenceKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/RuntimeManagerFeatureKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/SimpleKieSpringKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/WorkbenchModelsKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintDependencyKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintImportIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintProcessDependencyKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintScannerReimportIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintjBPMPersistenceKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/BaseKieServerClientKarafIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJaxbIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJsonIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationXstreamIntegrationTest.java
Folder with containers may grow quite fast in pax-exam folder (few gigabytes). It is not good to keep these folders in default build. This commit disables keeping these folders. It is possible to keep folders using karaf.keep.runtime.folder property. See more details in README in karaf-itests folder.
> Do not keep folders with Karaf container in target folder.

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/client/KieServerMgmtControllerClient.java
Add possibility to use controller client without need to specify specific data objects.
Simplifies its usage from external tests.
> kie-server-tests: Extend controller client methods

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/evaluation.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/usertask.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/JbpmQueriesKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/ProcessSearchServiceIntegrationTest.java
This should fix issues where large results are being returned and  due to page size, tests are unable to find expected instance in the result. I have modified the processes to use unique names so API won't return data that was used by other tests and stayed in history logs. 
Modified process files to use unique names for tasks and processes.
Modified some tests to use one more unique field in the filter.
Modified deleteLog() method to be static and run only once before tests.
@sutaakar Could you take a look please?
> Advanced search tests stabilization

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/JbpmQueriesKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/ProcessSearchServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/TaskSearchServiceIntegrationTest.java
Removes equalsTo filters when querying with date and replaces them
with greaterThanOrEqualsTo to prevent random failures.
Modifies filters to use process instance id to minimize size
of the result returned.
> jbpm-search-tests: Do not use EqualsTo filters with dates

- kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/HistoryResourceImpl.java
- kie-remote/kie-remote-services/src/test/java/org/kie/remote/services/rest/HistoryResourceRestParamTest.java
@krisv @markcoble I decided to relax the regex for the variable value on the rest endpoint as it causes issues on WAS but more importantly we don't limit/restrict on variable values on process level.
> RHBPMS-4794 - History REST endpoints not behaving correctlly on WAS

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
See https://issues.jboss.org/browse/RHBRMS-2874
Before:
After:
Part of an ensemble:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1073
- https://github.com/kiegroup/kie-wb-common/pull/995
> RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImplTest.java
See https://issues.jboss.org/browse/RHBRMS-2878
Before:
After:
> RHBRMS-2878: Start/stop container buttons are in wrong state after container upgrade

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
Cherry picked from https://github.com/kiegroup/droolsjbpm-integration/pull/1073
> [6.5.x] RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImplTest.java
Cherry picked from https://github.com/kiegroup/droolsjbpm-integration/pull/1074
> [6.5.x] RHBRMS-2878: Start/stop container buttons are in wrong state after container upgrade

- jbpm-process-svg/pom.xml
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/SVGImageProcessor.java
- jbpm-process-svg/src/test/java/org/jbpm/process/svg/TestEvalutionSVG.java
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee6-container.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
resolving compilation errors after batik upgrade by https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/45522ac393753e93c6ba3d3350ce41c7240d5b5a
@mbiarnes @tsurdilo could you please have a look?
> JBPM-6274 - Update batik to 1.9 for 6.5.x

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
Cherry picked from https://github.com/kiegroup/droolsjbpm-integration/pull/1073
---
Part of an ensemble:
- https://github.com/kiegroup/kie-wb-common/pull/1002
- https://github.com/kiegroup/droolsjbpm-integration/pull/1082
> [7.2.x] RHBRMS-2874: Start/stop container buttons should be enabled/disabled only when the operation finished

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImplTest.java
Cherry picked from https://github.com/kiegroup/droolsjbpm-integration/pull/1074
> [7.2.x] RHBRMS-2878: Start/stop container buttons are in wrong state after container upgrade

- kie-server-parent/kie-server-maven-plugin/README.md
- kie-server-parent/kie-server-maven-plugin/pom.xml
- kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/gateway/KieServerGateway.java
- kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/DeployMojo.java
- kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/DisposeMojo.java
- kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/KieServerAbstactMojo.java
- kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/UpdateMojo.java
- kie-server-parent/pom.xml
for unmanaged (direct process server) deploy.
fixing license header
kie-server context path is now configurable
deploy runtime strategy is now configurable
rename replace goal in update
> new kie-server-maven-plugin project : deploy, dispose and replace

- kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/jboss-deployment-structure.xml
To return cxf-rt-ws-policy excluded by https://github.com/kiegroup/droolsjbpm-integration/pull/885
> Add CXF dependency to Wildfly/EAP deployable

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/ProcessInstanceSearchResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/TaskSearchResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
@domhanak one more attempt.  I did not test against the various DBs but  DataSetLookupException is what is thrown when the BAD REQUESTs are encountered.  Please test and let me know.
> [7.2.x] JBPM-6027: Advanced Search API shows error code 500 instead of 400

- kie-server-parent/kie-server-api/src/build/revapi-config.json
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/CommandScript.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/AddProblemFactChangeCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/AddProblemFactChangesCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/GetSolverCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/GetSolverWithBestSolutionCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/GetSolversCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/IsEveryProblemFactChangeProcessedCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/SolvePlanningProblemCommand.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/SolverServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/SolverServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/main/java/org/kie/server/remote/rest/optaplanner/SolverResource.java
- kie-server-parent/kie-server-remote/revapi-config.json
- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/OptaplannerCommandServiceImpl.java
- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/SolverServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/AbstractPersistable.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/AddComputerProblemFactChange.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudBalancingGenerator.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/DeleteComputerProblemFactChange.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/cloudbalance-realtime-planning-daemon-solver.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/cloudbalance-realtime-planning-solver.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/cloudbalance-solver.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
@ge0ffrey First implementation of real-time planning on the ES side.
From https://issues.jboss.org/browse/PLANNER-815:
The problem fact changes will be registered by sending POST request to solverId/problemfactchanged with the following payload:
XSTREAM:
```
<org.kie.server.testing.AddComputerProblemFactChange>
<computer>
<id>5</id>
<cpuPower>3</cpuPower>
<memory>4</memory>
<networkBandwidth>2</networkBandwidth>
<cost>390</cost>
</computer>
</org.kie.server.testing.AddComputerProblemFactChange>
```
where AddComputerProblemFactChange is a ProblemFactChange implementation (taken from optaplanner-examples with slight modifications). See JIRA for more details.
> PLANNER-815: Execution server: Support real-time planning

- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/assembly/assembly-ee7-container.xml
Should fix the WAS 9 controller issue.
> JBPM-6085: Exclude jboss-jaxrs-api_2.0_spec

- kie-eap-integration/kie-eap-distribution/pom.xml
- kie-eap-integration/kie-eap-distribution/src/main/assembly/assembly.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/drools/module.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/commons/assembly-component.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/commons/module.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/maven-support/assembly-component.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/project-datamodel-api/assembly-component.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/project-datamodel-api/module.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/project-datamodel-commons/assembly-component.xml
- kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/uberfire/project-datamodel-commons/module.xml
- kie-maven-plugin/pom.xml
- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
- kie-osgi/kie-osgi-platforms/osgi-platform-fuse-6.3/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-drools/pom.xml
- kie-spring/src/test/java/org/kie/spring/CodeVersion.java
- kie-takari-plugin/pom.xml
- pom.xml
This is a mandatory step before merging the repos to form AppFormer single repository.
Related PRs:
https://github.com/AppFormer/uberfire/pull/784
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/487
https://github.com/kiegroup/drools/pull/1397
https://github.com/kiegroup/droolsjbpm-integration/pull/1135
https://github.com/kiegroup/guvnor/pull/484
https://github.com/kiegroup/kie-wb-common/pull/1005
https://github.com/kiegroup/drools-wb/pull/560
https://github.com/kiegroup/optaplanner-wb/pull/205
> AF-540: adapted to use appformer generic java model

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
- kie-server-parent/pom.xml
Most of the other repositories use the IDs without the "x" suffix.
Those are the chosen cannonical names that should be used everywhere.
> [6.5.x] kie-server-tests: unify container profile ids

- kie-performance-kit/src/main/java/org/kie/perf/Executor.java
Hi,
just a minor tweak for kie-performance-kit. Similar PRs will follow for 7.3 and master.
Thanks,
Marian
> [6.5.x] kie-performance-kit: Redirect standard error stream to standard output stream

- kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java
Hi, @mswiderski,
this is only a fix for a bug in kie-performance-kit. Scenario wasn't initialized for warmUp.
> kie-performance-kit:Init scenario in concurrent load suite

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementBaseTest.java
@sutaakar this `@After` method causes hundreds of failures if the client creation in the `@Before` method fails (e.g. incorrect server url).
> Prevent @After method failures

- kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java
Hi,
this is just a fix to correctly obtain KPKLimit annotation from a scenario.
> kie-performance-kit: Get annotation from scenario correctly

- droolsjbpm-bpms-distribution/pom.xml
- droolsjbpm-brms-distribution/pom.xml
*Add in org.jboss.narayana.jta dependency in the pom of brms distribution
*Explicitly defined the org.jboss.narayana.jta dependency in the pom of bpms distribution
> RHBRMS-2772: Missing jta jar in jboss-brms-engine.zip

- droolsjbpm-bpms-distribution/pom.xml
- droolsjbpm-brms-distribution/pom.xml
*Add in org.jboss.narayana.jta dependency in the pom of brms distribution
*Explicitly defined the org.jboss.narayana.jta dependency in the pom of bpms distibution
> RHBRMS-2772: Missing jta-1.1.jar in jboss-brms-engine.zip

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/JobServicesClientImpl.java
Adding check over the containerId to add it as a parameter, allowing ad-hoc creation
> [7.3.x] RHBPMS-4943: New ad-hoc job can't be created

- kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java
* Moved the creation of the JMSConnection to only occur if the interactionPattern is not FIRE_AND_FORGET
* Updated the finally statement for the onMessage method so that it won't attempt to close non-existent connections
> RHBPMS-4876_6.5.x_fix2

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
Currently it was caught in next catch block and showed in server log as an error with stacktrace.
Not existing server template file isn't an error (it can be valid scenario when we start empty controller).
> Show warning in case server template file isn't found

- kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
> [DROOLS-1732] use correct plugin classloader for kie-maven-plugin

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
Adding package security to XStreamMarshaller to avoid `com.thoughtworks.xstream.security.ForbiddenClassException` when unmarshalling java objects comming from kie-server.
Added ability to configure a list of allowed packages using a comma separated list on the `org.kie.server.xstream.enabled.packages` system property. Like `-Dorg.kie.server.xstream.enabled.packages=packageone.**,packagetwo.**`
@jsoltes  @mswiderski could you please review? (Sorry for all the format changes)
> [8.0.x] JBPM-6456: Unable to open tasks that contain subforms.

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/EmptyContainerIntegrationTest.java
KJar deployed to repository using KieServices can interfere with KJars deployed using Maven CLI in case they have same GAV.
Changing artifact id of empty test KJar to prevent this.
> Change test artifact id for empty kjar

- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/DBExternalResource.java
@sutaakar here is the move of registration in the controller from router via async executor. The drawback is it might lead to bit of delays based on the interval the scheduler runs. I changed it to 5 secs to not delay to much but at the same time collect many requests from kie server (one per container and alias) before running the async job.
> RHBPMS-5021 - Duplicate Kie server registration to Smart router

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
- kie-server-parent/kie-server-tests/pom.xml
Useful for example for testing WildFly with Keycloak.
> Skip JMS tests using Maven property

- kie-server-parent/kie-server-tests/pom.xml
JMS tests are currently disabled as they require alignment of test artifacts to WildFly11.
> Initial test support for WildFly11

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/ProcessSearchServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/TaskSearchServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RollingUpdateProcessServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
Fixed by moving dependencies for local tests into separated profile (active by default). It should be automatically picked by IDE when running JUnit tests (verified in Eclipse).
> Fix duplicated classes in test suites

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/ControllerStorageFileWatcher.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorageTest.java
To avoid situation when template maps are empty.
> JBPM-6613: Reload templates from file in one step

- kie-infinispan/pom.xml
@mswiderski @krisv Since Indexing engine got updated to Lucene 6 (because it is needed by Elasticsearch) I needed to force dependency version for this project.
Hibernate Search needs Lucene 5, but Elaticsearch 5 needs Lucene 6.
@porcelli ready to review
> [AF-549-elastic]: Added new indexing backend to add elasticsearch support 

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java
Modify happy path test to verify that task is in proper status after
we called skip on that task via REST.
@tsurdilo @mswiderski Please take a look, I wanted to  add Status checks to other tests, but I guess that is for other JIRA. Can you confirm?
> [6.5.x]RHBPMS-5041: Human Task should be in Obsolete status when we skip

- kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/client/RestKieServicesClientProvider.java
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/main/java/org/kie/server/controller/rest/ControllerUtils.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerClient.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/controller/DefaultRestControllerImpl.java
Jira: https://issues.jboss.org/browse/RHBPMS-4312
Added loading password from a keystore also from other methods
> [RHBMS-4312] Loading pasword from a keystore

- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-spring/pom.xml
Fixing the following warnings
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie:kie-spring:bundle:7.5.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.sun.xml.bind:jaxb-impl:jar -> duplicate declaration of version (?) @ org.kie:kie-spring:[unknown-version], /home/hrk/Devel/github.com/jhrcek/droolsjbpm-integration/kie-spring/pom.xml, line 283, column 17
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie.server:kie-server-services-common:jar:7.5.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie.server:kie-server-common:jar -> duplicate declaration of version (?) @ …
```
> Remove duplicated dependencies

- kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/runtime/ContainerList.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/runtime/ServerInstanceKeyList.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/spec/ServerTemplateKeyList.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/service/RuleCapabilitiesService.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/service/RuntimeManagementService.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/service/SpecManagementService.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/resources/META-INF/ErraiApp.properties
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/RuleCapabilitiesServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/RuntimeManagementServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/SpecManagementServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/AbstractServiceImplTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/RuntimeManagementServiceImplTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/SpecManagementServiceImplTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-mgmt-client/src/main/java/org/kie/server/controller/management/client/rest/RestKieServerMgmtControllerClient.java
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/main/java/org/kie/server/controller/rest/ControllerUtils.java
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/main/java/org/kie/server/controller/rest/RestSpecManagementServiceImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/KieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerStartupIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerStartupIntegrationTest.java
@mswiderski changing the collection return types so objects can be properly serialized when using the new websocket client. So far this was the only way I could the entire graph to be serialized/deserialized without marshaling errors.
> JBPM-6243 - Use model classes for serializing collections

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorageTest.java
Even Files.write() generates 2 file events when modifying content. I suppose the first event is caused by deleting old content, second contains new content.
Adjusted loadTemplateMapsFromFile() to store actual content just in case of missing file, in case of malformed file it will just show warning.
> RHBRMS-3044: Store template map when template file doesn't exist

- kie-server-parent/kie-server-controller/kie-server-controller-client/src/main/java/org/kie/server/controller/client/websocket/WebSocketKieServerControllerClient.java
- kie-server-parent/kie-server-controller/kie-server-controller-client/src/test/java/org/kie/server/controller/client/websocket/WebSocketKieServerControllerClientTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/src/main/java/org/kie/server/controller/websocket/common/WebSocketUtils.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/src/main/java/org/kie/server/controller/websocket/common/decoder/KieServerControllerDescriptorCommandDecoder.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/src/main/java/org/kie/server/controller/websocket/common/decoder/KieServerControllerServiceResponseDecoder.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/src/main/java/org/kie/server/controller/websocket/common/encoder/KieServerControllerDescriptorCommandEncoder.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/src/main/java/org/kie/server/controller/websocket/common/encoder/KieServerControllerServiceResponseEncoder.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/src/test/java/org/kie/server/controller/websocket/common/WebSocketUtilsTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/main/java/org/kie/server/controller/websocket/ConnectedKieServerHandler.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerClient.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/test/java/org/kie/server/controller/websocket/management/KieServerMgmtCommandServiceImplTest.java
Removing JAXB support as JSON is always used.
> JBPM-6243 Simplify WebSocket marshalling utils

- droolsjbpm-bpms-distribution/pom.xml
quartz-oracle and quartz-weblogic are included now in quartz artifact per https://jira.terracotta.org/jira/browse/QTZ-396
> fix for JBPM-4531 - Upgrade Quartz to Version 2.x

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TaskSearchServiceIntegrationTest.java
Some databases (Sybase) store empty string as one space value. Trim the task instance description to make the test pass on Sybase.
> Trim task instance description in TaskSearchServiceIntegrationTest

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/main/java/org/kie/server/remote/rest/drools/CommandResource.java
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
@sutaakar here is back port of #1327 
@etirelli it includes another jira that just adds logging of payload for rules execution that was requested by CEE. I believe it's worth adding to RHDM 7
> [7.5.x] RHDM-232 - ClassNotFoundException when invoking image related operation, RHDM-226 - Print request payload into the log 

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerStartupIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
- kie-server-parent/kie-server-tests/pom.xml
Contains same config as wildfly11. Used for reactivation of PR builder tests.
> Add wildfly10 integration test profile

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerRestImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/util/RestUtils.java
- kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/KieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/ContainerManager.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplTest.java
- kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/DMNKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/JBPMUIKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/OptaplannerKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-swagger/src/main/java/org/kie/server/services/swagger/SwaggerKieServerExtension.java
@etirelli @ge0ffrey @tarilabs @sutaakar 
here is the implementation that aims at providing basic readiness and liveness checks for KIE Server and all extensions activated. 
In general: 
- readiness will either respond with 200 (OK) when it's actually ready or with 503 (Service Unavailable) when it's still booting/deploying containers/waiting for controller.
- liveness (aka health check) will perform following:
- will check readiness
- will check for failed kie containers
- will ask each active extension to health check itself
response codes for health check are same as for readiness. Meaning that any error found will result in response 503, regardless if that is failed container, failed extension or not ready yet
Health check can be invoked in two modes: 
- basic - that will return status …
> JBPM-6740 - Expose readiness and liveness checks in KIE Server

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerNotificationIntegrationTest.java
Add timeout when checking events from event handler, WebSocket communication is asynchronous -> causing random fails when verify method is called sooner than arrive of event.
> Stabilize WebSocketKieControllerNotificationIntegrationTest

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
The jBPM-Query/Search KIE-Server extension/capability has been removed, so we can remove this extension.
> JBPM-6142: Removed unused constant.

- kie-spring/pom.xml
- kie-spring/src/test/filtered-resources/org/kie/spring/CodeVersion.java
Previously, the version update in `CodeVersion.java` was done directly in the tracked file. This resulted in a dirty working tree after `mvn clean install`, which made it difficult to automate local "full downstream" builds.
> Fix code replacement so that it doesn't result in dirty working tree

- kie-camel/src/main/java/org/kie/camel/KieComponent.java
- kie-camel/src/main/java/org/kie/camel/KieConfiguration.java
- kie-camel/src/main/java/org/kie/camel/KieProducer.java
- kie-camel/src/main/java/org/kie/camel/KieServicesConfigurationCustomizer.java
I was trying to reimplement a fabric8 quickstart using the new kie-camel component but I hit 2 issues (and fixed them).
The quickstart is here: https://github.com/nicolaferraro/spring-boot-camel-drools/tree/new-component-draft
First one was that method `executeCommandsWithResults` of the rule service has 2 versions with same number of arguments and they were collapsed by the comparator (it returned 0), so I got a random overloaded instance each time I ran the application.
Second one was that I could not hook into the services configuration to inject some jaxb classes I need to use.
Now I can do: https://github.com/nicolaferraro/spring-boot-camel-drools/blob/new-component-draft/src/main/java/io/fabric8/quickstarts/camel/drools/Application.java#L42-L51
This fixes both.
> Fix kie-camel to allow executing commands

- kie-server-parent/kie-server-tests/pom.xml
CaseServiceIntegrationTest passed locally just fine with wildfly11 profile, let's see what the CI build tells us about the entire test suite.
> Update Cargo configuration to use Wildfly 11

- kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
@mswiderski you were right. There was one occurrence of ExecutorEventSupport in kie-spring-boot. Now it builds.
depends on kiegroup/jbpm#1156
> JBPM-7040 - ExecutorEventSupportEJBImpl EJB does not resolve on WLS and WAS

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/type/JaxbDate.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TaskSearchServiceIntegrationTest.java
in general I made it possible to use jaxbdate object when using custom queries and lists.
> RHBA-409 - JAXB unmarshalls Date object as XMLGregorianCalendarImpl

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
- kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseServiceIntegrationTest.java
- adds negative scenarios to Case mgmt testing in KIE Server
- fixes one smaller issue (return code 404 vs 500)
- reveals difference between error messages provided by JMS and REST:
<"Case with id I don't exist case not found"> vs. <"Could not find case instance "I don't exist case"">
- reveals that Jaxb cannot marshall null when retrieving non-existing case file data
Once we agree on what to do with last two points, I can open a PR to 7.7.x branch.
> JBPM-6935 Adding test coverate for Case mtmg operations

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-sla/src/main/resources/org/kie/server/testing/UserTaskCaseWithSLA.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseSLAComplianceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/UserTaskWithSLA.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/UserTaskWithSLAOnTask.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
It seems that 3-second timeout is too fast for some production DBs, so I increased it to 5 seconds after discussion with @sutaakar.
> Stabilize SLA tests for production DBs

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-sla/src/main/resources/org/kie/server/testing/UserTaskCaseWithSLA.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseSLAComplianceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/UserTaskWithSLA.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/UserTaskWithSLAOnTask.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
> [7.7.x] Stabilize SLA tests for production DBs

- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1470
> [7.7.x] JBPM-7280: Skip removing of container info if not existing

- jbpm-process-svg/src/main/java/org/jbpm/process/svg/SVGImageProcessor.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/NodeSummary.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/RenderType.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/AbstractSVGProcessor.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/JBPMDesignerSVGProcessor.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/SVGProcessor.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/SVGProcessorFactory.java
- jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/StunnerSVGProcessor.java
Changes on **jbpm-process-svg** module to support Diagram SVG is not highlighted on the WB .
A refactor was made to choose the implementation between JBPM Designer or Stunner.
The `SVGImageProcessor` kept the method signature to keep a backward compatibility since this is a library that could be used in may places.
PS: unit tests will be updated later, the PR is to be tested ASAP since this is a blocker.
@romartin 
@LuboTerifaj
> JBPM-7245 Stunner - Diagram SVG is not highlighted on the WB (jbpm-process-svg)

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/DefaultRestrictionPolicy.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/proxy/DefaultRestrictionPolicyTest.java
See: https://issues.jboss.org/browse/RHPAM-1029
Before:
After:
> RHPAM-1029: Smart Router Servers view error

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java
Based on test failure analysis.
For some unknown reason these tests cause random database transaction issues when executed in community Jenkins.
@mswiderski Could it be possible to add "jenkins-pr-builder" profile to Jenkins downstream tests so these tests are skipped for downstream builds too?
> Skip several tests on Jenkins as they tend to be unstable there

- kie-server-parent/kie-server-tests/README.md
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/README.md
Tested on subset of the test suite: common, drools and jbpm. All passed.
> JBPM-7344: Use Tomcat 9 for Kie server integration tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestJmsSharedBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/src/main/resources/usertask.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java
Backport of #1490.
Should be merged after #1491.
> [7.7.x] Try to stabilize testErrorHandlingFailedTo* tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java
This test was ignored by #1489 and unignored (by mistake) in #1490. Now it should be OK.
> Ignore testErrorHandlingFailedToSignal test

- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java
allow the inexistance of configuration file during bootstrap, and update polling
allow some io errors during configuration file update
> [7.7.x] [RHPAM-1382] File watcher doesn't work in case of missing watched file

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/pom.xml
Small refinements as discussed + springboot test jar now has a name ending in -SNAPSHOT instead of a volatile timestamp, so it can be automatically tested with the latest SNAPSHOT version (before it couldn't locate the correct jar file).
> [7.11.x] Stabilize SpringBoot tests

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java
filtering correctly by deployment id
depends on https://github.com/kiegroup/jbpm/pull/1354
> [RHPAM-1600] REST Endpoint for getting errors in a kie-container does n't filter the result by container id

- kie-maven-plugin/pom.xml
Removed takari plugin in the kie-maven plugin to avoid creation of the m2e file until we fix it in the takari code for the takari-maven-plugin
> [Drools-3236] Removed creation of m2e configuration file

- camel-container-tests/camel-container-integration-tests/pom.xml
- kie-server-parent/kie-server-tests/README.md
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
Followup on wildfly14 migration.
I'm renaming the container profiles so they match reality.
I also removed `wildfly10` profiles as they seemed outdated (@sutaakar please check)
Should be merged with:
https://github.com/kiegroup/kie-jenkins-scripts/pull/365
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/875
https://github.com/kiegroup/jbpm/pull/1366
https://github.com/kiegroup/droolsjbpm-integration/pull/1627
https://github.com/kiegroup/kie-wb-distributions/pull/841
> Rename profiles after wildfly14 upgrade

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/UserTaskAdminServiceIntegrationTest.java
To prevent race conditions caused by entity manager shared amoung threads.
For more info see referenced JIRA.
> JBPM-7683: Switching test classes with timer related tests to PPI

- kie-spring-boot/pom.xml
@mswiderski  7.14.x backport is probably not relevant anymore, right?
> Remove Narayana version override from kie-spring-boot

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
As it isn't needed currently.
@rsynek FYI
> Remove drools.compiler.lnglevel from test kjars

- kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
- kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KieServerApplication.java
related to kiegroup/kie-docs#1240
Bean is already declared in [JBPMAutoConfiguration.java](https://github.com/kiegroup/droolsjbpm-integration/blob/15b8555ccdd4dc1ef31d6fdc3c446dbf1f6259b4/kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java#L289-L293).
> Remove redundant bean declaration from Keycloak Springboot sample

- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KieServerTest.java
When kieServicesClient fails to initialize in the @Before method NPE is thrown from @After method, which leads to spurious setup method failures [like these](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/release/job/buildAndDeployLocally-kieReleases-master/18)
> Fix NPE in tests

- jbpm-simulation/src/main/java/org/jbpm/simulation/impl/SimulateProcessPathCommand.java
- kie-infinispan/drools-infinispan-persistence/src/test/java/org/drools/persistence/jta/TransactionTestCommand.java
- kie-infinispan/drools-infinispan-persistence/src/test/java/org/drools/persistence/session/RuleFlowGroupRollbackTest.java
- kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/ConfigurationTest.java
As discussed I moved RegistryContext to kie-internal end updated usages.
@mariofusco @kkufova
PR list:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/348
https://github.com/kiegroup/drools/pull/2174
https://github.com/kiegroup/drools-wb/pull/1012
https://github.com/kiegroup/jbpm/pull/1387
https://github.com/kiegroup/droolsjbpm-integration/pull/1657
> [DROOLS-3177] Move RegistryContext to kie-internal

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerEnvironment.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/StartupStrategy.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/StartupStrategyProvider.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/.gitignore
- kie-server-parent/kie-server-services/kie-server-services-openshift/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/api/KieServerReadinessProbe.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/OpenShiftStartupStrategy.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/CloudClientConstants.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/CloudClientFactory.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateCloudRepository.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepository.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/resources/META-INF/services/org.kie.server.services.api.StartupStrategy
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/resources/META-INF/services/org.kie.server.services.impl.storage.KieServerStateRepository
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-without-label.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map.yml
- kie-server-parent/kie-server-services/pom.xml
By leveraging OpenShift/K8S API server service, a group of individual KieServers can have a consistent and single view of KieServerState. With the help of fabric8.io's OpenShift/Kubernetes java client, changes to the KieServerState data structure which is managed by OCP/K8S API Server can be monitored/watched and change event will be used to trigger an OpenShift DeploymentConfig rollout for automatically refreshing the Pods and in turn its hosted KieServer instances. Due to the smart Routing capability of OCP/K8S, KieServer API calls will not be interrupted providing there are more than one KieServer instances are provisioned. Last, given a group of KieServer instances are manged by one(1) DeploymentConfig which is associated with one(1) ConfigMap for managing KieServerState data, and …
> [JBPM-7834] Provide OpenShiftStartupStrategy

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ContainerFailureRecoveryIntegrationTest.java
- kie-spring/src/test/java/org/kie/spring/jbpm/KieSpringProcessInstanceMigrationServiceImplTest.java
> [JBPM-5215] Reuse deployment descriptor classes from common jBPM module

- kie-maven-plugin/pom.xml
Adding CMMN to class path as not to break integration tests
JIRA: DROOLS-3448, because this is more of a patch to work around the way the test is run:
- maven is started with a new class loader
- the `kie.conf` for CMMNAssemblerService is in the class path of full downstream build, which depends on everything 
- because it is not a direct Maven dependency, it is not in the class loader of the Maven build
- CMMNAssemblerService is therefore loaded from the root classloader
- when `KieAssemblerService`s are processed, all assembler services are found in the maven classpath, so they are loaded from that class loader
- ClassCastException is raised when CMMNAssemblerService is used because it is not an instance of KieAssemblerService (really, it is: but the class `KieAssemblerService` has now …
> DROOLS-3355: Improve Assembler/Weaver API

- kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerReconnectHandler.java
- kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/test/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerReconnectHandlerTest.java
Add proper handler to websocket reconnection
(cherry picked from https://github.com/kiegroup/droolsjbpm-integration/commit/d838c6f967719c102ee8ba3c844d18650c978857)
> [RHPAM-1354] Kie server loses connection to the Business Central (#1534)

- kie-spring/src/main/java/org/kie/spring/jbpm/services/SpringTransactionalCommandService.java
Hi @mswiderski,
please see my investigation in [JBPM-8120](https://issues.jboss.org/browse/JBPM-8120). I tried to do the same as we do in https://github.com/kiegroup/jbpm/blob/00a53b1f4d0524aef9ac5fa43cac83aed141e2c7/jbpm-services/jbpm-shared-services/src/main/java/org/jbpm/shared/services/impl/TransactionalCommandService.java#L101. I have also left there an option to use sharedEntityManager should a user need it. Locally it worked for me, I have also tested -all and -jbpm modules with springboot with one configuration (JAXB). Full test run will be done as a part of a nightly build. In case you have any suggestions for improvement, feel free to alter this PR.
Test coverage is provided by [CaseRuntimeDataServiceIntegrationTest#testGetCaseInstanceDataItems](https://github.com/kiegroup/drools …
> JBPM-8120 - Case Data is inserted twice in springboot

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/KieServerStateRepositoryUtils.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileInit.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileRepository.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerStateTest.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/storage/file/KieServerStateFileInitTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/OpenShiftStartupStrategy.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateCloudRepository.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepository.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryEnhancedTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryRegularTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryTest.java
Further enhancements to OpenShiftStartupStrategy (See PR https://github.com/kiegroup/droolsjbpm-integration/pull/1611) to allow minimum changes to existing RHPAM Template and initialization scripts. It includes the following:
- Automatically create initial KieServerState ConfigMap with configuration data from System properties.
- Refactored KieServerImple class, and added call to store() method within active/deactive KieContainer methods so as to trigger DC rollouts.
- Minor optimizations to OpenShiftStartupStrategy and test case classes.
> JBPM-7834: Provide OpenShiftStartupStrategy - Enhancements related to RHPAM templates and others

- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringjBPMPersistenceKarafIntegrationTest.java
Timeout raised because when running with specific databases, it takes a long time to initialize the container. 
@jiripetrlik @mariofusco could you please review?
> DROOLS-3543 Raise timeout for BlueprintContainer initialization

- kie-server-parent/kie-server-services/kie-server-services-openshift/pom.xml
As it is not available for Java 11.
@rhtevan Please take a look.
Checked on Java 8 and 11, both compile and pass unit tests.
> JBPM-8154: Exclude tools.jar from kubernetes-server-mock

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
the status is not properly set in the resource response from the kie server
> [JBPM-8153] Container is removed from UI even though it was not possible to stop it.

- kie-server-parent/kie-server-wars/kie-server/src/main/ee7-resources/WEB-INF/web.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/WEB-INF/web.xml
setting servlet 3.1 compliant servlet http constraints.
This will remove the severe log. we will have a default deny by the entries not specified
> [JBPM-8177] Security exceptions in localhost log when running kie-server on JWS

- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
- kie-server-parent/kie-server-api/pom.xml
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/SolutionMarshallingTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/objects/DateObject.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/objects/DateObjectUnannotated.java
https://issues.jboss.org/browse/PLANNER-1356
@mswiderski Please take a look. The real change is only those 4 lines in `JSONMarshaller`. The rest are tests proving that all of the changes are necessary and that it has the expected outcome.
CC @ge0ffrey, @sterobin (Doc), @rsynek or @sutaakar (QE).
> PLANNER-1356: Add out-of-the-box support for java.time.* (un)marshalling to JSON

- kie-server-parent/kie-server-wars/kie-server/src/main/ee-resources/WEB-INF/web.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/WEB-INF/web.xml
For JEE7 and newer the namespace has changed to http://xmlns.jcp.org/xml/ns/javaee [1] , old one was causing crashes on WebLogic.
Checked on all supported application servers.
@elguardian FYI
[1] https://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/index.html
> JBPM-8177: Use correct namespace for servlet 3.1

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceMigrationIntegrationTest.java
@mswiderski 
This should give us a better hint in future when we again for whatever reason send an empty PID list to migrate.
> Add additional asserts for migration tests

- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/application.properties
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
depends on https://github.com/kiegroup/jbpm/pull/1443
2 changes:
* default application.properties of integ-tests-sample shouldn't use swagger, since it is not configured (dismisses the warning)
* kie-server-spring-boot-sample will get JAX-WS API from jbpm-workitems-bpmn2 (previously it wasn't the root module who needed that dependency)
> Fix springboot on JDK 11 (jax-ws-api)

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/KieServerInfo.java
Default KIE Server mode is KieServerMode.DEVELOPMENT, so we should reflect it in KieServerInfo entity as well.
@mswiderski I have also noticed that although by default DEVELOPMENT mode is activated, which will allow undeployment while there are still active process instances present, it won't abort them by default. Thus leaving the developer in a possibly inconsistent situation. Shouldn't we make this aborting default in DEVELOPMENT mode? Currently it is not very safe. Perhaps explicitly allowing to undeploy without aborting of processes would be better?
> KieServerInfo has KieServerMode.REGULAR as a default KIE Server mode

- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
This library was added to features.xml but was missing in features for Fuse
> [7.18.x] Add missing big math library to DMN Fuse feature

- kie-gwthelper-maven-plugin/Readme.md
- kie-gwthelper-maven-plugin/pom.xml
- kie-gwthelper-maven-plugin/src/main/java/org/kie/maven/gwthelper/plugin/AddSourceMojo.java
- pom.xml
@ederign @porcelli @manstis @danielezonca
Scope of this PR is to add the org.kie:kie-gwthelper-maven-plugin to droolsjbpm-integration.
For some reason, I have to disable enforcer check to build the plugin, since it fails on java version.
I see the enforcer is configured to have "8" as version, and in my machine I have JDK 1.8. Other modules correctly build, but I could not figure out what is the issue.
> [DROOLS-3654] Add org.kie:kie-gwthelper-maven-plugin

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerHealthCheckControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/java/org/kie/server/controller/common/KieControllerServletListener.java
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/java/org/kie/server/controller/common/StandaloneControllerApplication.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerCrashIntegrationTest.java
added logic to the standalone controller to remove servers that were killed or crashed
> [JBPM-7974] kie-server not removed from the controller view if server  is killed or crashes

- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyPmmlMultipleTimesIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyRegressionModelIntegrationTest.java
To prevent container creation timeout issues on slower machines.
@jiripetrlik Please take a look.
> Extend timeout for PMML tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyPmmlMultipleTimesIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyRegressionModelIntegrationTest.java
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1757
> [7.18.x] [changes in tests] Extend timeout for PMML tests

- camel-container-tests/camel-container-tests-api/pom.xml
- camel-container-tests/camel-container-tests-module/pom.xml
- kie-camel/pom.xml
- kie-osgi/kie-karaf-features/pom.xml
- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
- kie-server-parent/kie-server-common/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-client/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-rest/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-standalone-impl/pom.xml
- kie-server-parent/kie-server-remote/kie-server-client/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterUnavailabilityIntegrationTest.java
- kie-server-parent/kie-server-wars/kie-server/pom.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee8-container.xml
- kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-servlet-container.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-drools/pom.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/pom.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-optaplanner/pom.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
- kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/pom.xml
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/pom.xml
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
upgraded to jboss-jaxrs-api_2.1_spec
excluded org.glassfish.jaxb:jaxb-runtime from resteasy since duplicated classes were found
> BAPL-1148: updated to org.dom4j

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
> [7.18.x] RHPAM-1988 - KIE Server client does not reuse marshaller for JMS

- kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/main/java/org/kie/server/controller/openshift/storage/ServerTemplateConverter.java
Improve resiliency by accommodating unexpected character case.     
Related JIRAs
https://issues.jboss.org/projects/RHPAM/issues/RHPAM-1975
https://issues.jboss.org/browse/KIECLOUD-121
> [RHPAM-1975] ServerTemplateConverter breaks with KieServerMode mixed-case

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerHealthCheckControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/java/org/kie/server/controller/common/KieControllerServletListener.java
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/java/org/kie/server/controller/common/StandaloneControllerApplication.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerCrashIntegrationTest.java
added logic to the standalone controller
cherry picked from #1712
> [JBPM-7974] kie-server not removed from the controller view if server is killed or crashes (7.18.x)

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerCrashIntegrationTest.java
To make KieControllerCrashIntegrationTest more reliable on slower machines.
@elguardian  Can you please take a look?
> Reduce the Kie server controller ping timeout

- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/KieServerControllerConstants.java
- kie-server-parent/kie-server-controller/kie-server-controller-openshift/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/main/java/org/kie/server/controller/openshift/storage/ServerTemplateConverter.java
- kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/java/org/kie/server/controller/openshift/storage/OpenShiftServerTemplateStorageTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/java/org/kie/server/controller/openshift/storage/ServerTemplateConverterTest.java
- kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/resources/test-kieserver-state-config-map.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/api/KieServerOpenShift.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/api/KieServerOpenShiftConstants.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/OpenShiftStartupStrategy.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateCloudRepository.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepository.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryDetachedCMBCTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryDetachedCMKIETest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryRegularTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-detached-bc.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-detached-kie.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-used-with-container.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-used-with-stopped-container.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-used-without-container.yml
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/resources/test-kieserver-state-config-map-used.yml
In response to request from (https://issues.jboss.org/projects/JBPM/issues/JBPM-8150), this PR includes the implementation remove the coupling between KIE server id and name of KIE server Deployment config, allowing users to choose whatever KIE server id they want, during creation of template or later.
> [JBPM-8150] [RHPAM-1975] Allow users to change Kie server id in Deployment config and templates

- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepository.java
This PR is one of the step towards completely addressing this issue. It will be coordinated with other Kie Operator changes which updates the KieServerCM label from 'USED' to 'DETACHED' once KieServerDC scale down to 0. Then, the new capability brought by this PR will remove the correspondent 'serverInstances' from the 'ServerTemplate'. As a result, the 'REMOTE SERVER' list will be empty by revisiting the BC->AdminServer section or manually clicking SERVER CONFIGURATION 'refresh' button.
Related PRs
https://github.com/kiegroup/droolsjbpm-integration/pull/1780
> [RHPAM-2008] HTTP 503 error is shown in Monitoring console when Kie server is scaled to 0

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-rest/src/main/java/org/kie/server/controller/rest/RestKieServerControllerImpl.java
This PR is a continuation towards completely addressing the issue specified by [RHPAM-2008]. It enhances KIE Server controller REST implementation with simplified CONNECT and DISCONNECT REST/API calls so that external utilities can send a 'signal' to simulate KIE Server instance connecting with/disconnecting from BC/WB->EmbeddedController.  
Related JIRA Comments:
https://issues.jboss.org/browse/RHPAM-2008?focusedCommentId=13722751&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13722751
Related PRs
https://github.com/kiegroup/droolsjbpm-integration/pull/1807
> [RHPAM-2008] HTTP 503 error is shown in Monitoring console #2

- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
Shade drools-model file based on the GAV of the KJar in order to support multiple modules in a KieClassPathContainer
No test attached, but there's a repdroducer attached in  
https://issues.jboss.org/browse/DROOLS-3875
> [DROOLS-3875] Shade drools-model file based on the GAV of the KJar 

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
backport from
http://git.app.eng.bos.redhat.com/git/kiegroup/droolsjbpm-integration.git/commit/?h=RHPAM-5212&id=260829a23bf0f48b02675f3c13f86bb7255a045a
> [RHBPMS-5252] Memory leak when repeatedly create and delete containers

- kie-camel/pom.xml
According to this
https://stackoverflow.com/a/44442682/4206
XercesImpl is needed
> [RHDM-851] Xerces is needed to run camel tests on IBM JDK

- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/api/KieServerOpenShift.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryDetachedCMBCTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryDetachedCMKIETest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryRegularTest.java
- kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryTest.java
This PR is a continuation towards completely addressing the issue specified by [RHPAM-2008]. It fixes a subtle issue which is that the value of kie-server-state label can be overwritten (Expected value: DETACHED; but being changed to USED) during the KIE Server termination when DC scales down to 0. As a result, it will defeat the capability introduced by the lifecycle hook script.    
Related JIRA Comments:
https://issues.jboss.org/browse/RHPAM-2008?focusedCommentId=13737574&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13737574
Related PRs
#1809
> [RHPAM-2008] HTTP 503 error is shown in Monitoring console (3)

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/util/RestUtils.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/StackTraceIncludedIntegrationTest.java
@MarianMacik added test into kie-server-integ-tests-all and change _errorMessage_ method to print always default message (and then, complete stack trace if property is enabled)
> [JBPM-8399] Added test for complete error stacktrace returned by kie-server

- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
follows what was done with
https://github.com/kiegroup/droolsjbpm-integration/pull/1737
@jiripetrlik can you please check? I cannot reproduce the reproducer locally.
/cc @etirelli
> RHDM-975 Add missing ANLT4 library to DMN Fuse feature

- process-migration-service/frontend/server.js
- process-migration-service/frontend/src/component/tabMigrationPlan/wizardAddPlan/PageDefinition.js
- process-migration-service/src/main/java/org/kie/processmigration/model/exceptions/ProcessDefinitionNotFoundException.java
- process-migration-service/src/main/java/org/kie/processmigration/rest/KieServiceResource.java
- process-migration-service/src/main/java/org/kie/processmigration/service/KieService.java
- process-migration-service/src/main/java/org/kie/processmigration/service/impl/KieServiceImpl.java
Fix https://issues.jboss.org/browse/JBPM-8491
Propagate 404 when necessary instead of throwing 500 error.
The KieServer API filters by container alias and container id. In order to prevent inconsistencies when migrating, an additional validation has been added to enforce containerID matches the request.
Besides, in the frontend side the errors are captured to prevent user from moving forward with invalid data
> [JBPM-8491] Do not allow filter by container alias

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/KieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplDevelopmentModeTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/JbpmKieServerExtensionTest.java
@mswiderski  @domhanak would you mind take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kie-wb-common/pull/2681
https://github.com/kiegroup/droolsjbpm-integration/pull/1839
> AF-2011: Redeploy does not abort running process instances when their process definition is deleted

- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/InstrumentationTest.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
Fix includes the unit test of @tkobayas
https://github.com/kiegroup/droolsjbpm-integration/pull/1855/commits/3564f00ea05315dc659c9b4919ab889dbb1d0201
> [DROOLS-4263 ]kbase.cache is not generated in kjar by kie-maven-plugin #1855

- camel-container-tests/camel-container-integration-tests/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/model-wrapper/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/kjar-with-instrumentation-wrapper/pom.xml
- kie-integration-test-coverage/kie-maven-plugin-tests/test-suite/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
- kie-server-parent/kie-server-wars/kie-server-distribution/pom.xml
- kie-spring-boot/kie-spring-boot-starters/pom.xml
enabled the maven-jar-plugin again because the disabling of it causes much more problems then the problem:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project appformer-js: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
This error has to solved ASAP.
> revoked the disabling of maven-jar-plugin

- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/scorecard_mm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/scorecard_mm/src/main/resources/META-INF/kmodule.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyScorecardMultiModuleIntegrationTest.java
@lanceleverich Can you please take a look? This is the fix for https://github.com/kiegroup/droolsjbpm-integration/pull/1860 .
However it is not fully working yet. The PMML call fails on "Cannot find a default KieSession". The problem is that Kie server expect container to have stateful Kie session by default unless specified otherwise. I am not sure about the PMML backgroud, should stateful or stateless session be used?
> Fix for DROOLS-4278 integration test

- kie-identity-session-provider/pom.xml
- pom.xml
The commit https://github.com/kiegroup/droolsjbpm-build-bootstrap/commit/34dfe2ec1c3634a0d06db0b16f49b57e5e085301 moved uberfire-bom from appformer into droolsjbpm-build-bootstrap, with uberfire-bom version kept as Appformer version. Since this is not very user-friendly and breaks product build, this PR proposes a change of uberfire-bom version to KIE version to align it with the rest of the BOMs.
Related PRs: 
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1009
- https://github.com/kiegroup/appformer/pull/746
- https://github.com/kiegroup/drools-wb/pull/1198
- https://github.com/kiegroup/jbpm-designer/pull/856
- https://github.com/kiegroup/jbpm-wb/pull/1375
- https://github.com/kiegroup/kie-uberfire-extensions/pull/87
- https://github.com/kiegroup/kie-wb-common/pull/2780
- …
> changed uberfire-bom version to KIE version

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestSubFormsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
> BAQE-982: Remove cargo-core-uberjar from Kie server test dependencies

- kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
- kie-plugins-testing/src/test/projects/kjar-8-multimodule/modA/src/main/resources/META-INF/kmodule.xml
Related Drools PR: https://github.com/kiegroup/drools/pull/2507
Fixes that now all project files are included in the build. Originally only resources were included, however when having a project pom.xml included in the build, the projects dependencies are automatically added to the build. This fixes a scenario when one KieBase includes another KieBase from a dependency KJar. 
JIRA: https://issues.jboss.org/browse/DROOLS-4440
@etirelli could you please review as Mario and Luca are on PTO?
> DROOLS-4440 Include whole project in kie-maven-plugin build

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
This fixes stack trace inclusion tests for Spring Boot.
> Include stack trace configuration for Spring Boot KIE Server

- kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java
- kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieSessionLookupHandler.java
- kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/SolverServiceBase.java
- kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus/PrometheusCustomMetricsSupport.java
- kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus/PrometheusKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus/PrometheusMetricsProvider.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-prometheus/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-prometheus/src/main/java/org/kie/server/ext/prometheus/ExampleCustomPrometheusMetricListener.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-prometheus/src/main/java/org/kie/server/ext/prometheus/MyPrometheusMetricsProvider.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-prometheus/src/main/resources/META-INF/services/org.kie.server.services.prometheus.PrometheusMetricsProvider
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/filtered-resources/kjars-sources/function-definition/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/filtered-resources/kjars-sources/function-definition/src/main/resources/FunctionDefinition.dmn
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/filtered-resources/kjars-sources/function-definition/src/main/resources/META-INF/kmodule.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/java/org/kie/server/integrationtests/extension/custom/PrometheusCustomExtensionIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
**Preview only** Adds support for user-provided custom Prometheus metrics. @cristianonicolai would you please help me review the jBPM part? It still needs some work. Custom listeners need to be packaged as a jar and included in WEB-INF/lib of the kie server similar to @mswiderski example at http://mswiderski.blogspot.com/2015/12/kie-server-extend-existing-server.html 
An example project to demonstrate custom listeners is at https://github.com/vblagoje/example-prometheus See custom listeners at https://github.com/vblagoje/example-prometheus/tree/master/custom-kie-ext
> [DROOLS-4255] Add KIE server support for deploying custom Prometheus metrics

- kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java
added some logic to print the message just the first time
> [JBPM-8400] Logs are constantly flooded with 'Unable to load key store. Using password from configuration'

- kie-maven-plugin/pom.xml
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/ProjectPomModel.java
- kie-maven-plugin/src/test/java/org/kie/maven/plugin/ProjectPomModelTest.java
- kie-maven-plugin creates a PomModel for KieBuilder instead of KieBuilder creating the PomModel itself. KieBuilder doesn't have access to all Maven build information to build a proper model. kie-maven-plugin does have this information, therefore is used to build the PomModel. 
This needs to be merged with https://github.com/kiegroup/drools/pull/2572
> DROOLS-4602 Create PomModel for KieBuilder directly in kie-maven-plugin

- kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/OpenShiftStartupStrategy.java
The solution is moving away from annotating KieServer DC with a change timestamp for triggering a rollout to leveraging fabric8 client deployment API directly.
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
> [RHPAM-2421] OpenShiftStartupStrategy doesn't respin Kie server pods after Kie container change.

- kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java
added some logic to print the message just the first time
> [7.26.x] [JBPM-8400] Logs are constantly flooded with 'Unable to load key store. Using password from configuration'

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/ImageServiceBase.java
Added a property to increase the number of nodes retrieved from database
> [JBPM-8885] Nodes after multi-Instance subprocess are not blurred eventhough process instance is completed.

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplOperationTest.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/util/DummyKieServerExtension.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/KieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/KieServerContainerListFilteringIntegrationTest.java
the system registers the container even before the container was created causing problem during unregistering (cannot dispose because the container is null in the registered instance so it cannot 
dispose in kieservice container map. The solution is to delay till we have the container active and then
overwrite the container.
> [JBPM-8864] not able to delete kieContainer after deploying container several times with same containerID due to an error

- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/planner/PlannerCloudBalanceIntegrationTest.java
OptaPlanner no longer throws exception if the entity collection is empty. That caused the test to fail because no exception was thrown. But it still throws exception if the value provider returns an empty collection. We can exploit this behavior to keep the negative test.
I personally don't see much value in this test but it is possible that it covers exception propagation in the Fuse environment. Jiri is on a leave this week so we cannot ask him so I'm proposing a fix that keeps the test in place and makes it pass. We can discuss with Jiri and decide to remove the test later.
> PLANNER-1739: Quick fix for OptaPlanner test broken by PLANNER-241

- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/UIServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/UIServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/UIServicesClientTest.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/FormResource.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormServiceBase.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/FormServiceBaseTest.java
When using bypass auth user, FormService now can use the "user" query parameter to check permissions to see task instead of using the authenticated user.
> [JBPM-8931] Form Retrieval not honouring bypass auth user setting

- optaplanner-workbench-models/pom.xml
Fixes build order so that `optaplanner-workbench-models-datamodel-api` is built before `kie-maven-plugin`.
> PLANNER-1317: Fix parent of optaplanner-workbench-models

- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/planner/PlannerCloudBalanceIntegrationTest.java
- kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/planner/domain/CloudBalance.java
https://issues.redhat.com/browse/PLANNER-1745
Follows up on #1957.
- Removed negative test that has little value and would break soon again.
- Removed deprecated API.
- Using fluent config API.
- Removed raw type usage, plus other cleanup.
> PLANNER-1745: Eliminate deprecated OptaPlanner API, clean up test

- kie-server-parent/kie-server-tests/pom.xml
Allows running Kie server on EAP7 with custom-container profile activated.
@MarianMacik Please review.
> Supply valid EAP URL parameter for Cargo

- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/ee7-resources/WEB-INF/web.xml
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/webc-resources/WEB-INF/web.xml
Adding "/docs/*" url-pattern to web.xml to enabling access to swagger docs URL for jbpm controller.
Please review if it's a feasible approach.
> JBPM-8974 Added swagger /docs url-pattern to web.xml

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerValidationIntegrationTest.java
For more details see https://issues.redhat.com/browse/JBPM-8976
> JBPM-8976: Fix kie-server expected capabilities comparison

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-scenario-simulation/src/main/java/org/kie/server/remote/rest/scenariosimulation/ScenarioSimulationResource.java
@yesamer @dupliaka 
https://issues.redhat.com/browse/DROOLS-4980
> [DROOLS-4980] Test Scenario: add @Consumes info 

- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/KieCamelTestSupport.java
Once https://github.com/kiegroup/drools/pull/2745 is built, this test should succeed.
Don't merge before https://github.com/kiegroup/drools/pull/2745 .
> [DROOLS-4600] Embedded Camel endpoints don't work with executable model

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerSwaggerIntegrationTest.java
Add test for automation [jbpm#1976](https://github.com/kiegroup/droolsjbpm-integration/pull/1976#) in ee7 and webc deployments.
> [JBPM-8974] Add test to access Swagger docs in a jBPM headless controller

- pom.xml
Jacoco exceeds allowed method length limit when instrumenting such generated classes.
> Exclude *Lexer classes from instrumentation

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/ProcessExecutor.java
The purpose is to get rid of MavenCLI which brings undesired undeclared dependencies like Xerces, causing issues like https://github.com/kiegroup/droolsjbpm-integration/pull/2014#issuecomment-587384823
> Refactor KJar builds for Kie server tests to use installed Maven binary

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/swagger/SwaggerIntegrationTest.java
- kie-server-parent/kie-server-wars/kie-server/src/main/ee-resources/WEB-INF/web.xml
Analogous to controller, it's needed to add a trailing slash plus asterisk in the url-pattern for swagger.json at `web.xml` to avoid 403 Forbidden error when accessing to that file in Websphere.
> [JBPM-9029] Fix access to swagger.json for KIE Server in Websphere

- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/ee7-resources/WEB-INF/web.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerSwaggerIntegrationTest.java
This test was failing at Websphere due to parent path navigation provoked HTTP 404 response.
Let's fix it creating the URL ad-hoc.
> [JBPM-8974] Fix Swagger docs test for working at WAS also

- kie-maven-plugin/pom.xml
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/DMNModelMode.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/ExecModelMode.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateDMNModelMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/ProjectPomModel.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/ValidateDMNMojo.java
- kie-maven-plugin/src/main/resources/META-INF/plexus/components.xml
- kie-maven-plugin/src/test/java/org/kie/maven/plugin/ValidateDMNMojoFlagsTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/decision-services/src/main/resources/ImportDecisionService20180718.dmn
please note tests are provided by takari framework here: https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-plugins-testing/src/test/projects/kjar-7-with-dmn
@etirelli @baldimir @hellowdan 
/cc @DuncanDoyle 
If I introduce an Error which is subject of the model analysis:
Then, if I really want to try anyway, by disabling the kie-maven-plugin flag:
I will get the same trouble now because the DMN compilation would, naturally, fail:
Once review approved, I will write the doc N&N
> DROOLS-5020 DMN wire Validator to kie-maven-plugin Maven build

- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
When the mode was configured for SpringBoot then this change was forgotten.
> Set correct Kie server mode in policy test suite for SpringBoot

- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/2031
> [7.33.x] Set correct Kie server mode in policy test suite for SpringBoot

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/swagger/SwaggerIntegrationTest.java
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/pom.xml
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/IntegrationTestsWebSecurityConfig.java
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/application.properties
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/swagger.properties
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
- kie-spring-boot/kie-spring-boot-samples/pom.xml
Depends on [droolsjbpm-build-bootstrap#1199](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1199)
After enabling Swagger capability for integration testing of kie server at Springboot, some modifications are needed:
- Swagger UI is exposed in a different endpoint:  
`[context]/api-docs?url=[context]/swagger.json`
so it's needed to make the test compatible for both endpoints
- Swagger cxf libraries have to be added to the _kie-server-spring-boot-integ-tests-sample_ project  as well as the Swagger UI. 
_Notice that due to a bug at **swagger-jaxrs** in latest versions (No message body writer has been found, when retrieving json files), this dependency must to be downgraded to **1.5.15**, as [current documentation recommends](https://github.com/kiegroup/kie-docs/blob/master/doc-co …
> Fix Springboot Swagger tests

- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/BatchTest.java
Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2011 to 7.33.x branch
> [RHDM-1237] Ensure all executable model classes are generated

- camel-container-tests/camel-container-integration-tests/pom.xml
https://issues.redhat.com/browse/RHPAM-2800
according to http://maven.apache.org/pom.html#Plugins
> RHPAM-2800: fixing pom.xml validity for XSD validation

- camel-container-tests/camel-container-integration-tests/pom.xml
> [7.33.x] RHPAM-2800: fixing pom.xml validity for XSD validation (#2051)

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/resources/userinfo.properties
- kie-server-parent/kie-server-tests/pom.xml
provision tests
Needed after [droolsjbpm-integration#2048](https://github.com/kiegroup/droolsjbpm-integration/pull/2048) due to in Keycloak we have "administrator" user in lowercase as Keycloak doesn't allow using capital letters.
> [BAQE-1367] administrator user should be lowercase to match keycloak

- process-migration-service/pom.xml
They are now managed by kie-parent.
PR group:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1273
- https://github.com/kiegroup/appformer/pull/943
- https://github.com/kiegroup/droolsjbpm-integration/pull/2064
- https://github.com/kiegroup/kie-wb-common/pull/3269
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/296
- https://github.com/kiegroup/optaweb-employee-rostering/pull/425
> BXMSPROD-741: Remove Node and npm versions

- kie-camel/pom.xml
- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/BatchTest.java
- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/CamelEndpointWithJaxWrapperCollectionTest.java
- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/XStreamBatchExecutionTest.java
This fix is related to DROOLS-2965 where order was reversed. It is no longer
possible to compare exact content of XMLs. Only unmarshalled values are compared.
> Kie-camel tests no longer depends on exact order of rules evaluation

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
Added property `org.kie.server.bypass.auth.user=true` inside **start-springboot** just for _kie-server-integ-test-jbpm._
> [RHPAM-2813] Add springboot property to bypass auth user

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-scenario-simulation/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
Removed process-exec-maven-plugin overwritten at child pom, passing these properties with their default value to parent, for better maintainability.
> Enhance maintainability at springboot kie-server-integ-tests-policy pom

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/secured-project/pom.xml
> [JBPM-9121] Add missing jaxb dependency in integration test

- kie-server-parent/kie-server-tests/pom.xml
This PR alligns dependecies of wildfly and eap7 profiles. We recently updated wildfly profily but seems same updates are needed alos for eap7.
For more details see:
- https://github.com/kiegroup/droolsjbpm-integration/pull/2033/files
- https://issues.redhat.com/browse/JBPM-9152
> JBPM-9152: Add missing netty dependencies

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FormServiceIntegrationTest.java
Added test to retrieve formName from kie-server.
**formName** was missing on _ConvertUtils.convertToTask_ method.
Related to [jbpm#1647](https://github.com/kiegroup/jbpm/pull/1647)
> [JBPM-9147] getTaskById does not return formName

- kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/src/test/java/org/kie/server/integrationtests/taskassigning/TaskAssigningIntegrationTest.java
As the change of dependencies is going to be bigger than I originally thought, let's merge the timeout increase first.
> PLANNER-1938 Increase timeout for task assigning test

- kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/pom.xml
- removes the exclusion of javax.activation:activation from the test classpath
- removes the local-test-run, as it's not used and drags in conflicting dependencies (e.g. javax.activation:activation-api)
> PLANNER-1989 Fix task assigning test on Java 11

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/pom.xml
System scope was used in a try to speed up test execution, however without significant effect.
Provided scope is aligned with purpose of kjar dependencies.
Changes in https://github.com/kiegroup/droolsjbpm-integration/pull/2105 made build if these kjars failing unless artefacts with system scope were available in local repository. With this fix these artefacts are properly downloaded when kjar is built.
> Use provided scope for kjar dependencies for Kie server tests

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/MarshallingFormat.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/marshal/MarshallerHelper.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/marshal/MarshallerHelperTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/QueryServiceRestOnlyIntegrationTest.java
New fields "parameter" in content type. If value is non-null alternative
object mapper is used to prevent null serialization
> [RHPAM-2911] Null fields should not be included in JSON response

- process-migration-service/pom.xml
BXMSPROD-598
It depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1156
filterWebInfLib property added with the value 'uberjar-only' to thorntail maven plugin to the business-monitoring-webapp and business-central-webapp
> BXMSPROD-598 filterWebInfLib property added to thorntail maven plugin

- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/local-date-unary-check/pom.xml
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/2135
> [7.39.x] Fix DMNLocalDateIntegrationTest execution on Java 11

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-scenario-simulation/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/pom.xml
- kie-server-parent/kie-server-tests/pom.xml
- process-migration-service/pom.xml
By using container.profile for triggering of integration tests this repository will align with integration tests in jbpm repository.
It will also fix the current PR check issue caused by missing `wildfly` profile in Maven command.
> Use container.profile property to activate tests for application server

- kie-spring-boot/pom.xml
We upgraded to Spring Boot 2.2.6.RELEASE where dependencies in KIE-SPRING-BOOT module was left behind
https://issues.redhat.com/browse/RHPAM-2734
> [RHPAM-2734]: syncing SB 2.2.6 deps

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskEventInstance.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskInstance.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskSummary.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/ConvertUtilsTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseSLAComplianceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
Depends on [jbpm:1689](https://github.com/kiegroup/jbpm/pull/1680) and https://github.com/kiegroup/droolsjbpm-knowledge/pull/447
correlationKey and processType has been added to TaskInstance and
TaskSummary
> [JBPM-9195] Case traceability from a Task Instance

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerRuleCapabilitiesIntegrationTest.java
- Ignores the following two random failing tests
WebSocketKieControllerRuleCapabilitiesIntegrationTest.testStartAndStopScann
WebSocketKieControllerRuleCapabilitiesIntegrationTest.testScanNow
> JBPM-9246: Ignore random WebSocketKieControllerRuleCapabilitiesIntegrationTest failing test

- kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/src/test/java/org/kie/server/integrationtests/taskassigning/TaskAssigningIntegrationTest.java
As the test is unstable for these databases.
> [PLANNER-2079] Skip TaskAssigningIntegrationTest for MySQL and MariaDB

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/src/main/resources/query-definitions.json
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
for case-sensitive dbs
Backport from [droolsjbpm-integration#2157](https://github.com/kiegroup/droolsjbpm-integration/pull/2157)
> [JBPM-9237][7.39.x] Test queries with columns 'PROCESS_INST_ID', 'ACTIVITY_ID'

- jbpm-process-svg/pom.xml
https://issues.redhat.com/browse/JBPM-9231
parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1395
> JBPM-9231: removed exclusion for batik-ext

- camel-container-tests/camel-container-integration-tests/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/ContainerRemoteController.java
- kie-server-parent/kie-server-tests/pom.xml
- process-migration-service/pom.xml
paste the link(s) from GitHub here
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) cdb.\*]**
* a full production downstream please add comment: regex **[.\*[j|J]enkins,?.\*(execute|run|trigger|start|do) product fdb.\*]**
* an upstream build please add comment: regex …
> Dynamically allocate WildFly/EAP ports for integration tests

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/util/QueryParamFactory.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/KieServerApplication.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/marker/KieServerEndpoint.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/marker/KieServerEndpointRequestFilter.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/test/java/org/kie/server/remote/rest/common/marker/KieServerEndpointRequestFilterTest.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-swagger/src/main/java/org/kie/server/remote/rest/swagger/ReadOnlySwaggerDecoration.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-swagger/src/main/java/org/kie/server/remote/rest/swagger/SwaggerRestApplicationComponentsService.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-swagger/src/test/java/org/kie/server/remote/rest/swagger/ReadOnlySwaggerDecorationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
Jira: https://issues.redhat.com/browse/JBPM-9296
> [JBPM-9296]  Self contained Audit/History module

- kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/security/SpringSecurityIdentityProvider.java
Jira:  https://issues.redhat.com/browse/JBPM-9317
> [JBPM-9317] userTaskService.saveContent doesn't work

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
When an endpoint fails, reason for failure is logged as debug level,
changing it to warn
**JIRA**:
[JBPM-9330](https://issues.redhat.com/browse/JBPM-9330)
> [JBPM-9330] Change log level for endpoint failure

- .github/workflows/pull_request.yml
-DjvmArgs argument is only for Jenkins system environment
<details>
<summary>
</summary>
</details>
> Removed jvmArgs arguments from GA

- kie-maven-plugin/pom.xml
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-5691
**referenced Pull Requests**: requires:
* https://github.com/kiegroup/drools/pull/3138
<details>
<summary>
</summary>
</details>
> DROOLS-5691 Fix (classic) BuildMojo no exec model after descope protobuf

- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/pom.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/src/test/java/org/kie/server/spring/boot/autoconfiguration/audit/replication/AuditDataReplicationKieServerTest.java
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/src/test/resources/application-integrationtest.properties
Jira: https://issues.redhat.com/browse/JBPM-9402
Set to embedded broker instead of using full server with tcp connection
> [JBPM-9402] AuditDataReplicationKieServerTest is in probably in deadlock

- kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/resources/META-INF/kmodule.xml
- kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/resources/org/kie/integration/testcoverage/dmn/basic.dmn
- kie-integration-test-coverage/kie-maven-plugin-no-execmodel-tests/kjar-with-instrumentation-no-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-no-execmodel/src/main/resources/META-INF/kmodule.xml
- kie-integration-test-coverage/kie-maven-plugin-no-execmodel-tests/kjar-with-instrumentation-no-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-no-execmodel/src/main/resources/org/kie/integration/testcoverage/dmn/basic.dmn
- kie-maven-plugin-example/src/main/resources/org/acme/test_generateModel_kjararchetype/test.dmn
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/AbstractDMNValidationAwareMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/ValidateDMNMojo.java
- kie-maven-plugin/src/test/java/org/kie/maven/plugin/ValidateDMNMojoFlagsTest.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-5072
**referenced Pull Requests**: on drools.git:
* https://github.com/kiegroup/drools/pull/3134
@mariofusco @lucamolteni : the DMN Validator, Decision Table static analysis (DT Analysis) requires the DMN model to be in their compiled form, before performing the static analysis on the decision table. To avoid compiling the DMN Models twice, I bind to the 2 main entry point which are building the ~`KieModule` of the KJAR project, that is:
- GenerateModelMojo (exec model, the default)
- BuildMojo (no exec model, classic DRL)
after the KJAR project is compiled by the KieBuilder `buildAll` as before, I launch the analysis of the decision table.
if the decision table static analysis have some error, it trigger the Maven Failure as expected by …
> DROOLS-5072 DMN wire DT static analysis to kie-maven-plugin

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerStartupIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/NotificationSaveContentIntegrationTest.java
**JIRA**: 
[JBPM-9383](https://issues.redhat.com/browse/JBPM-9383)
<details>
<summary>
</summary>
</details>
> JBPM-9383: Mark unstable tests to be skipped by PR check

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerStartupIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/NotificationSaveContentIntegrationTest.java
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/2256
**JIRA**: 
[JBPM-9383](https://issues.redhat.com/browse/JBPM-9383)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2256
<details>
<summary>
</summary> …
> [7.44.x] Mark unstable tests to be skipped by PR check

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseAdminResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/DefinitionResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/DocumentResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ExecutorResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/UserTaskResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/ProcessAdminResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/UserTaskAdminResource.java
Moving response to ApiResponse
**JIRA**: 
[JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)
> [JBPM-9410] No Model definition in KIE Server Swagger API

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
Temporary workaround until the JIRA is addressed.
[JBPM-9309](https://issues.redhat.com/browse/JBPM-9309)
<details>
<summary>
</summary>
</details>
> [JBPM-9309] Skip SLA test for WebLogic

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
**JIRA**: [JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)
Follow-up of #2263 
We don't need to ignore every potentially breaking change. Revapi ignores work like filters and the less specific the filter is, the more it will ignore. So there is no need to ignore them one by one :) If we left the current configuration (only breaking changes are failing the build), we would miss any potential changes in future regarding endpoints, i.e. JAX-RS annotations configuration.
<details>
<summary>
</summary>
* <b>a full …
> JBPM-9410 - No Model definition in KIE Server Swagger API - revapi fix

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
* Added missing ReleaseId field
**JIRA**: [JBPM-9431](https://issues.redhat.com/browse/JBPM-9431)
<details>
<summary>
</summary>
</details>
> JBPM-9431: Unable to add deployment unit while creating very first container

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/StartProcessServiceIntegrationTest.java
Jira: https://issues.redhat.com/browse/JBPM-9416
missing node id list when starting from node ids without correlation key.
> [JBPM-9416] node ids missing from ProcessServiceBase  causing process just being created.

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
* Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2295
(cherry picked from commit 121c1d2d336e20e00a5f68241a77231cde32887d)
**JIRA**: 
* [RHPAM-3254](https://issues.redhat.com/browse/RHPAM-3254)
* [JBPM-9431](https://issues.redhat.com/browse/JBPM-9431)
<details>
<summary>
</summary>
</details>
> JBPM-9431: Unable to add deployment unit while creating very first container (#2295)

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseAdminResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerRestImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/FormResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/DefinitionResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/DocumentResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ExecutorResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/UserTaskResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/ProcessAdminResource.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/UserTaskAdminResource.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/swagger/SwaggerIntegrationTest.java
Moving response to ApiResponse
**Depends on**
[#droolsjbpm-build-bootstrap:1527](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1527)
**JIRA**: 
[RHPAM-3219](https://issues.redhat.com/browse/RHPAM-3219)
> (GSS) [7.44.x] [RHPAM-3219] No Model definition in KIE Server Swagger API

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNContextKS.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/DMNContextKSMarshallingTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/dmn/JSONAPIRoundTripTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/json-applicant/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/json-applicant/src/main/java/com/acme/Address.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/json-applicant/src/main/java/com/acme/Applicant.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/json-applicant/src/main/resources/META-INF/kmodule.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/json-applicant/src/main/resources/model1.dmn
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/json-applicant/src/main/resources/model2.dmn
- kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNJsonApplicantIntegrationTest.java
Unfortunately the **generic kie-server marshaller** for JSON doesn't conform to Jackson's directive such as
```java
@JsonDeserialize(keyAs = String.class)
Map<String, Object> field ...
```
so there is no way to circumvent the following hard-constraint code-path during deserialization: 
https://github.com/kiegroup/droolsjbpm-integration/blob/1032eeb870afeea6dd9a9211b894badb4f1874d6/kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java#L747-L751
That is because for the purpose of the JSON Marshaller, a string literal in JSON for a (json map) field key could identify a class not only if it correspond to the Java's FQCN of a domain object, but also by its **simple name**,
ref a little above here: …
>  DROOLS-5793 kie-server marshaller simpleclass name clash with DMN symbol

- kie-camel/pom.xml
- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/DroolsJaxbHelperXSDInKJARTest.java
showing the reproducer setup in simpler terms.
```
$ mvn clean test -Dtest=DroolsJaxbHelperXSDInKJARTest
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ kie-camel
---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running
org.kie.camel.embedded.camel.component.DroolsJaxbHelperXSDInKJARTest
15:07:05.897 [main] WARN  o.a.m.i.embedder.MavenSettings - Environment
variable M2_HOME is not set
Nov 26, 2020 3:07:07 PM com.sun.xml.bind.v2.util.XmlFactory
createSchemaFactory
SEVERE: null
org.xml.sax.SAXNotRecognizedException:
http://javax.xml.XMLConstants/feature/secure-processing
at javax.xml.validation.SchemaFactory.setFeature(Unknown Source)
at …
```
> DROOLS-5803 Fix kie-camel dep not in MavenCentral xercesImpl 2.12.0.SP02

- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
…e to stop it.
[https://issues.redhat.com/browse/JBPM-8153](JBPM-8153)
* link 2
* link 3 etc.
<details>
<summary>
</summary> …
> JBPM-8153 Container is removed from UI even though it was not possible to stop it.

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
Retrieving containerId using KieServerRegistry just for the API
mentioned in the JIRA
**JIRA**:
[JBPM-9492](https://issues.redhat.com/browse/JBPM-9492)
> [JBPM-9492] Send signals using alias without need to send the instanceid

- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
Using read write lock
**JIRA**:  
[JBPM-9520](https://issues.redhat.com/browse/JBPM-9520)
> [JBPM-9520] KafkaServerExtension poll is not freed

- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
cherry-pick to backport from `master` to `7.48.x` as required by https://issues.redhat.com/browse/RHPAM-3382 
**JIRA**:  https://issues.redhat.com/browse/RHPAM-3382
**referenced Pull Requests**: https://github.com/kiegroup/droolsjbpm-integration/pull/2362
<details>
<summary>
</summary>
</details>
> [7.48.x] RHPAM-3382 It is not possible to create DMN runtime in OSGI environment

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/Marshaller.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/CustomXstreamMarshallerBuilder.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/XStreamMarshallerTest.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/marshal/MarshallerHelper.java
In order to "relax" deserialization requirements, user can specifiy as parameter of contentype, ignoreUnknown=true, which will ignore unknown fields durign xstream deserialization. 
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9558)
Depends on
https://github.com/kiegroup/kie-soup/pull/173
> [JBPM-9558]  KIE using XStream does not complain on unknown fields

- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ContainerInfo.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigurationMarshaller.java
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
This reverts commit 59f3ef91ad04957debc69758ccb82ba79a8212c0.
Jira https://issues.redhat.com/browse/RHPAM-3419
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/2385
> [7.48.x] Revert "[JBPM-9423] Duplicate container-info entries in kie-server-router.json file if we create containers with unique container-alias"

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
[JBPM-8153](https://issues.redhat.com/browse/JBPM-8153)
* https://github.com/kiegroup/kie-wb-common/pull/3553
<details>
<summary>
</summary> …
> [7.48.x]JBPM-8153 Container is removed from UI even though it was not possible to stop it.

- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/KieServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/RuleServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/RuleServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/main/java/org/kie/server/remote/rest/drools/CommandResource.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerBackwardCompatDroolsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/StatefulSessionUsageIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/rest/RestMalformedRequestIntegrationTest.java
API and test changed to return different HTTP codes depeding on service result. 
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9611)
> [JBPM-9611] Command resource returns HTTP OK response status code even for failure scenarios

- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GeneratePMMLModelMojo.java
- kie-plugins-testing/src/test/java/org/kie/maven/plugin/BuildPMMLTrustyTest.java
- kie-plugins-testing/src/test/projects/kjar-12-with-pmml-trusty/pom.xml
- kie-plugins-testing/src/test/projects/kjar-12-with-pmml-trusty/src/main/resources/META-INF/kmodule.xml
- kie-plugins-testing/src/test/projects/kjar-12-with-pmml-trusty/src/main/resources/categoricalvariablesregression/categoricalVariablesRegression.pmml
- kie-plugins-testing/src/test/projects/kjar-12-with-pmml-trusty/src/main/resources/compoundnestedpredicatescorecard/CompoundNestedPredicateScorecard.pmml
- kie-plugins-testing/src/test/projects/kjar-12-with-pmml-trusty/src/main/resources/logisticregressionirisdata/logisticRegressionIrisData.pmml
- kie-plugins-testing/src/test/projects/kjar-12-with-pmml-trusty/src/main/resources/simplescorecardcategorical/SimpleScorecardCategorical.pmml
@danielezonca @mariofusco @jiripetrlik
This PR removes Rules source generation from maven-plugin/GeneratePMMLMojo
Depends on https://github.com/kiegroup/drools/pull/3395
> [DROOLS-5702] Using rules sources generated inside pmml compiler.

- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieControllerExecutor.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerStartupIntegrationTest.java
**[JBPM-9355](https://issues.redhat.com/browse/JBPM-9355)**: Stabilize some jBPM integration tests by upgrading TJWSEmbeddedJaxrsServer embedded server
**referenced Pull Requests**: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1596
> [JBPM-9355] - Stabilize some jBPM integration tests by upgrading TJWSEmbeddedJaxrsServer embedded server

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
- kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/ProcessServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/ProcessServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/restart-project/src/main/resources/BPMN2-SynchronousProcess.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/StartProcessServiceIntegrationTest.java
Jira: https://issues.redhat.com/browse/JBPM-9624
depends on https://github.com/kiegroup/jbpm/pull/1872
> [JBPM-9624] Return the process variables for synchronous execution us cases

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JAXBMarshallerTest.java
Throwing marshalling exception if org.kie.server.strict.jaxb.format is
true
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9636)
> [JBPM-9636] When a non int value is passed as int to jaxb marshaller

- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
**[JBPM-9651](https://issues.redhat.com/browse/JBPM-9651)**: Enforcer exception - duplicated classes in kie-server-services-common
> [JBPM-9651] - Enforcer exception - duplicated classes in kie-server-services-common

- kie-server-parent/kie-server-tests/pom.xml
Add profile for testing of kie server client with Fuse on Springboot bom. It should be possible to specify Fuse on Spring boot version using fuse.springboot.version environment property.
> [DROOLS-6184] Add profile for Fuse on Spring boot

- kie-performance-kit/pom.xml
- kie-performance-kit/src/main/java/org/kie/perf/Executor.java
- kie-performance-kit/src/main/java/org/kie/perf/TestConfig.java
- kie-performance-kit/src/main/java/org/kie/perf/metrics/CPUUsageHistogramSet.java
- kie-performance-kit/src/main/java/org/kie/perf/metrics/PerfRepoReporter.java
BAQE-1706 - Transition to jdk11 and fixing bugs that came out in KIE server tests. Merge together with Kie-benchmark PR and changed test definition in bxms-qe-tests
> BAQE-1706 - Fix for Kie Server error introduced with jdk11

- kie-camel/src/test/java/org/kie/camel/embedded/camel/component/BatchTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/stateless-session-kjar/src/main/resources/kbase1/rules.drl
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/StatelessSessionUsageIntegrationTest.java
Second version of 
https://issues.redhat.com/browse/DROOLS-6177
This is far simpler but should satisfy the needs of a smaller payload
https://github.com/kiegroup/drools/pull/3473
https://github.com/kiegroup/droolsjbpm-integration/pull/2438
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: …
> [DROOLS-6177] Parametrize query command in kie-server to choose the return values

- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/rest/KieServerWithExtraEndpointTest.java
**[JBPM-9687](https://issues.redhat.com/browse/JBPM-9687)**: Stabilize a flaky test with SocketTimeoutException around KieServer
> [JBPM-9687] - Stabilize a flaky test with SocketTimeoutException around KieServer

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/ProcessDefinition.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormRendererBase.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/js/kieserver-ui.js
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/FormRendererBaseTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/DefinitionServiceBase.java
* Added "required" and "readonly" property to FormField by tags
* Fixed validation for input box in ProcessInstance form
**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)
https://github.com/kiegroup/kie-wb-common/pull/3609
https://github.com/kiegroup/jbpm-wb/pull/1486
Original PR : https://github.com/kiegroup/droolsjbpm-integration/pull/2398
<details>
<summary>
</summary>
* <b>a full production downstream build</b> …
> AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty

- kie-server-parent/kie-server-tests/kie-server-integ-tests-scenario-simulation/src/test/java/org/kie/server/integrationtests/scenariosimulation/ScenarioSimulationIntegrationTest.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6263
* https://github.com/kiegroup/drools/pull/3510
* https://github.com/kiegroup/droolsjbpm-integration/pull/2448
<details>
<summary>
</summary>
</details>
> DROOLS-6263: Test Scenario - expected vs actual alert is misleading

- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/events/ContainerSpecUpdated.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/events/ServerTemplateUpdated.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/runtime/ServerInstanceKey.java
- kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/spec/ServerTemplate.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerHealthCheckControllerImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/SpecManagementServiceImpl.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/InMemoryKieServerTemplateStorage.java
Jira: https://issues.redhat.com/browse/JBPM-9729
adding kie server instance online flag and modifying alive ping so the server can have that possibility of comming back alive if there is a network glitch during ping is alive.
> [JBPM-9729] KIE-Server template is removed after a ping failure

- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6369
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1652
<details>
<summary>
</summary>
</details>
> [DROOLS-6369] Fix kie-karaf-itests failures because of guava upgrade

- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/QueryServicesClient.java
- kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9714)
https://github.com/kiegroup/jbpm/pull/1950
> [JBPM-9714] Include sort column to advance queries variables  API

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/FallbackableTypeFactory.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- Compiled with jackson 2.10 and linkable with jackson 2.12 for Fuse 7.9 integration
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6396
This is a special fix for 7.52.x for RHDM/RHPAM 7.11.1 integration with Fuse 7.9 which depends on jackson 2.12.
<details>
<summary>
</summary>
</details>
> [7.52.x] [DROOLS-6396] Fix FallbackableTypeFactory for 7.52.x

- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerProducer.java
- kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionTest.java
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9780)
> [JBPM-9780] Accept all kafka properties

- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
* Fixed input type for Date picker 
**JIRA**: 
[AF-2860](https://issues.redhat.com/browse/AF-2860)
[RHPAM-3454](https://issues.redhat.com/browse/RHPAM-3454)
<details>
<summary>
</summary>
</details>
> AF-2860: Process form renderer for Date objects doesn't submit the correct data

- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/ProxyAwareKafkaEmitterTest.java
**JIRA**: [JBPM-9716](https://issues.redhat.com/browse/JBPM-9716)
Cherry-pick from c8162b722b39b418189f3e4e1f2b2f23105511b5
> [7.52.x][JBPM-9716] Wrong bootstrap servers property in the Kafka Emitter

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/SearchQueryFilterSpec.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
**JIRA**: 
[https://issues.redhat.com/browse/JBPM-9675](https://issues.redhat.com/browse/JBPM-9675)
* https://github.com/kiegroup/jbpm/pull/1900
Allow query tasks by potential owners with ALL or ANY operations.
```
"pot-owners-query-param": {
"cond-operation": "ANY",
"cond-values": ["HR", "IT", "bob"]
}
```
> [JBPM-9675] QueryParam pot-owners

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
Due to updates in https://issues.redhat.com/browse/JBPM-9778, where a new column was added into table, we need to increase checked columns count in QueryDataServiceIntegrationTest.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
* <b>a full …
> JBPM-9778: Update checked columns count

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
- Compiled with jackson 2.10 and avoid issues when linking with jackson 2.12
- Instroduced system property switch "org.kie.server.json.fallbackClassLoader.enabled"
Follows the same approach as https://github.com/kiegroup/droolsjbpm-integration/pull/2507 (7.52.x)
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6522
<details>
<summary>
</summary> …
> [DROOLS-6522] Make FallbackableTypeFactory optional

- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
This change doesn't directly affect the tests executed by CI. Just to prepare for the test with Fuse 7.9.
I tested with fuse-karaf-7.9.0.fuse-790068-redhat-00001.zip locally and confirmed that kie-karaf-itests passed.
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6532
<details>
<summary>
</summary>
</details>
> [DROOLS-6532] align features-fuse.xml with features.xml

- kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionProducerTest.java
**JIRA**:  [BAPL-2054](https://issues.redhat.com/browse/BAPL-2054)
Update Kafka to version 2.8.0
PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1714
- https://github.com/kiegroup/droolsjbpm-integration/pull/2568
- https://github.com/kiegroup/jbpm/pull/1996
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest</b> (using <i>this</i> e.g. <b>Jenkins retest this</b> optional but no longer required)
* <b>an upstream build</b> please …
>  [BAPL-2054] Update MockProducer usage related to Kafka 2.8.0 upgrade

- kie-maven-plugin/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6554
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1730
<details>
<summary>
</summary>
</details>
> [DROOLS-6554] droolsjbpm-integration deploy job failure

- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/DecisionMarshallingTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/SolutionMarshallingTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/XStreamMarshallerTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/json/JSONMarshallerExtensionTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/DroolsCommandMarshallingTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/DroolsCommandWithListMarshallingTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/MarshallingRoundTripNestedClassesTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/MarshallingRoundTripNestedClassesWithAnnotationsTest.java
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6577
<details>
<summary>
</summary>
</details>
> [DROOLS-6577] Suppress info log in kie-server-api unit tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2592
> [7.59.x][JBPM-9885] QueryDataServiceIntegrationTest tests are failing due to removal of end_date column

- kie-server-parent/kie-server-controller/kie-server-controller-openshift/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-openshift/pom.xml
**[JBPM-9872](https://issues.redhat.com/browse/JBPM-9872)**: Banned classes in kie-server-services-openshift artifact
<details>
<summary>
</summary>
</details>
> [JBPM-9872] Banned classes in kie-server-services-openshift artifact

- droolsjbpm-integration-distribution/src/main/assembly/filtered-resources/ReadMeDroolsJbpmIntegration.txt
https://issues.redhat.com/browse/DROOLS-6407
</details>
> [DROOLS-6407] Fix missing droolsjbpm-integration Wording

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
**[JBPM-9885](https://issues.redhat.com/browse/JBPM-9885)**: QueryDataServiceIntegrationTest tests are failing due to removal of end_date column
<details>
<summary>
</summary>
</details>
> [JBPM-9885] QueryDataServiceIntegrationTest tests are failing due to removal of end_date column

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskEventInstance.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java
**[JBPM-9882](https://issues.redhat.com/browse/JBPM-9882)**: Adding actual owner to TaskEvent
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/554
* https://github.com/kiegroup/jbpm/pull/2032
<details>
<summary>
</summary>
</details>
> [JBPM-9882] Adding actual owner to TaskEvent

- kie-osgi/kie-karaf-itests/src/test/filtered-resources/META-INF/persistence.xml
- kie-osgi/kie-karaf-itests/src/test/filtered-resources/org/kie/karaf/itest/blueprint/processpersistence/persistence.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/resources/META-INF/jbpm-persistence.xml
- kie-spring/src/test/resources/jbpm/services/jta-persistence.xml
- kie-spring/src/test/resources/jbpm/services/local-persistence.xml
Jira: https://issues.redhat.com/browse/JBPM-9887
depends on https://github.com/kiegroup/jbpm/pull/2019
> [JBPM-9887] Getting the process id out of the ejb timer column

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/client/RestKieServicesClientProvider.java
[link](https://issues.redhat.com/browse/RHPAM-3988)
> [RHPAM-3988] Make the kieservice client timeout value configurable in RestKieServicesClientProvider used by controller

- kie-osgi/kie-karaf-features/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-6693
> [DROOLS-6693] upgrade to JavaParser 3.23.1

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/RenderFormServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestJmsSharedBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestOnlyBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/jms/ContainerJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerManagementIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerRuleCapabilitiesIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerRuntimeManagementIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/JsonTypeInfoIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/JsonTypeInfoUpdateIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/jms/DroolsJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/KieServerContainerListFilteringIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change …
> [7.59.x] Remove index from parameterized Kie server integration tests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/RenderFormServiceIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestJmsSharedBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestOnlyBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/jms/ContainerJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerManagementIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerRuleCapabilitiesIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerRuntimeManagementIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/JsonTypeInfoIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/JsonTypeInfoUpdateIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/jms/DroolsJmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/KieServerContainerListFilteringIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change …
> Remove index from parameterized Kie server integration tests

- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/FormReader.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/FormRendererTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/various-fields-taskform.json
Added support for java 8 date/time classes in the mapper used to extract parameters. 
In order the browser to render dates properly, the html page returned by form rest API should contain the proper type, Date for LocalDate and DateTime-Local for LocalDateTime and Date
**Merge with** 
https://github.com/kiegroup/kie-wb-common/pull/3706
**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9948)
> [JBPM-9948] Adding Date classes support in forms

- kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerSwaggerIntegrationTest.java
[JBPM-9959](https://issues.redhat.com/browse/JBPM-9959)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2660
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be …
> [7.59.x][JBPM-9959] Add Authorization header for controller Swagger UI requests

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerIntegrationTest.java
Applied fix from https://github.com/kiegroup/droolsjbpm-integration/pull/2719 on one more forgotten place.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …
> Fix TimerIntegrationTest PSQLException on PostgreSQL database

- kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/assembly/assembly-ee7-container.xml
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/assembly/assembly-servlet-container.xml
[JBPM-10042](https://issues.redhat.com/browse/JBPM-10042)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in …
> [JBPM-10042] Kie server webc controller is missing cdi-api dependency

- kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/assembly/assembly-ee7-container.xml
- kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/assembly/assembly-servlet-container.xml
[JBPM-10042](https://issues.redhat.com/browse/JBPM-10042)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in …
> [7.67.x] [JBPM-10042] Kie server webc controller is missing cdi-api dependency

- drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaFullTopicsTests.java
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6874
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …
> [DROOLS-6874] investigating flaky HACEP test

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/docs/ParameterSamples.java
**JIRA**: 
[RHPAM-4028](https://issues.redhat.com/browse/RHPAM-4028)
* follow up on https://github.com/kiegroup/droolsjbpm-integration/pull/2745
> [7.67.x][RHPAM-4028] Add CountDefinition to ServiceResponse

- kie-server-parent/kie-server-router/README.md
- kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AbstractAggregateHttpHandler.java
**JIRA**: [JBPM-10041](https://issues.redhat.com/browse/JBPM-10041)
<details>
<summary>
</summary> …
> [JBPM-10041] Router should disconnect also servers throwing SSLException or subclasses

- kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java
**[JBPM-10057](https://issues.redhat.com/browse/JBPM-10057)**: Flaky test fix - org.kie.server.router.repository.FileRepositoryTest#testWatchServiceOnLatelyCreatedConfigFile 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on …
> [JBPM-10057] - Flaky test fix - org.kie.server.router.repository.FileRepositoryTest#testWatchServiceOnLatelyCreatedConfigFile

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
- kie-server-parent/kie-server-api/src/test/resources/supportedDateType.json
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/bootstrap/input-form-group-template.html
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/js/kieserver-ui.js
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/patternfly/input-form-group-template.html
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/BootstrapFormRendererTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/FormRendererTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/date-type-check-form.json
[https://issues.redhat.com/browse/JBPM-10079](https://issues.redhat.com/browse/JBPM-10079)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
> JBPM-10079 ClassCastException when submitting a form in kie-server containing date process variable

- kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java
this exception is already captured SLF4j line below
**JIRA**:  https://issues.redhat.com/browse/DROOLS-6997
**referenced Pull Requests**: none.
<details>
<summary>
</summary> …
> DROOLS-6997 Move printStackTrace() to SLF4J logging

- kie-spring-boot/pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4413
* https://github.com/kiegroup/droolsjbpm-integration/pull/2794
* https://github.com/kiegroup/droolsjbpm-integration/pull/2795
* https://github.com/kiegroup/droolsjbpm-integration/pull/2796
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure …
> [7.67.x] RHPAM-4413 narayana-spring-boot-starter to 2.6.3

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
- kie-server-parent/kie-server-api/src/test/resources/supportedDateType.json
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/model/FormField.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/model/LayoutItem.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/bootstrap/input-form-group-template.html
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/js/kieserver-ui.js
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/patternfly/input-form-group-template.html
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/BootstrapFormRendererTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/FormRendererTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/date-form.json
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/date-type-check-form.json
- kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/dateTime-local-form.json
[https://issues.redhat.com/browse/JBPM-10058](https://issues.redhat.com/browse/JBPM-10058)
[https://issues.redhat.com/browse/JBPM-10077](https://issues.redhat.com/browse/JBPM-10077)
[https://issues.redhat.com/browse/JBPM-10077](https://issues.redhat.com/browse/JBPM-10077)
[https://issues.redhat.com/browse/JBPM-9942](https://issues.redhat.com/browse/JBPM-9942)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the …
> [7.67.x] Backport PRs for form rendering issues

- kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/invoker.properties
- kie-integration-test-coverage/kie-maven-plugin-no-execmodel-tests/kjar-with-instrumentation-no-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-no-execmodel/invoker.properties
- kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/kjar-with-separate-instrumentation-wrapper/src/test/resources/kjar-with-separate-instrumentation/invoker.properties
- kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/model-wrapper/src/test/resources/model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-default/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-yes-generate/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-default/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-yes-generate/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-13/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-2/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-3/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-4/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-5/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-6/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-exec-model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-no-exec-model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-exec-model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-no-exec-model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-exec-model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-no-exec-model/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/kie-maven-plugin-test-kjar-common/invoker.properties
- kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/kie-maven-plugin-test-kjar-parent/invoker.properties
the `org.w3c.dom.ElementTraversal` class is not present for jdk8, so we force org.w3c:dom dependency to be present.
As soon as we agree this is the right proposal, I will propagate it to `7.67.x` and `7.67.x-blue` branches
Built and tested either with JDK11 and 8.
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4455
* https://github.com/kiegroup/kie-wb-distributions/pull/1173
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023
* https://github.com/kiegroup/kie-wb-common/pull/3755
* https://github.com/kiegroup/droolsjbpm-integration/pull/2835
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and …
> RHPAM-4455 ssl.insecure to maven-invoker-plugin invoker.properties

- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/RuntimeDataServiceBaseTest.java
**JIRA**: 
[RHPAM-3893](https://issues.redhat.com/browse/RHPAM-3893)
Given a KIE-Server with the demo traffic-violations DMN example deployed, when running the following HTTP request:
```
http -a krisv:krisv http://localhost:18080/kie-server/services/rest/server/queries/containers/traffic-violation_1.0.0-SNAPSHOT/processes/definitions\?sort\=\&sortOrder\=true\&page\=0\&pageSize\=100
```
Returns a 500 Error instead of an empty collection as expected
> [RHPAM-3893] Return empty collection of processDefinitions

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/java/org.jbpm.data/CustomAbortWorkItemHandler.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/customWIH.bpmn
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java
**JIRA**: [JBPM-10071](https://issues.redhat.com/browse/JBPM-10071)
<details>
<summary>
</summary> …
> [JBPM-10071] test for WIH's abortWorkItem method should be called

- kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/EJBCacheInitializer.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java
Jira: https://issues.redhat.com/browse/JBPM-10127
> [JBPM-10127] Performance downgrade in cluster extension

- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/locator/LatestContainerLocator.java
**JIRA**: _JBPM-10152_ 
[link](https://issues.redhat.com/browse/JBPM-10152)
<details>
<summary>
Log statement is logging complete list instead of latest container in LatestContainerLocator
</summary>
</details>
> JBPM-10152: Corrected the debug log statement

- kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml
- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/pom.xml
- kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/pom.xml
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/pom.xml
- kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
**JIRA**:
[
RHPAM-4714](https://issues.redhat.com/browse/RHPAM-4714)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2298
* https://github.com/kiegroup/droolsjbpm-integration/pull/2961
<details>
<summary>
</summary> …
> [RHPAM-4714] wildfly-elytron as provided

- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/ElytronIdentityProvider.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/adapters/JMSSecurityAdapter.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapter.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapterTest.java
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4714
* https://github.com/kiegroup/droolsjbpm-integration/pull/2961
Changes performed https://github.com/kiegroup/droolsjbpm-integration/pull/2961 were not enough as kieServerMatrix tests are still failing while using `tomcat` server:
```
[INFO] [talledLocalContainer] SEVERE: Exception sending context initialized event to listener instance of class [org.kie.server.remote.rest.common.Bootstrap]
[INFO] [talledLocalContainer] java.lang.NoClassDefFoundError: org/wildfly/security/auth/server/SecurityDomain
[INFO] [talledLocalContainer] 	at org.kie.server.services.impl.security.ElytronIdentityProvider.available(ElytronIdentityProvider.java:33)
[INFO] …
```
> Ensure elytron is on the classpath before using it

- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/SLAOnProcess.bpmn2
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
- kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
**JIRA**: [JBPM-10185](https://issues.redhat.com/browse/JBPM-10185)
<details>
<summary>
</summary> …
> [JBPM-10185] Test for handling sla timer for processes

- kie-osgi/kie-karaf-features/pom.xml
- kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4781
This PR is for main(= 7.x)
for 7.67.x ->
for 7.67.x-blue ->
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case …
> [RHPAM-4781] KIE-OSGI: Inconsistent h2 version upgrade

- kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
**JIRA**: [JBPM-10214](https://issues.redhat.com/browse/JBPM-10214)
`explodedJarFolder` has a default value, i.e.,  it won't be null ever. As we want to keep the previous behavior, the best way IMHO without adding more configuration is to try the exploded option first and, if not present, try to autoscan the fat-jar.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
> [JBPM-10214] Fix regression for immutable KIE container with auto scan

- kie-server-parent/kie-server-tests/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7605
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …
> [DROOLS-7605] WebSphere kie-server-tests fails

- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
The current approach behaves like monothread.
> [FIX_KAFKA_EXECUTOR] fix executor service

- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
Related JIRA: https://issues.redhat.com/browse/RHPAM-4898
> [RHPAM-4898] Fix concurrency issue in KafkaServerRegistration

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/jms/JMSConstants.java
- kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java
- kie-server-parent/kie-server-common/src/test/java/org/kie/server/common/KeyStoreHelperUtilTest.java
- kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java
- kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/adapters/BrokerSecurityAdapter.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/adapters/JwtSecurityAdaptor.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/util/JwtService.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/util/JwtUserDetails.java
- kie-server-parent/kie-server-services/kie-server-services-common/src/main/resources/META-INF/services/org.kie.server.api.security.SecurityAdapter
- kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/util/JwtUtilTest.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/security/BrokerUserGroupAdapter.java
- kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/META-INF/services/org.jbpm.services.task.identity.adapter.UserGroupAdapter
- kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
issue: https://github.com/apache/incubator-kie-issues/issues/994
depends on: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2440
> [incubator-kie-issues-994] kafka auth feature with message header records

- kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/DecisionTasksIntegrationTest.java
Terminator value of the system is not accounted in some decision tests. Added.
> [FIX_TERMINATOR_TEST_VARIABLES] terminator is not counted in some decision tests

- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
- kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/json/JSONMarshallerExtensionTest.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/objects/FreeFormItemType.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/objects/ItemsType.java
- kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/objects/StandardItemType.java
- kie-server-parent/kie-server-api/src/test/resources/poly_payload.json
The performance problem was related to the polymorphic feature of jackson. it computes the subtypes of a given types.
Before the patch we were saying that all classes contained in the kjar/project where subtypes of every class causing a huge impact in performance
That performance problem was causing another problem, it was overwriting the proper names for types
Every class when you are serializing you have the full qualified name and the name used for serialized and deserialized
So before the patch we were overwriting that information making this feature not working properly
Now because the subtypes are being computed properly we are not overwriting the names therefore now the name is being taken from the annotation like it should be
> [FIX] custom fix when xml adapter has names

- kie-camel/pom.xml
- kie-osgi/kie-karaf-features/pom.xml
Related PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2486
> [7.67.x-blue] Update camel to 2.25.4.
