kie-spring/src/test/java/org/kie/spring/tests/AbstractKieSpringDynamicModuleTest.java
kie-spring/src/test/java/org/kie/spring/tests/KieSpringImportReleaseIdTest.java
kie-spring/src/test/java/org/kie/spring/tests/KieSpringScannerTest.java
kie-spring/src/test/resources/org/kie/spring/kie-import-releaseid.xml

Test Refactoring and New Test for import by releaseId.
The actual test for kie-spring import by releaseId was never implemented. This commit adds the test.

Kie-spring tests: Test Refactoring and New Test for kie-spring import by releaseId

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java

Removed commented tests: those tests are implemented in KieServerDroolsIntegrationTest.
Removed scanner tests from KieServerDroolsIntegrationTest as they are implemented in KieServerIntegrationTest.
Closed URLClassLoader, removed manual marshalling from testCallContainerMarshallCommands.

DROOLS-733 - Test cleanup: removed commented or duplicated tests, small tweaks.

---

drools-osgi/drools-osgi-integration/pom.xml
drools-osgi/drools-osgi-integration/src/main/java/org/drools/osgi/compiler/OsgiKieModule.java
drools-osgi/drools-osgi-integration/src/main/java/org/drools/osgi/spring/OsgiKModuleBeanFactoryPostProcessor.java
drools-osgi/drools-osgi-integration/src/main/test/org/drools/osgi/compiler/OsgiKieModuleTest.java

* few unit tests added as well to cover parsing of the known
bundle URLs

[DROOLS-905] add support for Equinox + blueprint bundles

---

kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/RemoteConfiguration.java
kie-remote/kie-remote-client/src/test/java/org/kie/services/client/api/command/RemoteCommandObjectTest.java

https://issues.jboss.org/browse/JBPM-4678

JBPM-4678 - Constructor of RemoteConfiguration does not process Url

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerCommandServiceImpl.java
kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieContainerCommandServiceImpl.java
kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/RulesExecutionService.java

@etirelli could you have a look - it's only refactoring to allow better extensibility as described in the [articles](http://mswiderski.blogspot.com/2015/12/extending-kie-server-capabilities.html) illustrating how kie server can be extended on various levels

DROOLS-994 - Improve extensibility of drools extension in KIE Server

---

kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/DeploymentResourceImpl.java

BZ-1306309 - REST endpoints do not work on WebLogic 12c R2

---

drools-osgi/drools-osgi-integration/src/main/java/org/drools/osgi/spring/OsgiKModuleBeanFactoryPostProcessor.java
kie-spring/src/main/java/org/kie/spring/KModuleBeanFactoryPostProcessor.java
kie-spring/src/main/java/org/kie/spring/KModuleSpringMarshaller.java
kie-spring/src/main/java/org/kie/spring/annotations/KModuleAnnotationPostProcessor.java

Depends on https://github.com/droolsjbpm/drools/pull/680
@mariofusco please take a look

[6.4.x] [DROOLS-1074] add support for kie-spring as EAP module + related refactoring

---

drools-osgi/drools-osgi-integration/src/main/java/org/drools/osgi/spring/OsgiKModuleBeanFactoryPostProcessor.java
kie-spring/src/main/java/org/kie/spring/KModuleBeanFactoryPostProcessor.java
kie-spring/src/main/java/org/kie/spring/KModuleSpringMarshaller.java
kie-spring/src/main/java/org/kie/spring/annotations/KModuleAnnotationPostProcessor.java

Same change already on 6.4.x (https://github.com/droolsjbpm/droolsjbpm-integration/pull/350)

[DROOLS-1074] add support for kie-spring as EAP module + related refactoring

---

drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintProcessDependencyKarafIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/resources/blueprint_process_dep/sampleProcess.bpmn2
drools-osgi/drools-karaf-itests/src/test/resources/blueprint_process_dep/sampleRule.drl
drools-osgi/drools-karaf-itests/src/test/resources/org/drools/karaf/itest/blueprint/kie-beans-blueprint-process-dep.xml

Separated reproducer for the above BZ from https://github.com/droolsjbpm/droolsjbpm-integration/pull/315.

BZ 1312285: add reproducer

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java

Minor improvements included.
@psiroky FYI

PLANNER-560 - ignoring test until it gets fixed

---

kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContext.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContextFilter.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContextManager.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/JaxbContextResolver.java
kie-remote/kie-remote-services/src/test/java/org/kie/remote/services/rest/jaxb/JaxbContextResolverTest.java

For 6.4.x. 
@mswiderski Could you review this? 
This is *not* a blocker: so, please merge this _after_ the release this week.

6.4.x: BZ-1310739 - Performance degradation with REST API on WebSphere: JAXB Context CDI use

---

drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-core.xml

(cherry picked from commit ca2c61944ed338dc8194e73ca3f5353979dc5811)

BZ-1321790 Add OSGi features support for optaplanner-persistence-xstream

---

kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContext.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContextFilter.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/DynamicJaxbContextManager.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/rest/jaxb/JaxbContextResolver.java
kie-remote/kie-remote-services/src/test/java/org/kie/remote/services/rest/jaxb/JaxbContextResolverTest.java

For 6.3.x. 
@mswiderski Could you review this? 
I'm pretty sure this should be added to the 6.3.x branch -- however, I'm not sure _when_ this should be merged.  I'll add a comment once I figure it out.

6.3.x: BZ-1310739 - Performance degradation with REST API on WebSphere: JAXB Context CDI use

---

kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/api/RemoteRestRuntimeEngineBuilder.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/RemoteRestRuntimeEngineBuilderImpl.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/AbstractRemoteCommandObject.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/RemoteConfiguration.java
kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/RemoteClientBuilderTest.java

@psiroky Would you mind reviewing and merging? 
Thanks!
Based on 
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/356

BZ-1310510,1325945 - 6.2.0: Remote java API: cannot get tasks assigned to different users

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java

Uncommented accidentally commented tests.

DROOLS-1114 - uncomment tests

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java

6.4.x cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/430

[6.4.x] DROOLS-1114 - uncomment tests

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/util/RestUtils.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/test/java/org/kie/server/remote/rest/common/util/RestUtilsTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerDroolsIntegrationTest.java

6.4.x cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/432

DROOLS-1128 - Concurrent call fails when creating container

---

kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/api/RemoteRestRuntimeEngineBuilder.java
kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/JaxbCommandsResponse.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/RemoteRestRuntimeEngineBuilderImpl.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/AbstractRemoteCommandObject.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/InternalJmsCommandHelper.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/RemoteConfiguration.java
kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/RemoteTaskServiceClientImpl.java
kie-remote/kie-remote-client/src/test/java/org/kie/remote/client/ws/AuthenticatorTest.java
kie-remote/kie-remote-client/src/test/java/org/kie/remote/services/ws/command/CommandServiceTest.java
kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/RemoteClientBuilderTest.java
kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/http/AvailablePortFinder.java
kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/http/HeaderTest.java
kie-remote/kie-remote-client/src/test/java/org/kie/services/client/builder/http/RedirectTest.java

https://bugzilla.redhat.com/show_bug.cgi?id=1325986
Please only merge once there is a + on the bpms-rollup-1-6.3.x.

BZ-132598 - Support for custom authentication in RemoteRuntimeEngine configuration

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/ImageServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerKieServerBaseIntegrationTest.java

6.4.x cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/437
Changes just in tests.

[6.4.x] kie-server: test improvements and stabilization

---

kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/factorybeans/AbstractKieObjectsResolver.java
kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/namespace/AbstractElementParser.java
kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/namespace/KieBaseElementParser.java
kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/namespace/KieContainerElementParser.java
kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/namespace/KieSessionElementParser.java

* needed together with (already cherry-picked) 3e0a38c6b3867d78a

[6.3.x] [BZ-1310039] set blueprint bundleContext in all needed cases

---

kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/jaxb/ConversionUtil.java
kie-remote/kie-remote-jaxb-gen/src/main/java/org/kie/remote/jaxb/gen/util/JaxbUnknownAdapter.java
kie-remote/kie-remote-services/src/test/java/org/kie/remote/services/jaxb/JaxbRemoteServicesSerializationTest.java

https://issues.jboss.org/browse/JBPM-5114
This use case is particular important for migration ( @ibek, Could you add a comment about that? Thanks!) 
List of PRs: 
- https://github.com/droolsjbpm/drools/pull/782
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/469 (contains test)

JBPM-5114 - Nested Map<String, Map<String, Object>[]> objects can not be de/serialized correctly

---

kie-infinispan/drools-infinispan-persistence/src/main/java/org/drools/persistence/infinispan/processinstance/InfinispanWorkItemManager.java

@mswiderski 
related issue in here https://issues.jboss.org/browse/JBPM-5084.
I not sure it is reasonable, so please check it.
and i don't know how to create unit test for it , it just is draft code .

JBPM-5084: troubleshooting function for workitem

---

kie-remote/kie-remote-jaxb-gen/pom.xml

@mswiderski  Would you merge? 
This fixes the tests failing in `kie-remote`.

- fix for addition of ReTryWorkItemCommand

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/pom.xml

To make it configurable externally, also removing duplicities.

kie-server-tests: restructured storage property

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/rest/RestMalformedRequestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/rest/RestMalformedRequestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java

Also check for OK response status for DELETE requests - WebLogic returns 200 in case of no content in DELETE response.

kie-server-tests: release REST connection in finally block

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/rest/RestMalformedRequestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/rest/RestMalformedRequestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java

Also check for OK response status for DELETE requests - WebLogic returns 200 in case of no content in DELETE response.

[6.4.x] kie-server-tests: release REST connection in finally block

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/DocumentServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java

Added InitiatorProviderProcessListener and TaskCleanUpProcessEventListener event listeners

JBPM-5071 - Add default process event listeners from workbench

---

drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-core.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/AbstractPersistable.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudBalance.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudComputer.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudProcess.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java

This fixes jaxb on the execution server

PLANNER-565 Use optaplanner-persistence-jaxb

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudBalance.java

Promote optaplanner-persistence xstream and jaxb's score binders to public API

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/AbstractPersistable.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java

@ge0ffrey FYI, I put here that change I sent you in PR.

PLANNER-565 - Best solution test coverage extension

---

kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-servlet-container.xml

Excluding jboss-transaction-api from webc WAR file.

JBPM-5175: ClassCastException on Tomcat8

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessDefinitionIntegrationTest.java

Missing KieServerAssert reference.

kie-server-tests: fix compilation failure

---

kie-server-parent/kie-server-controller/kie-server-controller-test-war/src/main/assembly/assembly-servlet-container.xml
kie-server-parent/kie-server-controller/kie-server-controller-test-war/src/main/webc-resources/WEB-INF/web.xml

JBPM-5175: update Tomcat controller test war

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/ImageServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/client/KieServerControllerClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/client/KieServerMgmtControllerClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestOnlyBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/filter/Authenticator.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/rest/RestMalformedRequestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/rest/RestMalformedRequestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java

Deprecated Resteasy implementation replaced by JAX-RS 2.0 Client API.
Removed duplicit tests in RestMalformedRequestIntegrationTest.

kie-server-tests: refactored REST test implementation

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/BARuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

These test cover basic functionality for sorting on queries

JBPM-5166 - extends sorting tests

---

kie-spring/src/test/resources/jbpm/jta-emf/README.md

@lazarotti Also adding a note so that the name doesn't change again.. :)

JBPM-5216 - Adding note about resources

---

kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/internal/command/AbstractRemoteCommandObject.java
kie-remote/kie-remote-services/src/main/java/org/kie/remote/services/util/ExecuteCommandUtil.java

@mswiderski Just in case this part of the code remains in 7.x..

RHBPMS-397 - Allow insecure Remote task operations (not only limited to GetTask* commands)

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsQueueIntegrationTest.java

And refactored KieServerSynchronization to remove code duplication.

kie-server-tests: update synchronization for JmsQueueIntegrationTest

---

jbpm-simulation/src/main/java/org/jbpm/simulation/impl/events/AggregatedActivitySimulationEvent.java
jbpm-simulation/src/main/java/org/jbpm/simulation/impl/events/AggregatedEndEventSimulationEvent.java
jbpm-simulation/src/main/java/org/jbpm/simulation/impl/events/AggregatedProcessSimulationEvent.java
jbpm-simulation/src/main/java/org/jbpm/simulation/impl/events/HTAggregatedSimulationEvent.java
jbpm-simulation/src/main/resources/default.simulation.rules.drl
jbpm-simulation/src/main/resources/onevent.simulation.rules.drl

@psiroky @tsurdilo this should fix the problems on master with failed tests of jbpm simulation

[DROOLS-1175][DROOLS-1242] - jbpm simulation adjustments

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/usertask.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FailureOnContainerDisposeIntegrationTest.java

Moved FailureOnContainerDisposeIntegrationTest kie-server-tests-all to simulate the issue.
Provided fix suggestion.

JBPM-5253 - NPE when container dispose fails

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/client/KieServerControllerClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/controller/client/KieServerMgmtControllerClient.java

I'm trying to reuse this testing rest client in our selenium test suites to save some some clicking in UI.
While using these we came across 2 issues:
* custom credentials do not work
* marshaller is not initialized properly
@sutaakar Could you please review?

Fix initialization issues in KieServer*ControllerClient testing clients

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/usertask.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FailureOnContainerDisposeIntegrationTest.java

Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/570

[6.5.x] JBPM-5253 - NPE when container dispose fails

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerContainerCRUDIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerContainerListFilteringIntegrationTest.java

Tests scenarios from KieServerContainerCRUDIntegrationTest are included in the new test class.

JBPM-5220 kie-server: add tests for filtred list of containers

---

drools-osgi/drools-karaf-features/src/main/filtered-resources/repository/features-core.xml
kie-remote/kie-remote-common/pom.xml
kie-remote/kie-remote-jaxb/pom.xml
kie-remote/kie-remote-ws/kie-remote-ws-common/pom.xml
kie-remote/kie-remote-ws/kie-remote-ws-impl/pom.xml
kie-remote/kie-remote-ws/kie-remote-ws-wsdl/pom.xml

* while the "wrap" hack works on Karaf, it does not work
on Equinox. In order to support Equinox we need all deps
properly OSGified.
@mrietveld could you please take a look at this?

[JBPM-5250] OSGify all needed kie-remote modules

---

kie-remote/kie-remote-client/src/test/java/org/kie/services/client/serialization/JaxbRemoteSerializationTest.java
kie-remote/kie-remote-common/src/main/java/org/kie/remote/common/rest/KieRemoteHttpRequest.java

GUVNOR-2297,RHBPMS-4118 - 'SAXParseException; Premature end of file' due to incorrect encoding

---

kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/TaskServiceClientCommandObject.java

PR Set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/160
- https://github.com/droolsjbpm/jbpm/pull/560
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/605

[6.4.x] RHBPMS-4184,JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

---

kie-remote/kie-remote-client/src/main/java/org/kie/services/client/api/command/TaskServiceClientCommandObject.java

PR Set: 
- https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/160
- https://github.com/droolsjbpm/jbpm/pull/560
- https://github.com/droolsjbpm/droolsjbpm-integration/pull/605

[6.5.x] RHBPMS-4184,JBPM-5277 - getTasksAssignedAsPotentialOwner doesn't allow groups searching, only actorid

---

kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/factorybeans/KieImportSessionResolver.java
kie-aries-blueprint/src/main/java/org/kie/aries/blueprint/factorybeans/KieSessionResolver.java
kie-remote/kie-remote-client/src/main/java/org/kie/remote/client/internal/command/KieSessionClientCommandObject.java

alignments for droolsjbpm-integration of Kie API change

[DROOLS-1267] allow to submit atomic actions during a fireUntilHalt

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/pom.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/AbstractCaseResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/test/java/org/kie/server/remote/rest/casemgmt/CaseQueryResourceTest.java

Moved common invokeCaseOperation to abstract class.

JBPM-4650: Fix NPE when listing case definitions and instances

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java

cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/612

[6.5.x] kie-server-tests: improve findProcessInstances tests

---

drools-osgi/drools-karaf-features/pom.xml

This PR do the same job as https://github.com/droolsjbpm/droolsjbpm-integration/pull/593
But target to master branch. Please have a look, Thanks!

Add exclusion for springwork.osgi since the transitive deps are invalid

---

kie-server-parent/kie-server-tests/pom.xml

Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/634

kie-server-tests: allow external configuration of excluded groups

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerInstanceImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java

Same as on 6.5.x branch (https://github.com/droolsjbpm/droolsjbpm-integration/pull/597)

[RHBRMS-2546] Kie Server - Creating container has releaseId null

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/KieServicesClientImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/category/Transactional.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerAssert.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/jms/ContainerJmsResponseHandlerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/jms/DroolsJmsResponseHandlerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsTransactionsIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/KieServerXAConnectionFactory.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

This is cherry-picked commit f00bd0e31ce2ef1aa14b6964872ef94b65711058 from #598 (6.5.x)

JBPM-5228 - Add more tests for 'fire and forget' feature

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/StatefulSessionUsageIntegrationTest.java

@mariofusco @etirelli could you please have a look
depends on https://github.com/droolsjbpm/drools/pull/905

DROOLS-1270 - support fact handle operations for REST APIs on kie server

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/StatefulSessionUsageIntegrationTest.java

(cherry picked from commit f7889b07a5e861e382093e6485e30c5b330c622e)
depends on https://github.com/droolsjbpm/drools/pull/906

[6.5.x] DROOLS-1270 - support fact handle operations for REST APIs on kie server

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/AbstractCaseResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/Messages.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-insurance/src/main/resources/org/kie/server/testing/CarInsuranceClaimCase.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-insurance/src/main/resources/org/kie/server/testing/UserTaskCase.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-insurance/src/main/resources/org/kie/server/testing/insurance-rules.drl
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseServiceIntegrationTest.java

depends on https://github.com/droolsjbpm/jbpm/pull/629
@sutaakar as we talked about it the other day :) can you take a look?

JBPM-4646 - Case management - support for reopening the case

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java

@psiroky could you please double check as this most likely will be a blocker for 6.5

[6.5.x] don't fail on kie scanner when not set and requested to stop

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ExecutorResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ExecutorServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java

@mswiderski can you take a look please?  thanks!

JBPM-5266: Jobs: Type validation fails during new job creation

---

kie-osgi/kie-karaf-itests-kjar/pom.xml
kie-osgi/kie-karaf-itests/pom.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/maven-settings.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/org/kie/karaf/itest/blueprint/kie-scanner-import-blueprint.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/test.properties
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/AbstractKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintScannerReimportIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJaxbIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJsonIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationXstreamIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/util/FileManager.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/util/KieScannerTestUtils.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/util/TimerUtils.java
kie-osgi/kie-karaf-itests/src/test/resources/org/kie/karaf/itest/blueprint/kie-scanner-reimport-blueprint.xml

[BPMSPL-299] Two test classes were implemented to verify new "import" element in kie blueprint. All new tests run in Karaf container. Test class KieBlueprintImportIntegrationTest checks that all assets from kjar are successfully loaded by kie scanner. Test class KieBlueprintScannerReimportIntegrationTest tests reimporting of kjar by kie scanner.

[BPMSPL-299] Karaf tests for import element in kie blueprint.

---

drools-osgi/drools-karaf-itests-kjar/pom.xml
drools-osgi/drools-karaf-itests/pom.xml
drools-osgi/drools-karaf-itests/src/test/filtered-resources/maven-settings.xml
drools-osgi/drools-karaf-itests/src/test/filtered-resources/test.properties
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/AbstractKarafIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/blueprint/KieBlueprintScannerReimportIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/KieServerClientKarafIntegrationJaxbIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/KieServerClientKarafIntegrationJsonIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/kieserver/KieServerClientKarafIntegrationXstreamIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/remoteclient/RemoteClientKarafIntegrationJaxbIntegrationTest.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/util/FileManager.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/util/KieScannerTestUtils.java
drools-osgi/drools-karaf-itests/src/test/java/org/drools/karaf/itest/util/TimerUtils.java
drools-osgi/drools-karaf-itests/src/test/resources/org/drools/karaf/itest/blueprint/kie-scanner-reimport-blueprint.xml

[6.5.x] [BPMSPL-299] Two test classes were implemented to verify new "import" element in kie blueprint. All new tests run in Karaf container. Test class KieBlueprintImportIntegrationTest checks that all assets from kjar are successfully loaded by kie scanner. Test class KieBlueprintScannerReimportIntegrationTest tests reimporting of kjar by kie scanner.

[6.5.x] [BPMSPL-299] Karaf tests for import element in kie blueprint.

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java

Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/700

kie-server-tests: add solver dispose synchronization

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/img/ImageReference.java

@krisv as we discussed to improve the searching mechanism for svg files.

improved searching for svg file within kjar for displaying process image

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/BytecodeInjectReactive.java

Aligning with droolsjbpm/drools#996 .

DROOLS-1302 OOPath ReactiveList remove cases

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/KieServer.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/KieServerRegistry.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/api/Policy.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerRegistryImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/controller/DefaultRestControllerImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/policy/KeepLatestContainerOnlyPolicy.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/policy/PolicyManager.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/resources/META-INF/services/org.kie.server.services.api.Policy
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/KieServerPolicyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/KieServerPolicyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceMigrationIntegrationTest.java

@etirelli whenever you have a chance, please have a look. it should support automatic dispose of containers and much more by additional policies implementations which are completely pluggable. 
Will do an article about the concepts and features next week.
@sutaakar the tests might be unstable as they are difficult to properly assert and the policy evaluation is time based... if you have any ideas on how to improve them I'd be more than happy to apply :)

JBPM-5388 - Policy support in KIE Server

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseInstance.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/test/java/org/kie/server/remote/rest/casemgmt/CaseQueryResourceTest.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseServiceIntegrationTest.java

depends on https://github.com/droolsjbpm/jbpm/pull/664
@sutaakar this replaces #713 with fixes and cleanup of todos according to expected behavior

JBPM-4646 - Case management - extended test coverage and fixes

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/BARuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

Some tests failed on Oracle RAC database due id ordering from db.

kie-server-tests: test improvement for Oracle RAC

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/per-process-instance-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/per-process-instance-project/src/main/resources/WorkDefinitions.wid
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/per-process-instance-project/src/main/resources/email-workitem.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/PerProcessInstanceWorkItemIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/ImageServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/PerProcessInstanceWorkItemRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/RestJbpmBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/cases/CaseServiceRestOnlyIntegrationTest.java

Contains partial fix - fixed getWorkItem() functionality.
Minor refactoring to avoid duplicities.

JBPM-5403: work item for per process instance test coverage

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/ruleflow-group/src/main/resources/org/kie/server/testing/ruleflow/simple-ruleflow.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/jms/DroolsJmsResponseHandlerIntegrationTest.java

@mswiderski We talked about this case some time ago on IRC

kie-server-tests: response handler test stabilization

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/jms/DroolsJmsResponseHandlerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/jms/JmsResponseHandlerIntegrationTest.java

So response handlers are cleaned up in one place.

kie-server-tests: reset response handlers after test run

---

droolsjbpm-integration-examples/src/main/java/org/drools/examples/broker/Broker.java

@tarilabs here is configuration change for the broker example. could you give it a try when you have a sec?

broker example session configuration to use rule node as wait state

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

depends on https://github.com/droolsjbpm/jbpm/pull/689
@krisv and here is its remote counterpart

JBPM-4646 - Case management - get tasks for cases as stakeholder

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/type/JaxbMap.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/type/JaxbMapTest.java

This fixes problems described in [JBPM-5435](https://issues.jboss.org/browse/JBPM-5435).

JBPM-5435: JaxbMap modifies collection passed as constructor argument

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/BytecodeInjectReactive.java
kie-maven-plugin/src/test/java/org/drools/compiler/xpath/tobeinstrumented/XPathTest.java
kie-maven-plugin/src/test/java/org/drools/compiler/xpath/tobeinstrumented/model/PojoWithCollections.java
kie-maven-plugin/src/test/java/org/drools/compiler/xpath/tobeinstrumented/model/TMDirectory.java
kie-maven-plugin/src/test/java/org/drools/compiler/xpath/tobeinstrumented/model/TMFile.java
kie-maven-plugin/src/test/java/org/drools/compiler/xpath/tobeinstrumented/model/TMFileSet.java
kie-maven-plugin/src/test/java/org/kie/maven/plugin/InjectReactiveIntegrationTest.java
kie-maven-plugin/src/test/projects/kjar-4-bytecode-inject/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/FieldIsNotListInterface.java
kie-maven-plugin/src/test/projects/kjar-4-bytecode-inject/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/FieldsSomeInterfacesSomeNot.java
kie-maven-plugin/src/test/projects/kjar-4-bytecode-inject/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/PojoWithCollections.java
kie-maven-plugin/src/test/projects/kjar-4-bytecode-inject/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/TMDirectory.java
kie-maven-plugin/src/test/projects/kjar-4-bytecode-inject/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/TMFile.java
kie-maven-plugin/src/test/projects/kjar-4-bytecode-inject/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/TMFileSet.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/TMDirectory.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/TMFile.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/org/drools/compiler/xpath/tobeinstrumented/model/TMFileSet.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/to/instrument/TMDirectory.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/to/instrument/TMFile.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/to/instrument/TMFileSet.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/to/not/instrument/TMDirectory.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/to/not/instrument/TMFile.java
kie-maven-plugin/src/test/projects/kjar-5-bytecode-inject-selected/src/main/java/to/not/instrument/TMFileSet.java

Depends on droolsjbpm/drools#1033 .

Align reactivity support for Collection interfaces.

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/ImageServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/RestJbpmBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/KieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/RestJbpmBaseIntegrationTest.java

Cherrypick of https://github.com/droolsjbpm/droolsjbpm-integration/pull/763

[6.5.x] kie-server-tests: Abort processes after test cases

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java

@mswiderski when I tried to use bigger poll-interval (10000) then this test pass

RHBPMS-4435 - Add test to reproduce issue

---

kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/ScoresMarshallingTest.java

Showing issues described in referenced JIRA.

PLANNER-565 - Marshall best solution score test

---

kie-server-parent/kie-server-tests/pom.xml

Allowed by Cargo version upgrade.
- Cleaner user configuration
- Email support for WildFly
- No need for controller client for WildFly
- Fixed context config for WebLogic

kie-server-tests: Cargo improvements

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AbstractAggregateHttpHandler.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterRestIntegrationTest.java

Response is aggregated just in case there is any response returned.

JBPM-5605: Immediately return 404 if no Kie server response

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/CaseAdminServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/impl/CaseAdminServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/helper/CaseServicesClientBuilder.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseAdminResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseRestApplicationComponentsService.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/test/java/org/kie/server/remote/rest/casemgmt/CaseQueryResourceTest.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/resources/case-authorization.properties
kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/classes/case-authorization.properties
kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/WEB-INF/classes/case-authorization.properties

depends on https://github.com/droolsjbpm/jbpm/pull/734

JBPM-4646 - Case management - case instance security

---

kie-spring/src/main/java/org/kie/spring/factorybeans/RuntimeManagerFactoryBean.java
kie-spring/src/main/java/org/kie/spring/manager/SpringRuntimeManagerFactoryImpl.java
kie-spring/src/test/java/org/kie/spring/jbpm/DisallowedSharedTaskServiceTest.java
kie-spring/src/test/java/org/kie/spring/jbpm/tools/IntegrationSpringBase.java
kie-spring/src/test/resources/jbpm/no-initial-context/runtime-env-emf.xml
kie-spring/src/test/resources/jbpm/shared-taskservice/jta-emf-per-process-instance.xml
kie-spring/src/test/resources/jbpm/shared-taskservice/jta-emf-per-request.xml

(cherry picked from commit 649142980081c2c0a63a07fa98937aac25fca004)

[6.5.x] RHBPMS-4098 - Process Instance Halting Mid Process

---

kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee6-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml

@sutaakar here it is as we discussed...

exclude jax-rs-api from ee6 ad ee7 assemblies of kie server

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml
kie-server-parent/kie-server-api/pom.xml
kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/CommandScript.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ReleaseId.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/resources/logback-test.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/pom.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/KieServerApplication.java
kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
kie-server-parent/kie-server-services/kie-server-services-common/src/test/resources/logback-test.xml
kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/weblogic.xml

depends on https://github.com/droolsjbpm/jbpm/pull/736

DROOLS-1222 - Upgrade kie-server from jackson 1 to jackson 2

---

drools-android/src/main/java/org/drools/android/robolectric/ShadowMultiDexClassLoader.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/events/ServerTemplateUpdated.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/JbpmRestApplicationComponentsService.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerRegistryImpl.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/RemoteKieFormsProvider.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
pom.xml

Please wait for PR https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/382 to be merged first.

Introduce findbugs to integration repository

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/LoadBalancerClientTest.java

@sutaakar do you mind to take a quick look?

JBPM-5698 - Starting process with new Kie server node

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/SpecManagementServiceImpl.java
kie-server-parent/kie-server-router/kie-server-router-client/src/main/java/org/kie/server/router/client/KieServerRouterEventListener.java
kie-server-parent/kie-server-router/kie-server-router-client/src/test/java/org/kie/server/router/client/KieServerRouterEventListenerTest.java

JBPM-5693 - Starting multiple Kie server nodes simultaneously, 	JBPM-5677 - Kie server router URL format

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/UIServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/util/RestUtils.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/pom.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/FormResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/JBPMUIKieServerExtension.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FormServiceIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

adding the fix to kie-server too!
This PR should me merged with:
- https://github.com/droolsjbpm/jbpm/pull/756
- https://github.com/droolsjbpm/jbpm-wb/pull/633

RHBPMS-4576: A user can display tasks for which he is not Potential Owner or Bussines Admin

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/usertask-failing.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

depends on https://github.com/droolsjbpm/jbpm/pull/752

JBPM-5704 - NPE when completing already completed user task

---

kie-eap-integration/kie-eap-distribution/pom.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/apache/maven/assembly-component.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/apache/maven/module.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/apache/maven/wagon/module.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/eclipse/sisu/assembly-component.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/eclipse/sisu/module.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
kie-server-parent/kie-server-wars/kie-server/pom.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee6-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-servlet-container.xml
pom.xml

Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/401

[DROOLS-1452] fixes after Maven 3.2.5 -> 3.3.9 upgrade

---

kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManagerFactory.java
kie-spring/src/test/java/org/kie/spring/jbpm/AbstractJbpmSpringParameterizedTest.java
kie-spring/src/test/java/org/kie/spring/jbpm/KieSpringProcessInstanceMigrationServiceImplTest.java
kie-spring/src/test/java/org/kie/spring/jbpm/KieSpringTransactionManagerFactoryTest.java
kie-spring/src/test/resources/jbpm/configuration-template/assets.xml
kie-spring/src/test/resources/jbpm/configuration-template/jta-em-spring.xml
kie-spring/src/test/resources/jbpm/configuration-template/jta-emf-spring.xml
kie-spring/src/test/resources/jbpm/configuration-template/local-emf-spring.xml
kie-spring/src/test/resources/jbpm/jta-em/singleton.xml
kie-spring/src/test/resources/jbpm/jta-emf/singleton.xml
kie-spring/src/test/resources/jbpm/processes/AddTaskAfterActive-v1.bpmn2
kie-spring/src/test/resources/jbpm/processes/AddTaskAfterActive-v2.bpmn2

@mswiderski thanks for all your help on this!

RHBPMS-4636 - MigrationManager API throws NPE when used in Kie-Spring  environment

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/JbpmRestApplicationComponentsService.java
kie-server-parent/kie-server-router/kie-server-router-client/src/main/java/org/kie/server/router/client/KieServerRouterEventListener.java
kie-server-parent/kie-server-router/kie-server-router-client/src/test/java/org/kie/server/router/client/KieServerRouterEventListenerRetryTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationListener.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ContainerInfo.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/DefaultContainerResolver.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/DefaultRestrictionPolicy.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/KieServerProxyClient.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigurationMarshaller.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/spi/ConfigRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/spi/ContainerResolver.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/spi/RestrictionPolicy.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/locator/LatestContainerLocator.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/DefinitionServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/jpa/PersistenceUnitInfoLoader.java

@sutaakar do you mind taking a quick look whenever you have some time?

JBPM-5730 - Make KIE Server router extendable

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java

@etirelli can you review+merge, please?

Fix potential NPE when stubbing DMN nodes inside result back to client

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/policy/PolicyManager.java

@sutaakar @tsurdilo do you mind guys to take a look?

JBPM-5838 - Resource leak when using Kie server policies on Tomcat

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java

@tsurdilo same here for master branch...

RHBRMS-2775 - Allow Session type configuration in KieServerMDB

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java

On RAC databases this test can fail as database distribute IDs among nodes in batches making ID order unreliable for tests.

kie-server-tests: Improve process instance correlation key test

---

kie-maven-plugin/pom.xml

@mariofusco or @tarilabs could you please review?

Upgrade takari-lifecycle-plugin from 1.11.11.jbossorg-1 to 1.12.4

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseFileDataItem.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseFileDataItemList.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/test/java/org/kie/server/remote/rest/casemgmt/CaseQueryResourceTest.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

@tsurdilo here is the kie server part of https://github.com/kiegroup/jbpm/pull/807

JBPM-4646 - case management - case file data audit trail

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseFileDataItem.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseFileDataItemList.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/test/java/org/kie/server/remote/rest/casemgmt/CaseQueryResourceTest.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/812

[7.0.x] JBPM-4646 - case management - case file data audit trail

---

kie-server-parent/kie-server-controller/kie-server-controller-rest/src/main/java/org/kie/server/controller/rest/ControllerUtils.java

To fix controller issues on WebSphere 9.
Inspired by https://github.com/kiegroup/droolsjbpm-integration/commit/39936d07782a9283dc63aaabaca644c59cec5a3b .

JBPM-5860: Check Content-Type value of controller request

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/admin/ExecutionErrorInstance.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/admin/ExecutionErrorInstanceList.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/QueryServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/ProcessAdminServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/UserTaskAdminServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/impl/ProcessAdminServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/impl/UserTaskAdminServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/ProcessAdminResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/UserTaskAdminResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/UserTaskAdminServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/signal-process.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/src/main/resources/signal-process.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/802

JBPM-5851 - Technical Error Events

---

kie-server-parent/kie-server-tests/pom.xml

This is reproducer for [JBPM-5879](https://issues.jboss.org/browse/JBPM-5879)
Run "mvn clean install -Ptomcat8" from kie-server-tests

[reproducer, do not merge] JBPM-5879 Reproducer

---

droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml

@krisv here it is
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/434

Added kie server router to bpms distribution zip

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json

Hi, @mswiderski,
same as #941, but for 7.0.x.
Marian

[7.0.x] Change revapi-config.json comment to be more general

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/img/ImageReference.java

@krisv @sutaakar backport to 7.0.x

[7.0.x] JBPM-5969 - Process image resolving on Windows

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/img/ImageReference.java

@sutaakar could you please review and in case you have option to give it a try on windows?

JBPM-5969 - Process image resolving on Windows

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/FormResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/RemoteFormModellerFormProvider.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/org/kie/server/subform/HRInterviewSubform-taskform.form
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/org/kie/server/subform/PurchaseHeader.form
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/org/kie/server/subform/PurchaseLine.form
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/org/kie/server/subform/hiringSubform-taskform.form
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/org/kie/server/subform/hiringSubform.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FormServiceIntegrationTest.java

@tsurdilo could you please have a look?

JBPM-5973 - Subforms are not rendered when provided by KIE Server

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java

Some tests will fail due [JBPM-5930](https://issues.jboss.org/browse/JBPM-5930) and  [JBPM-5931](https://issues.jboss.org/browse/JBPM-5931)

kie-server-tests: Extend Mgmt Controller tests

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java

@tsurdilo could you please take a look?

[6.5.x] RHBRMS-2776 - Allow Session type configuration in KieServerMDB

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

Hi, @sutaakar,
here is the fix for Sybase DB in the query expression. I have tried it with our automation and it works now on all DBs correctly.
Marian

Use different query for Sybase when a boolean column is queried

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java

Can help customers to understand what the marshalling error is related to.

JBPM-5380: Specific error handling for query-definitions unmarshalling

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/MarshallingFormat.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/MarshallingFormatTest.java

[7.0.x] RHBPMS-4592 Fix content-type from http header (#943)

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

Tests scenarios for trigger ad-hoc task in kie server. 
testTriggerTaskIntoStage() is failing due [JBPM-6001](https://issues.jboss.org/browse/JBPM-6001)

kie-server-tests: add tests for trigger ad-hoc task

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryInKjarIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/resources/query-definitions-kjar-duplicate-queries.json
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/resources/query-definitions-kjar-one-updated.json
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/resources/query-definitions-kjar-one.json
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/resources/query-definitions-kjar-two.json
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/resources/script-process.bpmn2

depends on https://github.com/kiegroup/drools/pull/1325
@sutaakar here is a copy of your PR to test it with the change in drools

JBPM-6018: Test coverage for queries in kjar

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

@tsurdilo  Not sure if this is overkill, but thought it might be safe to include an end to end test in part with https://github.com/kiegroup/jbpm/pull/885.

JBPM-6073: getComments method not returning desired page

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java

I have fixed empty assertions that @yurloc has discovered.

kie-server-tests: Fix empty assertions

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerKieServerBaseIntegrationTest.java

Replace assume with assert.
Based on https://github.com/kiegroup/droolsjbpm-integration/commit/8c31e3955c5d326445e18712e84321b99d106565#commitcomment-22589370

kie-server-tests: Assert list containers response

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

Test expects Kie server to returns HTTP status 500 when registering malformed query. Question is if Kie server can distinguish if error is caused by wrong input or some internal DB related fail. If so then it should return HTTP 400.

JBPM-6122: Invalid query test

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/ProcessServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/ProcessServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java

Fixed REST endpoints name.
Added missing tests scenarios.

JBPM-6120 - Invalid Kie Server REST endpoints for processes

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/893

JBPM-5976 - Provide auto acknowledge jobs for execution errors

---

kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/input-data-string-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/input-data-string-101/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/input-data-string-101/src/main/resources/input-data-string.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNInputDataStringIntegrationTest.java

Depends on kiegroup/drools#1336

DROOLS-1630 DMN support during incremental KieContainer upgrade

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-insurance/src/main/resources/org/kie/server/testing/UserTaskProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

I have added some of the missing CaseServicesClient tests identified by @sutaakar.

kie-server-tests: add missing CaseServicesClient tests

---

kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/kjar-with-separate-instrumentation-wrapper/pom.xml
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/model-wrapper/pom.xml
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/pom.xml
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/test-suite/pom.xml

I merged #976, an old PR. It was green, but I did not think to retest. Turns out it was not actually green any more. Lesson learned.

[DROOLS-1379] Update versions in POMs

---

kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/HttpStatusCodeException.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/ProcessInstanceSearchResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/TaskSearchResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/ProcessSearchServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm-search/src/test/java/org/kie/server/integrationtests/jbpm/search/TaskSearchServiceIntegrationTest.java

@domhanak tests are working now.

JBPM-6027: Advanced Search API shows error code 500 instead of 400

---

kie-server-parent/kie-server-remote/kie-server-client/pom.xml
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/BalancerStrategy.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/LoadBalancer.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/impl/AbstractBalancerStrategy.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/impl/RandomBalancerStrategy.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/impl/RoundRobinBalancerStrategy.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/LoadBalancerClientTest.java

@sutaakar here is your test case and the fix

JBPM-6230 - Kie server client load balancer test for URL with path

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/InMemoryFormProvider.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/services/jbpm/ui/form/FormFilterTest.java

@mswiderski @jsoltes could you take a look?

RHBPMS-4760: Task Subforms retrieved by Kie Server Rest API is missing subform fields

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/RemoteFormModellerFormProvider.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/services/jbpm/ui/form/FormFilterTest.java

@mswiderski @jsoltes could you take a look?

JBPM-6277: Task Subforms retrieved by Kie Server Rest API is missing subform fields

---

kie-eap-integration/kie-eap-tests/src/test/resources/jboss-deployment-structure-drools-and-jbpm-modules.xml
kie-maven-plugin/pom.xml
kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java

[DROOLS-1649] ServiceRegistry refactor
(cherry picked from commit 64b6f383655f2dd0d49a002c7ae388ce8b0bafcb)

[DROOLS-1649] ServiceRegistry refactor (#1068)

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

See https://issues.jboss.org/browse/JBPM-5457
Part of an ensemble:
- https://github.com/kiegroup/droolsjbpm-integration/pull/1066
- https://github.com/kiegroup/kie-wb-common/pull/999

JBPM-5457: Start and Stop container buttons change states even though they fail

---

kie-server-parent/kie-server-maven-plugin/README.md
kie-server-parent/kie-server-maven-plugin/pom.xml
kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/gateway/KieServerGateway.java
kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/DeployMojo.java
kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/DisposeMojo.java
kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/KieServerAbstactMojo.java
kie-server-parent/kie-server-maven-plugin/src/main/java/org/kie/server/maven/plugin/UpdateMojo.java
kie-server-parent/pom.xml

back port of @fax4ever kie-server-maven plugin to allow to deploy to unmanaged kie servers

[7.2.x] [DROOLS-1655] Maven plugin for unmanaged KIE Server deployments (#1063)

---

kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/jboss-deployment-structure.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1086

[7.2.x] Add CXF dependency to Wildfly/EAP deployable

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/CommandScript.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/AddProblemFactChangeCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/AddProblemFactChangesCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/GetSolverCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/GetSolverWithBestSolutionCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/GetSolversCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/IsEveryProblemFactChangeProcessedCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/commands/optaplanner/SolvePlanningProblemCommand.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/SolverServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/SolverServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/main/java/org/kie/server/remote/rest/optaplanner/SolverResource.java
kie-server-parent/kie-server-remote/revapi-config.json
kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/OptaplannerCommandServiceImpl.java
kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/SolverServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/AbstractPersistable.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/AddComputerProblemFactChange.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/CloudBalancingGenerator.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/java/org/kie/server/testing/DeleteComputerProblemFactChange.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/cloudbalance-realtime-planning-daemon-solver.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/cloudbalance-realtime-planning-solver.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/src/main/resources/cloudbalance-solver.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java

@ge0ffrey @yurloc A backport of the master PR https://github.com/kiegroup/droolsjbpm-integration/pull/1003

[7.2.x] PLANNER-815: Execution server: Support real-time planning

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/SolverServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/main/java/org/kie/server/remote/rest/optaplanner/SolverResource.java
kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/SolverServiceBase.java

* REST API resource rename
* SolverServiceBase - fail on terminating solver

PLANNER-815: Execution server: Support real-time planning

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

Cherry picked from https://github.com/kiegroup/droolsjbpm-integration/pull/1066
---
Part of an ensemble:
- https://github.com/kiegroup/kie-wb-common/pull/1036
- https://github.com/kiegroup/droolsjbpm-integration/pull/1100

[7.2.x] JBPM-5457: Start and Stop container buttons change states even though they fail

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/CustomExtensionClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/filter/Authenticator.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/helper/CustomExtensionClientBuilder.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/impl/CustomExtensionClientRest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/resources/META-INF/services/org.kie.server.client.helper.KieServicesClientBuilder
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/java/org/kie/server/integrationtests/extension/custom/CustomExtensionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/pom.xml
kie-server-parent/kie-server-tests/pom.xml

Extend custom extension test to use own client.

JBPM-6271: Kie server custom extension REST client

---

kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml

Caused issues when running controller with Kie server on same application server with enabled synchronization.

JBPM-6233: Remove unused dependencies from websocket modules

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
kie-server-parent/kie-server-tests/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1101

[7.2.x] JBPM-6233: Adjust web socket tests for WebLogic

---

kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1105

[7.2.x] JBPM-6233: Remove unused dependencies from websocket modules

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebsocketKieControllerStartupIntegrationTest.java

To be possible to run websocket tests against custom deployments.

JBPM-6233: Websocket test stabilization

---

kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/spec/ServerTemplate.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/SpecManagementServiceImpl.java

@sutaakar this should prevent from having race conditions on same collection

JBPM-6316 - Race condition when invoking Kie controller operations

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebsocketKieControllerStartupIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1112

[7.3.x] JBPM-6233: Websocket test stabilization

---

kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1105

[7.3.x] JBPM-6233: Remove unused dependencies from websocket modules

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/CustomExtensionClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/filter/Authenticator.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/helper/CustomExtensionClientBuilder.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/java/org/kie/server/client/impl/CustomExtensionClientRest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-client/src/main/resources/META-INF/services/org.kie.server.client.helper.KieServicesClientBuilder
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/java/org/kie/server/integrationtests/extension/custom/CustomExtensionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/pom.xml
kie-server-parent/kie-server-tests/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1102

[7.3.x] JBPM-6271: Kie server custom extension REST client

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java

Adding synchronization loops to stabilize tests for cases when controller is part of Workbench.
In that case controller actions interacting with Kie server are asynchronous.

Kie server controller test adjustments

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1123

[7.3.x] Kie server controller test adjustments

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerManagementIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1123

[6.5.x] Kie server controller test adjustments

---

droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml
kie-eap-integration/kie-eap-distribution/pom.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/jbpm/assembly-component.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/jbpm/module.xml
kie-osgi/kie-karaf-features/pom.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml

related prs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/510
https://github.com/kiegroup/jbpm/pull/945

JBPM-6310 - update to jbpm-workitems module

---

droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml
kie-eap-integration/kie-eap-distribution/pom.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/jbpm/assembly-component.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/jbpm/module.xml
kie-osgi/kie-karaf-features/pom.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml

[7.3.x] JBPM-6310 - update to jbpm-workitems module (#1129)

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/JBPMUIKieServerExtension.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/EmptyContainerIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1138

[7.3.x] JBPM-6353: Avoid NPE when creating container without processes

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/CustomXstreamMarshallerBuilder.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileRepository.java

(cherry picked from commit 8bc367b680283130c78cd7c6c587a196b0f2a827)

RHBRMS-2784 - XStream: DoS when unmarshalling void type (#1075)

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/broken-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ContainerUpdateIntegrationTest.java

@mswiderski What should happen if there is an error while container is updated - like in the test? Should it be reverted back to the original version?

JBPM-6351: Test and fix for update to broken container

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/CombinedUpdateIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/resources/Person.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1139

[7.3.x] DROOLS-1704: Test for multiple container updates

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/broken-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ContainerUpdateIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1137

[7.3.x] JBPM-6351: Test and fix for update to broken container

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AbstractAggregateHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/DefaultContainerResolver.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigurationMarshaller.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/spi/ContainerResolver.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java

@tsurdilo another one to take a look at ...
@sutaakar if you have a moment then take a look too, thanks

JBPM-6336 - KIE Server Router support for OpenShift with services

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AbstractAggregateHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/DefaultContainerResolver.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigurationMarshaller.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/spi/ContainerResolver.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java

@tsurdilo @sutaakar here is a bacport of #1145

[7.3.x] JBPM-6336 - KIE Server Router support for OpenShift with services

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerContainerDeployment.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerContainerVerifier.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/locator/LatestContainerLocator.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileInit.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileRepository.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerContainerDeploymentTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerContainerVerifierTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/storage/file/KieServerStateFileInitTest.java

GUVNOR-3025: OpenShift S2I (Source to Image) Integration
https://issues.jboss.org/browse/GUVNOR-3025

GUVNOR-3025: OpenShift S2I (Source to Image) Integration

---

kie-performance-kit/pom.xml

Hi,
this is a simple upgrade of PerfRepo client for jbpm-performance tests.
Thanks,
Marian

Update PerfRepo client to 1.7

---

kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1161

Fix failing Kie server test

---

kie-performance-kit/pom.xml
kie-performance-kit/src/main/java/org/kie/perf/Executor.java
kie-performance-kit/src/main/java/org/kie/perf/TestConfig.java
kie-performance-kit/src/main/java/org/kie/perf/metrics/PerfRepoReporter.java
kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java
kie-performance-kit/src/main/java/org/kie/perf/suite/LoadSuite.java
kie-performance-kit/src/main/java/org/kie/perf/suite/SoakSuite.java

Hi,
I have done a couple of enhancements to prepare kie-performance-kit for 7.x performance tests which are a part of kiegroup/kie-benchmarks#13.
Thanks,
Marian

[7.3.x] Enhance kie-performance-kit for 7.x tests

---

kie-performance-kit/pom.xml
kie-performance-kit/src/main/java/org/kie/perf/Executor.java
kie-performance-kit/src/main/java/org/kie/perf/TestConfig.java
kie-performance-kit/src/main/java/org/kie/perf/metrics/PerfRepoReporter.java
kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java
kie-performance-kit/src/main/java/org/kie/perf/suite/LoadSuite.java
kie-performance-kit/src/main/java/org/kie/perf/suite/SoakSuite.java

Hi,
same as #1157, but for master.
Thanks,
Marian

Enhance kie-performance-kit for 7.x tests

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/ProcessInstanceSearchResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/main/java/org/kie/server/remote/rest/jbpm/search/TaskSearchResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/QueryDataResource.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationListener.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouterConstants.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/spi/ConfigRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/JbpmKieServerExtensionTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/resources/default-query-definitions.json

@tsurdilo @sutaakar whenever you guys have a moment

JBPM-6373 - KIE Server improvements for cloud based deployments

---

kie-performance-kit/src/main/java/org/kie/perf/Executor.java
kie-performance-kit/src/main/java/org/kie/perf/TestConfig.java

Hi,
I have added a customizable warmUpTime property to kie-performance-kit. master and 7.x will come later.
Thanks,
Marian

[6.5.x] Add customizable warmUpTime

---

kie-performance-kit/src/main/java/org/kie/perf/Executor.java

Hi,
I have only raised logging level in kie-performance-kit, nothing special.
Thanks,
Marian

[6.5.x] kie-performance-kit: KPKLimit warmUp handling

---

kie-performance-kit/src/main/java/org/kie/perf/Executor.java

[7.3.x] kie-performance-kit: Raise warmUp logging level from debug to info

---

kie-performance-kit/src/main/java/org/kie/perf/Executor.java

kie-performance-kit: Raise warmUp logging level from debug to info 

---

kie-tomcat-integration/pom.xml

Fix groupId of kie-tomcat-integration

---

kie-performance-kit/src/main/java/org/kie/perf/Executor.java

[7.3.x] kie-performance-kit: KPKLimit warmUp handling

---

kie-performance-kit/src/main/java/org/kie/perf/Executor.java

kie-performance-kit: KPKLimit warmUp handling

---

kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/JMSConnection.java
kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java

* Created JMSConnection class to hold values for the Connection and Session
* Updated KieServerMDB
- Removed instance variables for Connection and Session
- Changed startConnectionAndSession method to return a JMSConnection
- Changed closeConnectionAndSession method to take a JMSConnection argument
- Changed onMessage method to use the JMSConnection returned from the startConnectionAndSession method
- Changed sendResponse method to take a Session argument

RHBPMS-4876_fix

---

kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/JMSConnection.java
kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java

* Created JMSConnection class to hold values for the Connection and Session
* Updated KieServerMDB
- Removed instance variables for Connection and Session
- Changed startConnectionAndSession method to return a JMSConnection
- Changed closeConnectionAndSession method to take a JMSConnection argument
- Changed onMessage method to use the JMSConnection returned from the startConnectionAndSession method
- Changed sendResponse method to take a Session argument

RHBPMS-4876_6.5.x_fix

---

kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/KieServerMDB.java

* Moved the creation of the JMSConnection to only occur if the interactionPattern is not FIRE_AND_FORGET
* Updated the finally statement for the onMessage method so that it won't attempt to close non-existent connections

RHBPMS-4876_fix2

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/UserTaskDefinition.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/DefinitionServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessDefinitionIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/978

JBPM-6406 - Display TaskName in Definition Stage of REST Call

---

kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java

[7.3.x] kie-performance-kit:Init scenario in concurrent load suite

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/CommandsMarshallingTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/kjar-JBPM-5019/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/kjar-JBPM-5019/src/main/java/org/kie/server/testing/Person.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/kjar-JBPM-5019/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/kjar-JBPM-5019/src/main/resources/kbase1/rules.drl
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/DisposeCommandTest.java

JBPM-5019 fix DisposeCommand serialization

---

kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java

[7.3.x] kie-performance-kit: Get annotation from scenario correctly

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1197

[7.3.x] Rewrite HOST header with target host for proxy requests

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1201

[7.3.x] Show warning in case server template file isn't found

---

kie-maven-plugin/pom.xml

Part of:
- https://github.com/kiegroup/drools/pull/1476
- https://github.com/kiegroup/drools-wb/pull/620
- https://github.com/kiegroup/optaplanner-wb/pull/222
- https://github.com/kiegroup/droolsjbpm-integration/pull/1193

PLANNER-865: Workbench: ScoreHolder support in GuidedDecisionTables causes error in server log

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ContainerFailureRecoveryIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

Needed for cases when local repo for Kie server is placed to some different location.

Use Kie server settings.xml for local artifact removal

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ContainerFailureRecoveryIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1204

[7.3.x] Use Kie server settings.xml for local artifact removal

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/DisposeCommandIntegrationTest.java

Rename the test to be executed as part of integration tests.

Rename Dispose command test

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/DisposeCommandIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1209

[7.3.x] Rename Dispose command test

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/DisposeCommandIntegrationTest.java

[6.5.x] Rename Dispose command test

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/router/client/KieServerRouterClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterUnavailabilityIntegrationTest.java

Simplifies Smart router testing for example in cloud tests.

Create client for Smart router operations

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/router/client/KieServerRouterClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterUnavailabilityIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1212

[7.3.x] Create client for Smart router operations

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java

Copy of https://github.com/kiegroup/droolsjbpm-integration/pull/1220
Adding package security to XStreamMarshaller to avoid com.thoughtworks.xstream.security.ForbiddenClassException when unmarshalling java objects comming from kie-server.
Added ability to configure a list of allowed packages using a comma separated list on the org.kie.server.xstream.enabled.packages system property. Like -Dorg.kie.server.xstream.enabled.packages=packageone.**,packagetwo.**
@jsoltes @mswiderski could you please review? (Sorry for all the format changes)

[7.3.x] JBPM-6456: Unable to open tasks that contain subforms.

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/DBExternalResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseServiceIntegrationTest.java
kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/classes/case-authorization.properties
kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/WEB-INF/classes/case-authorization.properties

depends on https://github.com/kiegroup/jbpm/pull/1017

JBPM-6466 - Provide case close operation with completion message, JBPM-6467 - Allow to fetch several case file data items in single call

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java

Classes created by Drools during the compilation of the .<>drl files and shared in the map to exports in the Maven compiler response

Added Drool's ProjectClassloader store in the shared map

---

kie-osgi/kie-osgi-integration/pom.xml

@psiroky @mariofusco @mbiarnes  could you please double check this is correct? It fixes the faling osgi tests on master

downgraded to 7.5.0-SNAPSHOT - osgi adjustment

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java

Exposed keys of the TypeMetaInfo map for the KieCompilationResponse

GUVNOR-3565

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseComment.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseFile.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseServiceIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/1033

JBPM-6498 - Case file and comments authorisation

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/KieServerTypePermission.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/CustomXstreamMarshallerBuilder.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/xstream/KieServerTypePermissionTest.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileRepository.java

depends on https://github.com/kiegroup/droolsjbpm-knowledge/pull/271
@ge0ffrey @mariofusco could you please have a look?

Use XStreamUtils.createTrustingXStream(..) helper

---

kie-eap-integration/kie-eap-distribution/pom.xml
kie-eap-integration/kie-eap-distribution/src/main/assembly/assembly.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/drools/module.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/kie/api/module.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/kie/ci/module.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/kie/soup/maven-integration/assembly-component.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/kie/soup/maven-integration/module.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/kie/soup/maven-support/assembly-component.xml
kie-eap-integration/kie-eap-distribution/src/main/filtered-resources/org/kie/soup/maven-support/module.xml
kie-maven-plugin/pom.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml
kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml

Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.

AF-593+: Move uberfire-maven-utils to kie-soup.

---

kie-maven-plugin/pom.xml

Do not merge. 
This should trigger CI

Testr removing kie-ci as it's hopefully not needed

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-dmn/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-search/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json

Please don't merge yet, will need to be merged together with https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/584

revapi: add missing justification

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNContextKS.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/DecisionMarshallingTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/DMNContextKSMarshallingTest.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/DMNServicesClientImpl.java
kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java

https://issues.jboss.org/browse/DROOLS-2073

[DROOLS-2073] Kie server API to evaluate multiple decisions by name/id

---

kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/storage/KieServerTemplateStorage.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/ControllerStorageFileWatcher.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorageTest.java
kie-server-parent/kie-server-controller/kie-server-controller-standalone-impl/src/main/java/org/kie/server/controller/service/StandaloneSpecManagementServiceImpl.java
kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/java/org/kie/server/controller/common/KieControllerServletListener.java

JBPM-6593 - Clustering support for Standalone controller

---

droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml
droolsjbpm-brms-distribution/pom.xml
droolsjbpm-brms-distribution/src/main/assembly/pre-bin.xml

Remove the drools-verifier from brms/bpm package

RHBRMS-1220 removing drools-verifier

---

kie-server-parent/kie-server-common/pom.xml
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebsocketKieServerControllerClient.java
kie-server-parent/kie-server-services/kie-server-services-common/pom.xml
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/controller/DefaultRestControllerImpl.java

Jira: https://issues.jboss.org/browse/RHBPMS-4312
After discussion with @mswiderski and @etirelli here https://github.com/kiegroup/droolsjbpm-integration/pull/1264 I am closing old PR and opening new one with correct branch name and fallback possibility to load a password from config

[RHBPMS-4312] Added password loading from a key store

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CarInsuranceClaimCaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/cases/CaseServiceRestOnlyIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/1064
just test alignments based on more strict validation of case role user task assignments

JBPM-6595 - Case Roles: User/group assignments fail when using Case File

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/NodeInstance.java

Just a minor fix for a typo which I noticed - NodeInstance Builder should have nodeInstance field, not processInstance. For a couple of seconds I was quite confused :)

NodeInstance builder should have nodeInstance field

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

Modify happy path test to verify that task is in proper status after
we called skip on that task via REST.
Same thing for master, ignore the empty line changes, looks like a github feature

RHBPMS-5041: Human Task should be in Obsolete status when we skip

---

kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/client/RestKieServicesClientProvider.java
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/main/java/org/kie/server/controller/rest/ControllerUtils.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerClient.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/controller/DefaultRestControllerImpl.java

Jira: https://issues.jboss.org/browse/RHBPMS-4312
This is enhancing previous PR: https://github.com/kiegroup/droolsjbpm-integration/pull/1273 with possibility to read multiple passwords

[RHBPMS-4312] Key store password reading made more general to support

---

kie-server-parent/kie-server-wars/kie-server/src/main/shared-ee6-ee7-resources/WEB-INF/weblogic.xml

@sutaakar here is the change we talked about

JBPM-6656 - NoSuchMethodError when starting Kie server on WebLogic

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskInstance.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/QueryServicesClient.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

Allow to search tasks assigned by potential owner through

JBPM-6670 - Allow to search tasks assigned by potential owner through

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/DocumentServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CarInsuranceClaimCaseIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/1095

JBPM-6681 - Support for lazy loaded variables

---

kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/1103

JBPM-6710 - Create comment operation should directly return comment id

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TaskSearchServiceIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1322

[7.5.x] Trim task instance description in TaskSearchServiceIntegrationTest

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorageTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1308

[7.5.x] RHBRMS-3044: Store template map when template file doesn't exist

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/main/java/org/kie/server/remote/rest/drools/CommandResource.java
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml

RHDM-232 - ClassNotFoundException when invoking image related operation, RHDM-226 - Print request payload into the log

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/DMNServicesClientImpl.java
kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNInputDataStringIntegrationTest.java

/cc @baldimir @etirelli @kurobako

DROOLS-2234 DMN JSON payload with decision-name or decision-id null causes NPE

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerStartupIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1333

[7.5.x] Add wildfly10 integration test profile

---

kie-server-parent/kie-server-controller/kie-server-controller-client/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket-common/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-websocket/pom.xml

JBPM-6243 - Update WebSocket javax API version

---

jbpm-process-svg/src/main/java/org/jbpm/process/svg/SVGImageProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/NodeSummary.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/SetBorderColorTransformation.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/main/java/org/kie/server/remote/rest/drools/CommandResource.java

depends on https://github.com/kiegroup/jbpm/pull/1117

[6.5.x] RHBPMS-5103 - Reusable subprocess node doesn't get highlighted in red, RHBRMS-3050 - Print request payload into the log

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerNotificationIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1364

[7.5.x] Stabilize WebSocketKieControllerNotificationIntegrationTest

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNContextKS.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java

https://issues.jboss.org/browse/DROOLS-2115

[DROOLS-2115] Remove unnecessary array-list conversions in DMNContextKS and CMNResultKS classes

---

kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/README.md

Verification in window system.

Mark the difference between bat and sh.

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNContextKS.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java

https://issues.jboss.org/browse/DROOLS-2115

DROOLS-2115 Remove unnecessary array-list conversions in DMNContextKS and CMNResultKS classes for 7.5.x branch

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-remote/kie-server-client/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerExecutor.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerStartupIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

another round of reverted PR - https://github.com/kiegroup/droolsjbpm-integration/pull/1348

RHDM-251 - Wildfly 11 upgrade

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java

Improve stability of JobServices requeue test

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskWithProcessDescription.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/TaskWithProcessDescriptionList.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

Added processInstanceDescription as a businessId

JBPM-6890: Adding the customTaskID as a unique identifier for an active

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TaskSearchServiceIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

The MySQL database can be started for example by using docker:
`docker run --name mysql57 -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_USER=sa -e MYSQL_PASSWORD=sa -e MYSQL_DATABASE=mydb -p 3306:3306 -d mysql:5.7 --ssl=0 --lower_case_table_names=1`

Test stabilization and adjustments

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CarInsuranceClaimCaseIntegrationTest.java

Added tests for not existing stage and ad-hoc fragment.

JBPM-6001 - Trigger AdHoc Node is not implemented for stage, JBPM-6008 - Triggering ad-hoc fragments in specific case stage

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/impl/RandomBalancerStrategy.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/impl/RoundRobinBalancerStrategy.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/LoadBalancerClientTest.java

I have added more details in here https://issues.jboss.org/browse/JBPM-6230

JBPM-6999 - Kie server client load balancer using wrong URL under concurrent access

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/config/TestConfig.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessSearchServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TaskSearchServiceIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1414

[7.7.x] Test stabilizations

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CarInsuranceClaimCaseIntegrationTest.java

#1405 for 7.7.x since the original one was merged to master only shortly after 7.7.x was created.

[7.7.x] JBPM-6001 - Trigger AdHoc Node is not implemented for stage, JBPM-6008 - Triggering ad-hoc fragments in specific case stage

---

kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java

JBPM-4646 - API corrections

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/ProcessInstanceCustomVars.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/ProcessInstanceCustomVarsList.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/QueryServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

This PR is related to https://github.com/kiegroup/jbpm/pull/1195

JBPM-7171: New custom query mapper for processes

---

kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java

[7.7.x] JBPM-4646 - API Corrections

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/util/RestUtils.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/pom.xml
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/FormResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/ContainerUpdateUiIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/FormServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/FormServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/RestJbpmBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestOnlyBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerManagementIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerRuleCapabilitiesIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerRuntimeManagementIntegrationTest.java

Copy of https://github.com/kiegroup/droolsjbpm-integration/pull/1444
@mswiderski could you please review?
This is part of an ensemble merge with:
https://github.com/kiegroup/jbpm/pull/1202
https://github.com/kiegroup/droolsjbpm-integration/pull/1445
https://github.com/kiegroup/jbpm-wb/pull/1075

[7.7.x] RHPAM-275: A user can display tasks for which he is not Potential Owner or Bussines Admin

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestOnlyBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerStartupIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1462

[7.7.x] Kie server test stabilizations

---

kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/Messages.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

- introduces the rest of case mgmt operations test coverage for KIE server
- fixes pagination for negative page or page size

[7.7.x] JBPM-6935 Add remaining case mgmt coverage and fix pagination

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/bkm-java-model/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/bkm-java-model/src/main/java/com/acme/functions/StandardDeviation.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/bkm-java-model/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/bkm-java-model/src/main/resources/Standard Deviation.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNBkmJavaIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNBkmJavaModelTest.java

execute the test on the kie-server.

DROOLS-2441 DMN runtime not using the kiecontainer root classloader

---

jbpm-process-svg/src/main/java/org/jbpm/process/svg/SVGImageProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/NodeSummary.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/model/RenderType.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/AbstractSVGProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/JBPMDesignerSVGProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/SVGProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/SVGProcessorFactory.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/StunnerSVGProcessor.java

Cherry pick commit  c621e19ba0e265b05952ec600ffe0b0533165a1e to 7.7.x
@romartin

[7.7.x] RHPAM-1003 Stunner - Diagram SVG is not highlighted on the WB

---

kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/Messages.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

- introduces the rest of case mgmt operations test coverage for KIE server
- fixes pagination for negative page or page size

JBPM-6935 Add remaining case mgmt coverage and fix pagination

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseAdminResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java

Fix getCaseInstanceProcessInstance API description typo

Fix getCaseInstanceProcessInstance API description typo

---

kie-camel/src/test/java/org/kie/camel/KieComponentIntegrationTest.java
kie-camel/src/test/java/org/kie/camel/KieComponentOpOnUriTest.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java

/cc @mswiderski really sorry I missed this!

DROOLS-1663 Kie DMN support for IMPORT decisions between DMN files

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/basetests/RestJmsSharedBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/src/main/resources/usertask.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

@sutaakar @baldimir @mswiderski Just a test to stabilize one (actually 6 with parameterized) test.

Try to stabilize testErrorHandlingFailedToSignal test

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/DMNContextKSMarshallingTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/dmn/DMNResultKSStubTest.java

/cc @etirelli @baldimir @winklerm

DROOLS-2713 DMN eval response containing list and sublist fail on server

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java
kie-spring/src/test/resources/jbpm/services/jta-services.xml
kie-spring/src/test/resources/jbpm/services/resource-local-services.xml

in addition another commit to avoid conflicts with db in kia-spring module

 JBPM-7424 - org.kie.server.json.format.date has no effect anymore in

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java

@sutaakar here is the fix and your test case

RHPAM-1240 - Aborting process in not existing container

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java

Using watchService to improve configuration change detection, creation and deletion

[RHPAM-1382] File watcher doesn't work in case of missing watched file

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerRuleCapabilitiesIntegrationTest.java

Raise scanner interval as previous one was too small, could cause Kie server to be unresponsive.
Add additional checks to verify that scanner is really doing what is expected.

Stabilize and extend testStartAndStopScanner()

---

kie-aries-blueprint/src/test/resources/META-INF/maven/pom.properties
kie-camel/src/test/resources/META-INF/maven/pom.properties
kie-spring/src/test/resources/META-INF/maven/pom.properties

* Fix kie-spring and kie-aries-blueprint tests
* Fix kie-camel "random" test failures
Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1483
Should fix test failures for 7.7.x

[7.7.x] Fix kie-spring and kie-aries-blueprint and kie-camel tests (#1483)

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

removing duplicated entry in fuse features.

[RHPAM-1227] Duplicated definition of kie-pmml feature

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/UserTaskResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

This PR is related to: https://github.com/kiegroup/jbpm/pull/1295

JBPM-7542: Create better response for user without permissions to do REST Forward task operation

---

droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml

@cristianonicolai @krisv here is the cmmm implementation added to the distribution zip

Include jbpm-case-mgmt-cmmn in the bpms distribution

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/java/org/kie/server/springboot/autoconfiguration/jbpm/extensions/SpringBootCaseKieServerExtension.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/MigrationProcessTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KieServerMigrationTest.java
kie-spring-boot/kie-spring-boot-samples/kjars/evaluation/pom2.xml

@MarianMacik please have a try with this change

Set transaction manager factory for spring boot auto configuration

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/security/SpringSecurityIdentityProvider.java

@sutaakar I believe that is what we need to get aligned

JBPM-7727 - SecurityException when SLA is triggered in case

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
kie-server-parent/kie-server-tests/pom.xml
kie-server-parent/kie-server-tests/src/test/filtered-resources/application.properties
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/IntegrationTestsWebSecurityConfig.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/KieServerIntegrationTestsApplication.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/application.properties
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/case-authorization.properties
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/pom.xml

Introducing SpringBoot test coverage.
So far WIP.

JBPM-7586 - SpringBoot - test coverage for KIE Server spring boot apps

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/ImageServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/ImageServiceBaseTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
kie-server-parent/kie-server-tests/pom.xml
kie-server-parent/kie-server-tests/src/test/filtered-resources/application.properties
kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/security/SpringSecurityIdentityProvider.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/ExecutorJobsTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/application-executor.properties
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/IntegrationTestsWebSecurityConfig.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/KieServerIntegrationTestsApplication.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/application.properties
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/case-authorization.properties
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KieServerApplication.java
kie-spring-boot/kie-spring-boot-samples/pom.xml
kie-spring/src/main/java/org/kie/spring/persistence/AbstractKieSpringJpaManager.java
kie-spring/src/main/java/org/kie/spring/persistence/KieSpringJpaManager.java
kie-spring/src/test/java/org/kie/spring/jbpm/PerProcessInstanceSpringTest.java
kie-spring/src/test/java/org/kie/spring/jbpm/PerProcessInstanceWithExternalTXSpringTest.java

depends on https://github.com/kiegroup/jbpm/pull/1325

[7.11.x] Backport of issues for 7.1.GA

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/jms/OptaPlannerJmsResponseHandlerIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/1576

[7.11.x] JBPM-7777 - Stabilize OptaplannerIntegrationTest

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/ContainerManager.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryInKjarIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/1339

JBPM-7809 - Resolve datasource name for query definitions at runtime

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/test/java/org/kie/server/integrationtests/common/KieServerIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

Stabilize SpringBoot tests

---

kie-server-parent/kie-server-router/kie-server-router-client/src/test/java/org/kie/server/router/client/KieServerRouterEventListenerRetryTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerInstanceImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerScannerEventListener.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplOperationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerSynchronization.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerRuleCapabilitiesIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kie-server-testing-server-custom-settings.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-1/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-1/src/main/java/org/kie/server/testing/Person.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-1/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-1/src/main/resources/kjar1/rules.drl
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-2/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-2/src/main/java/org/kie/server/testing/Person.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-2/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/container-isolation-kjar-SNAPSHOT-2/src/main/resources/kjar1/rules.drl
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/ContainerSnapshotUpdateIntegrationTest.java
kie-server-parent/kie-server-tests/pom.xml

Contains fix and a test coverage.
The test fails on line 73 as the rule seems not to fire.

Rhdm 733 test coverage

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java

filtering correctly by deployment id
depends on https://github.com/kiegroup/jbpm/pull/1346

[RHPAM-1599] REST Endpoint for getting errors in a kie-container doesn't filter the result by container id

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/commands/KieServerControllerDescriptorCommand.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/KieServerControllerServiceResponse.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/notification/KieServerControllerNotification.java

(cherry picked from commit 00ca36b03c879d45929f256a844ebfa97e7a29b5)

BXMSPROD-38: missing imports for com.fasterxml.jackson upgrade

---

kie-server-parent/kie-server-tests/pom.xml
kie-server-parent/kie-server-wars/kie-server/pom.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-servlet-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/META-INF/context.xml
kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/WEB-INF/web.xml

Waiting for https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/853 to be merged first.

BAQE-441 Update dependencies for tomcat

---

droolsjbpm-bpms-distribution/src/main/assembly/pre-bin.xml
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerEnvironment.java
kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMProperties.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerProperties.java

depends on 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/861
https://github.com/kiegroup/droolsjbpm-knowledge/pull/337
https://github.com/kiegroup/drools/pull/2120
https://github.com/kiegroup/jbpm/pull/1357
https://github.com/kiegroup/droolsjbpm-integration/pull/1612

JBPM-7880 - ElasticSearch event emitter for runtime events

---

kie-infinispan/drools-infinispan-persistence/src/main/resources/infinispan.xml

@ederign @jhrcek This fixes test in master. I had to update infinispan configuration file.
Would you mind to review?

[AF-1668]: Fixed wrong infinispan configuration file. Also tests fixed

---

droolsjbpm-bpms-distribution/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/DBExternalResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/DBExternalResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/src/test/java/org/kie/server/integrationtests/policy/DBExternalResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/DBExternalResource.java
kie-spring/pom.xml
kie-spring/src/test/java/org/kie/spring/jbpm/AbstractJbpmSpringTest.java
kie-spring/src/test/java/org/kie/spring/jbpm/tools/SpringDataSourceFactory.java
kie-spring/src/test/resources/jbpm/no-initial-context/datasource-local.xml
kie-spring/src/test/resources/jbpm/services/jta-services.xml
kie-spring/src/test/resources/jbpm/services/resource-local-services.xml
kie-spring/src/test/resources/org/kie/spring/timer/conf/spring-conf.xml

depends on:
https://github.com/kiegroup/drools/pull/2130
https://github.com/kiegroup/jbpm/pull/1365

[BAQE-439] Once more:  Narayana + DBCP integration

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/commands/KieServerControllerDescriptorCommand.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/KieServerControllerServiceResponse.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/notification/KieServerControllerNotification.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
kie-server-parent/kie-server-tests/pom.xml
kie-server-parent/kie-server-wars/kie-server/src/main/ee7-resources/WEB-INF/jboss-deployment-structure.xml

Upgrate to Wildfly 14
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
* https://github.com/kiegroup/optaplanner/pull/437
* https://github.com/kiegroup/optaplanner-wb/pull/304

[AF-1555]: Upgrade WF11 to WF14

---

kie-spring-boot/pom.xml

https://issues.jboss.org/browse/JBPM-7685

JBPM-7685: synced narayana-jta version to 5.9.0.Final

---

camel-container-tests/camel-container-integration-tests/pom.xml
kie-server-parent/kie-server-tests/pom.xml

@sutaakar @jiripetrlik We'll see if this fixes the full downstream.

Fix full downstream build

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

Follow-up https://github.com/kiegroup/drools/pull/2148
Superseeds https://github.com/kiegroup/drools/pull/2154
/cc @mariofusco @etirelli @baldimir @jiripetrlik

Use ch.obermuhlner:big-math in OSGi feature file

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/services/SpringKModuleDeploymentService.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/ConfigurationTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/TestAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/handlers/WidWorkItemHandler.java

@tsurdilo here is the enhancement we talked about

JBPM-7969 - Make use of @Wid annotation to register work item handlers

---

kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerImpl.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerReconnectHandler.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket-client/src/test/java/org/kie/server/controller/websocket/client/WebSocketKieServerControllerReconnectHandlerTest.java

adding the proper message handler during reconnection

[RHPAM-1354] Kie server loses connection to the Business Central

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-wars/kie-server/src/main/ee7-resources/META-INF/kie-server-jms.xml
kie-server-parent/kie-server-wars/kie-server/src/main/ee7-resources/WEB-INF/classes/wildfly-jbpm.audit.jms.properties
kie-server-parent/kie-server-wars/kie-server/src/main/ee7-resources/WEB-INF/ejb-jar.xml

depends on 
https://github.com/kiegroup/jbpm/pull/1377 
https://github.com/kiegroup/droolsjbpm-knowledge/pull/343

JBPM-7906 - Audit Mode should apply to task log information

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNMessageKS.java

/cc @manstis @etirelli @baldimir @jiripetrlik
depends on https://github.com/kiegroup/drools/pull/2165

DROOLS-3335 Broken DMN resource to inhibit KJAR and report error

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/AdditionalPropertiesIntegrationTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/BuildMojoIntegrationTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/BuildPMMLTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/InjectReactiveIntegrationTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/KJarWithDMNIntegrationTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/KieMavenPluginBaseIntegrationTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/SerializeMojoIntegrationTest.java
kie-plugins-testing/src/test/java/org/kie/maven/plugin/TestUtil.java
kie-plugins-testing/src/test/projects/kjar-7-with-dmn/pom.xml
kie-plugins-testing/src/test/projects/kjar-7-with-dmn/src/main/resources/META-INF/kmodule.xml
kie-plugins-testing/src/test/projects/kjar-7-with-dmn/src/main/resources/ch11MODIFIED.dmn
kie-plugins-testing/src/test/projects/kjar-7-with-dmn/src/main/resources/simple-dmn.dmn

@tarilabs @mariofusco @lucamolteni @etirelli please review.

DROOLS-3072 Add integration test for kie-maven-plugin with DMN

---

jbpm-simulation/src/main/java/org/jbpm/simulation/SimulationRunner.java

As discussed, this PR move to kie-internal the fluent API because it is still experimental
@mariofusco @mdproctor @kkufova 
PRs list:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/349
https://github.com/kiegroup/drools/pull/2177
https://github.com/kiegroup/drools-wb/pull/1016
https://github.com/kiegroup/droolsjbpm-integration/pull/1661

[DROOLS-3401] Moved Fluent API to kie-internal

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/WebSocketKieControllerNotificationIntegrationTest.java

Replacement of https://github.com/kiegroup/droolsjbpm-integration/pull/1664

kie-server-tests: Stop embedded server in case of test failure

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java

Reusing JIRA as I found one more place when the change isn't applied.

JBPM-7683: Use Per process instance strategy for SLA tests

---

kie-camel/src/main/java/org/kie/camel/KieProducer.java
kie-camel/src/test/java/org/kie/camel/KieClientServicesIntegrationTest.java

Added the next client:
CaseServicesClient
DocumentServicesClient
JobServicesClient
QueryServicesClient
SolverServicesClient
UIServicesClient
UserTaskServicesClient

[RHPAM-1770] Missing producers for kie server clients in Kie camel component

---

kie-server-parent/kie-server-tests/README.md

Instructions to run embedded integration tests in IDEA

---

kie-osgi/kie-karaf-itests/pom.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/META-INF/persistence.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/org/kie/karaf/itest/blueprint/processpersistence/datasource.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/org/kie/karaf/itest/blueprint/processpersistence/persistence.xml
kie-osgi/kie-karaf-itests/src/test/filtered-resources/org/kie/karaf/itest/kie-beans-persistence.xml
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringjBPMPersistenceKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintjBPMPersistenceKarafIntegrationTest.java

@jiripetrlik could you please review?

DROOLS-3543 Parameterize database properties for OSGi tests

---

camel-container-tests/camel-container-tests-module/pom.xml
drools-simulator/pom.xml
kie-camel/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-insurance-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-insurance/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/decision-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/definition-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/deployment-descriptor-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/per-process-instance-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/multimodule-project/multimodule-project-domain/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/rest-processes/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/src/test/filtered-resources/kjars-sources/definition-project-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/src/test/filtered-resources/kjars-sources/definition-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/filtered-resources/kjars-sources/common-parent/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/filtered-resources/kjars-sources/definition-project-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/filtered-resources/kjars-sources/definition-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-test-web-service/pom.xml

PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215

Align JAXB and JAXWS APIs with Wildfly

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/JobsHttpHandler.java

@sutaakar would you mind to review?

JBPM-8191 - Smart router cannot handle job requests

---

kie-server-parent/kie-server-tests/pom.xml

Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/885

JBPM-7951 Remove patched tomcat-dbcp

---

kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/main/java/org/kie/server/controller/openshift/storage/ServerTemplateConverter.java
kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/java/org/kie/server/controller/openshift/storage/ServerTemplateConverterTest.java
kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/resources/test-kieserver-state-config-map.yml

Related to AF-1685: Development Lifecycle Streamline (#1698)

[JBPM-8220] Update ServerTemplateConverter

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml

@cimbalek This should fix the build.

Fix duplicated classes

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/pom.xml
kie-server-parent/kie-server-tests/pom.xml
kie-server-parent/kie-server-tests/src/test/filtered-resources/application.properties
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-drools/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-drools/src/main/java/org/kie/server/springboot/autoconfiguration/drools/PrometheusKieServerAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/resources/application.properties

And fix related issues.
@lucamolteni @MarianMacik Please take a look.

Enable Prometheus metrics also for SpringBoot

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyDecisionTreeModelIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/pmml/ApplyScorecardModelIntegrationTest.java

@jiripetrlik Please take a look.

Raise timeout for container creation in pmml tests

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml

This library was added to features.xml but was missing in features for Fuse

Add missing big math library to DMN Fuse feature

---

process-migration-service/src/main/java/org/kie/processmigration/rest/PlanResource.java
process-migration-service/src/main/java/org/kie/processmigration/service/impl/KieServiceImpl.java
process-migration-service/src/main/java/org/kie/processmigration/service/impl/MigrationServiceImpl.java
process-migration-service/src/test/java/org/kie/processmigration/persistence/TestEntityManager.java
process-migration-service/src/test/java/org/kie/processmigration/service/AbstractPersistenceTest.java
process-migration-service/src/test/java/org/kie/processmigration/service/MigrationServiceImplTest.java

* Unit tests were failing due to updated hibernate library
* Fixed problem while updating Migration instances

Fix tests and Migration update

---

jbpm-process-svg/src/main/java/org/jbpm/process/svg/SVGImageProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/AbstractSVGProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/JBPMDesignerSVGProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/SVGProcessor.java
jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/StunnerSVGProcessor.java
jbpm-process-svg/src/test/java/org/jbpm/process/svg/TestEvalutionSVG.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/UIServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/UIServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/ImageResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/ImageServiceBase.java

added new process instance diagram color customization parameters

JBPM-8257:Configurable Color coding for executed flows in Process model

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/ExecModelMode.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/MVNValidatorMojo.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/MvelValidatorMojo.java
kie-maven-plugin/src/main/resources/META-INF/plexus/components.xml

[DROOLS-3708] Support Mvel Validator in the kie-maven-plugin

---

kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/java/org/kie/server/controller/common/KieControllerServletListener.java

starting/stopping the executor service in the listener

[JBPM-8348] Tomcat doesn't correctly stop Kie server controller healt hcheck

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/JbpmKieServerExtensionTest.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/1783
@mswiderski @jstastny-cz could you please take a look?
This is part of an ensemble, please merge with:
https://github.com/kiegroup/jbpm/pull/1467
https://github.com/kiegroup/droolsjbpm-integration/pull/1784

[7.18.x] JBPM-8363: EJB Timer error in development mode for existing process during deploy

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/JbpmKieServerExtensionTest.java

@jstastny-cz @mswiderski could you please take a look?
This is part of an ensemble please merge with:
https://github.com/kiegroup/jbpm/pull/1466
https://github.com/kiegroup/droolsjbpm-integration/pull/1783

JBPM-8363: EJB Timer error in development mode for existing process during deploy

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java

@mariofusco @baldimir please review

[3787] Filter test path also on windows

---

jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/AbstractSVGProcessor.java
jbpm-process-svg/src/test/java/org/jbpm/process/svg/TestEvalutionSVG.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/ImageServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/ImageServiceBaseTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/evaluation-svg.svg

Added viewBox attribute to svg returned by Process Instance image sevices

JBPM-8306: Process diagram images are hardcoded to large sizes

---

kie-spring-boot/pom.xml

RHPAM-1878: exclude because of byte-buddy upgrade

---

kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/get-models2/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/get-models2/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/get-models2/src/main/resources/check.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNGetModels2IntegrationTest.java

.. empty
@etirelli @baldimir @jiripetrlik

DROOLS-3876 DMN kie server get models endpoint when inputdata typeref ..

---

kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/ModelEvaluatorServiceBase.java

@etirelli @baldimir @jiripetrlik
requires https://github.com/kiegroup/drools/pull/2308

DROOLS-3886 DMN externalize kie server model execution logic

---

kie-server-parent/kie-server-services/kie-server-services-optaplanner/pom.xml
kie-server-parent/kie-server-services/kie-server-services-optaplanner/src/main/java/org/kie/server/services/optaplanner/SolverServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-prometheus/pom.xml
kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus/PrometheusMetrics.java
kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus/PrometheusMetricsSolverListener.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/java/org/kie/server/integrationtests/optaplanner/OptaplannerIntegrationTest.java

See https://issues.jboss.org/browse/PLANNER-1443 for more details.

PLANNER-1443: Monitoring of OptaPlanner on kie-server

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/prometheus/PrometheusIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNMetricIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/DroolsMetricIntegrationTest.java

Also contains reproducer for JBPM-8452

JBPM-8347 Increate Prometheus metrics test coverage

---

kie-maven-plugin-example/src/main/java/org/declaredtype/FactA.java
kie-maven-plugin-example/src/main/resources/META-INF/kmodule.xml
kie-maven-plugin-example/src/main/resources/org/declaredtype/decB.drl
kie-maven-plugin-example/src/main/resources/org/declaredtype/rules.drl
kie-maven-plugin-example/src/test/java/org/kie/kproject/DMNTest.java
kie-maven-plugin-example/src/test/java/org/kie/kproject/KProjectTest.java

Related to https://github.com/kiegroup/drools/pull/2327

Fix kie-maven-plugin-example and added reproducer for DROOLS-3960

---

kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/ee7-resources/WEB-INF/web.xml
kie-server-parent/kie-server-controller/kie-server-controller-standalone/src/main/webc-resources/WEB-INF/web.xml

bump version to web 3.1 and added the proper constraints to avoid SEVERE log

[JBPM-8177] Security exceptions in localhost log when running kie-server on JWS

---

process-migration-service/frontend/package-lock.json
process-migration-service/frontend/package.json
process-migration-service/pom.xml

This should solve issues with daily builds.
@ruromero can you review as well?

Set npm version to 0.0.0

---

process-migration-service/frontend/package-lock.json
process-migration-service/frontend/package.json
process-migration-service/src/test/resources/META-INF/persistence.xml

This should remove automatic installation of git hooks.

Remove husky from process-migration-service

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-100/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-100/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-100/src/main/resources/air-conditioning-control.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-100/src/main/resources/air-conditioning-data-types.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-101/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-101/src/main/resources/air-conditioning-control.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-101/src/main/resources/air-conditioning-data-types.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNImportItemDefinitionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNImportItemDefinitionTest.java

@etirelli @baldimir @jomarko
Requires https://github.com/kiegroup/drools/pull/2357

DROOLS-4062 DMN KieContainer upgrade DMN Import resolution strategy

---

kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml

added org.slf4j:slf4j-jdk14 to the assembly so weblogic can log

[JBPM-8506] Need slf4j adapter for kie server with RHDM 7

---

process-migration-service/frontend/jest.config.js
process-migration-service/frontend/package-lock.json
process-migration-service/frontend/package.json

Fix https://issues.jboss.org/browse/JBPM-8487

[JBPM-8487] Generate frontend tests results in junit format

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

Requires https://github.com/kiegroup/drools/pull/2370
@etirelli @baldimir @danielezonca @vblagoje

DROOLS-4075 DMN merge upstream PMML evaluators

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/rest/StackTraceIncludedIntegrationTest.java

JBPM-8399: Fix EAP test for stack trace included

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java

[JBPM-8593] addDynamicUserTask method argument should be changed from Description to Subject

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-dmn/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#1002

BAQE-1039 - Change revapi to check against 7.23.0.Final

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerContainerDeployment.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileInit.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerContainerDeploymentTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/storage/file/KieServerStateFileInitTest.java

[BAPL-1262] [Field-RFE] OpenShift - Smart Router container resolver for aliases
https://issues.jboss.org/browse/BAPL-1262
Signed-off-by: David Ward <dward@redhat.com>

[BAPL-1262] [Field-RFE] OpenShift - Smart Router container resolver for aliases

---

kie-server-parent/kie-server-tests/pom.xml
pom.xml

@MarianMacik FYI
@mbiarnes Should fix the Tomcat issues in upstream build.

Use Tomcat version defined in kie-parent

---

kie-maven-plugin-example/src/main/resources/org/kie/kproject/v1_2/ch11MODIFIED.dmn

align to DROOLS-4129 required modifications.
/cc @lucamolteni DROOLS-4356 JIRA reporter.
/cc @etirelli @baldimir @jiripetrlik

DROOLS-4356 Failing test in kie-maven-plugin-example

---

process-migration-service/README.md
process-migration-service/pom.xml
process-migration-service/src/main/resources/META-INF/persistence.xml
process-migration-service/src/main/resources/project-defaults.yml

Fix https://issues.jboss.org/browse/JBPM-8497

[JBPM-8497] Document integration with production databases

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java

setting to true RunAsFilter so resources can be loaded properly

[JBPM-8700] Not able to enable swagger documentation when using spring-boot-kieserver

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/DMNServicesClientImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNPMMLIntegrationTest.java

align BigDecimal utils
@jiripetrlik

RHDM-1050 Incorrect marshalling of BigDecimal output variables in DMN

---

process-migration-service/pom.xml
process-migration-service/src/main/java/org/kie/processmigration/rest/PlanResource.java

https://issues.jboss.org/browse/RHPAM-2328
removed unsupported thorntail deps from PIM

RHPAM-2328: removed unsupported 'io.thorntail:bom-all' and 'swagger'

---

pom.xml

@rsynek Can you please take a look?

Add test coverage measurement for droolsjbpm-integration repo

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/SerializeMojo.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java

Mostly addressing possible leaks by possibly not closed streams.
@mswiderski Could you please take a look?

Fixing blocker issues reported by SonarCloud

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/DMNServicesClientImpl.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/pmml/DMNPMMLMiningIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/pmml/DMNPMMLRegressionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/pmml/DMNPMMLScorecardIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/pmml/DMNPMMLTreeIntegrationTest.java

coercion alignments.
Requires:
https://github.com/kiegroup/drools/pull/2548
Connected to:
https://github.com/kiegroup/kie-jpmml-integration/pull/18
/cc 
@etirelli @jiripetrlik @baldimir

DROOLS-4556 DMN multiple output PMML alignments

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-dmn/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#1070

BAQE-1114 - Change revapi to check against 7.26.0.Final

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/usertask.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

@mareknovotny This should fix the FDB issues.

[JBPM-8801] Add explicit createdBy assignment to a task for tests

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java

using the cxf path as a base for swagger feature. this matches the documentation.

[JBPM-8765] Swagger points to wrong URL for Business application

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/Marshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/MarshallingFormat.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/MarshallingFormatTest.java
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/RestEasy960Util.java
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/variant/QualityValue.java
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/variant/ServerDrivenNegotiation.java
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/variant/VariantQuality.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/marshal/MarshallerHelper.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/IdentifierJbpmRestIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/JbpmRestIntegrationTest.java
process-migration-service/frontend/package-lock.json

changing the marshalling for returning proper json objects in case of primitive types

[JBPM-8725] Invalid REST API return type - quated string instead of json/xml

---

kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/OpenShiftStartupStrategy.java

Cherry picked and applying the same changes to 7.26.x branch
Related PR:
https://github.com/kiegroup/droolsjbpm-integration/pull/1914
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

[RHPAM-2421] OpenShiftStartupStrategy doesn't respin Kie server pods after Kie container change

---

process-migration-service/frontend/src/__tests__/tabMigration/PageEditMigrationDefinitionModal.test.js
process-migration-service/frontend/src/__tests__/tabMigrationPlan/PageMigrationScheduler.test.js
process-migration-service/frontend/src/component/tabMigrationPlan/wizardExecuteMigration/PageMigrationRunningInstances.js
process-migration-service/frontend/src/component/tabMigrationPlan/wizardExecuteMigration/PageMigrationScheduler.js

Fix https://issues.jboss.org/browse/JBPM-8476

[JBPM-8476] Fix selectAll and scheduledStartTime format

---

kie-server-parent/kie-server-wars/kie-server/src/main/ee-resources/WEB-INF/classes/restricted-groups.properties
kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/WEB-INF/classes/restricted-groups.properties

JBPM-8766 Cannot start a task if elytron adapter is installed (#1910)

---

kie-maven-plugin/pom.xml
kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/ProjectPomModel.java
kie-maven-plugin/src/test/java/org/kie/maven/plugin/ProjectPomModelTest.java

(cherry picked from commit 26fbbae0f5716893cdc2679a43659a6ebdd339cb)
Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/1917
Should be merged with https://github.com/kiegroup/drools/pull/2583

DROOLS-4602 Create PomModel for KieBuilder directly in kie-maven-plugin

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-router/kie-server-router-client/src/main/java/org/kie/server/router/client/KieServerRouterEventListener.java
kie-server-parent/kie-server-router/kie-server-router-client/src/test/java/org/kie/server/router/client/KieServerRouterEventListenerTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/pom.xml
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouterConstants.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/identity/FileStoredIdentityManager.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/identity/HashUtil.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/identity/IdentityService.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/identity/KieServerInstanceAccount.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/identity/KieServerInstancePrincipal.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/resources/META-INF/services/org.kie.server.router.identity.IdentityService
kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/router/client/KieServerRouterClient.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterAuthNoIdPTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterAuthTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterCommandTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/MockIdentityService.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/resources/META-INF/services/org.kie.server.router.identity.IdentityService

adding functionality for kie service instance auth in smart router.

[JBPM-8855] Smart Router management endpoints authentication

---

process-migration-service/pom.xml

BXMSPROD-560 lock-treatment-tool added to productized profile

---

kie-osgi/kie-karaf-features/pom.xml
kie-spring-boot/pom.xml

RHPAM-2466 narayana dependencies removed from kie-spring-boot project

---

process-migration-service/frontend/package-lock.json
process-migration-service/frontend/package.json
process-migration-service/pom.xml

BXMSPROD-597
* lock-treatment-tool added to dev-dependencies
* locktt script added
* pom execution changed to npm run locktt

BXMSPROD-597: frontend project locktt execution improved

---

camel-container-tests/camel-container-tests-module/pom.xml
droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-brms-distribution/pom.xml
kie-camel/pom.xml
kie-integration-test-coverage/kie-spring-test/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/pom.xml
kie-spring-boot/kie-spring-boot-starters/jbpm-spring-boot-starter-basic/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter-drools/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter-jbpm/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter-optaplanner/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter/pom.xml
kie-spring-boot/pom.xml
kie-spring/pom.xml

Depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1086

Remove Spring Boot dependency management

---

kie-server-parent/kie-server-tests/pom.xml

@MarianMacik Can you please take a look?

Refactor Kie server test profiles to get rid of default profile activation

---

kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/AbstractKarafIntegrationTest.java

DROOLS-4946 - Karaf integration tests fail

---

kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/AbstractKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/AbstractKieSpringKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/DecisionTablesIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/InstallFeaturesKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieDMNKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringDependencyKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/KieSpringMetaInfAppContextKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/RuntimeManagerFeatureKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/SimpleKieSpringKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/WorkbenchModelsKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/beans/AbstractProcessWithPersistenceBean.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/beans/ProcessWithPersistenceDirectBean.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/beans/ProcessWithPersistenceEnvBean.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintDependencyKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintImportIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintProcessDependencyKarafIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintScannerReimportIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/KieCamelBlueprintCommandIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/KieCamelBlueprintDTIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/KieCamelBlueprintIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/KieCamelRemoteIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/model/Person.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/tools/DroolsCommandHelper.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJaxbIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJsonIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationXstreamIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/pmml/AbstractPmmlIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/util/KieScannerTestUtils.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/util/PaxExamWithWireMock.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/util/PaxExamWithWireRestClientMock.java

For more details see https://issues.redhat.com/browse/DROOLS-4946

DROOLS-4946: Organize imports

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/ExecModelMode.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java

According to 
https://issues.redhat.com/browse/BXMSDOC-4481
@vidya-iyengar

[DROOLS-4370] Rename WITHDRL to YES_WITHDRL

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/services/SpringRegisterableItemsFactory.java

adding autodiscovery support for NotificationListener

[JBPM-8998] Missing SpringBoot support in NotificationListener

---

process-migration-service/README.md
process-migration-service/pom.xml
process-migration-service/src/main/java/org/kie/processmigration/rest/HealthStatus.java
process-migration-service/src/main/java/org/kie/processmigration/rest/HealthStatusResource.java
process-migration-service/src/test/java/org/kie/processmigration/it/ProcessMigrationIntegrationTest.java

Fix https://issues.redhat.com/browse/BAPL-1447

[BAPL-1447] Use MicroProfile Health 2.0

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/UserTaskWithRollback.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java

As the change at [jbpm#1584](https://github.com/kiegroup/jbpm/pull/1584) involves TransactionManager, let's test it also in container.

[JBPM-8988] test ProcessAutoAckError command in container

---

kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/KieServerControllerConstants.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
Related JIRAs
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2657
https://issues.redhat.com/projects/RHPAM/issues/RHPAM-2008
https://issues.redhat.com/browse/JBPM-8585
Related PRs
https://github.com/kiegroup/kie-wb-common/pull/3139
Followed-By PRs
https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/414
https://github.com/jboss-container-images/rhdm-7-openshift-image/pull/329
https://github.com/jboss-container-images/jboss-kie-modules/pull/352
https://github.com/kiegroup/kie-cloud-operator/pull/353

[RHPAM-2657] KieServer Scale-Up-From-Zero lifecycle hooks logic broken

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerSwaggerIntegrationTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/2003

[7.33.x] Fix Swagger docs test for Business central

---

kie-server-parent/kie-server-tests/pom.xml

To be aligned with certified version for websphere.

Update cargo.container.id to websphere 9

---

kie-camel/src/test/java/org/kie/camel/embedded/camel/component/BatchTest.java

Enabled executable model execution in CamelTest
Testing
https://github.com/kiegroup/drools/pull/2763

 [RHDM-1237] Ensure all executable model classes are generated -

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-dmn/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json

depends on kiegroup/droolsjbpm-build-bootstrap#1190

BAQE-1267 - Change revapi to check against 7.33.0.Final

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-common/src/main/java/org/kie/server/integrationtests/shared/KieServerDeployer.java
kie-server-parent/kie-server-tests/pom.xml

Retrieve Maven binary for Kie server tests using maven.home property

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/QueryFilterSpec.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/QueryParam.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/util/QueryFilterSpecBuilder.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/util/QueryParamFactory.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JAXBMarshallerTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/util/QueryFilterSpecBuilderTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/QueryDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

modify payload and added an adapter for recursive query param / ast expression

[JBPM-8910] How to use a "OR" query operator in a custom query in the query-parameters

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerControllerImpl.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerControllerImplTest.java

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/2020

[7.33.x] [JBPM-9031] Fix condition evaluating Server template capabilities

---

kie-camel/src/test/java/org/kie/camel/KieComponentIntegrationTest.java
kie-camel/src/test/java/org/kie/camel/KieComponentOpOnUriTest.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/dmn/DMNResultKS.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/dmn/DMNResultKSContextTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/model/dmn/DMNResultKSStubTest.java

This PR is required to adapt to the changes introduced with [PR 2279 in drools](https://github.com/kiegroup/drools/pull/2779)

[FAI-58] Add metadata to DMN context

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java

Associate the model with the top nested form field binding name

[JBPM-9015] KIE-Server rendererd forms bind data to incorrect process variable names

---

kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/spec/ContainerSpec.java
kie-server-parent/kie-server-controller/kie-server-controller-api/src/main/java/org/kie/server/controller/api/model/spec/ServerTemplate.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/InMemoryKieServerTemplateStorage.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/AbstractServiceImplTest.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/SpecManagementServiceImplTest.java
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/test/java/org/kie/server/controller/rest/ConcurrentModificationExceptionTest.java

different instances of the server template through the storage.

[JBPM-8936] ConcurrentModificationException when retrieving server template

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml

As Swagger is tested in SwaggerIntegrationTest

Enable SpringBoot swagger for kie-server-integ-tests-all module

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/CustomNotificationListenerTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/listeners/CountDownLatchNotificationListener.java

[RHPAM-2705] Springboot @Autowired beans in NotificationListener (remove the need of @Lazy for some services)

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter/pom.xml

parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1183

some exclusions for Quartz 2.3.2 upgrade related

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/CustomNotificationListenerTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/listeners/CountDownLatchNotificationListener.java

[7.7.x] [RHPAM-2705] Springboot @Autowired beans in NotificationListener (remove the need of @Lazy for some services) 

---

kie-performance-kit/src/main/java/org/kie/perf/TestConfig.java
kie-performance-kit/src/main/java/org/kie/perf/suite/ConcurrentLoadSuite.java
kie-performance-kit/src/main/java/org/kie/perf/suite/LoadSuite.java
kie-performance-kit/src/main/java/org/kie/perf/suite/SoakSuite.java

The build of the framework locally passed. However, that does not say much.

Parametrize test package for kie-performance-kit

---

drools-ha/ha-core-infra/pom.xml
drools-ha/ha-core/pom.xml
drools-ha/ha-remote/pom.xml

@jiripetrlik @danielezonca 
Updated with RHPAM-2800 https://github.com/kiegroup/openshift-drools-hacep/pull/85

[Drools-5208]Remove modules moved into integration

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/UserTaskResource.java

giving error 40x from server when it is not authorized

[RHPAM-2810] Non potential owner of task able to update task variable through REST api

---

kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolutionSynchronizer.java

PLANNER-1933: Remove error message informing about an update to a solution outside of planning

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml
kie-server-parent/kie-server-api/pom.xml
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/xstream/XStreamMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/CustomXstreamMarshallerBuilder.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/objects/DateObject.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/storage/FileBasedKieServerTemplateStorage.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/file/KieServerStateFileRepository.java
kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateCloudRepository.java

Part of https://github.com/kiegroup/kie-soup/pull/137

KOGITO-1546 XStreamUtils kie-soup refactoring

---

kie-server-parent/kie-server-wars/kie-server/src/main/webc-resources/README.md

Update the README in response to https://issues.jboss.org/browse/DROOLS-4399

Update README.md 

---

camel-container-tests/camel-container-integration-tests/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml
kie-server-parent/kie-server-tests/README.md
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-policy/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/pom.xml
kie-server-parent/kie-server-tests/pom.xml
process-migration-service/pom.xml

https://issues.redhat.com/browse/JBPM-9044
Parent PR kiegroup/droolsjbpm-build-bootstrap/pull/1203

[JBPM-9044] Upgrade Wildfly to 18.0.1.Final

---

drools-ha/ha-core-infra/src/test/java/org/kie/hacep/LocalStorageKieSessionTest.java

[Drools-5321] Randomly failing test org.kie.hacep.LocalStorageKieSessionTest.fireUntilHaltTest on timeout

---

kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/java/org/kie/server/controller/openshift/storage/OpenShiftServerTemplateStorageTest.java
kie-server-parent/kie-server-controller/kie-server-controller-openshift/src/test/java/org/kie/server/controller/openshift/storage/ServerTemplateConverterTest.java
kie-server-parent/kie-server-services/kie-server-services-openshift/src/test/java/org/kie/server/services/openshift/impl/storage/cloud/KieServerStateOpenShiftRepositoryTest.java

If CRUD mode was used in OpenShift mock server then HTTPS was always enabled.
This causes certificate issues in JDK 11 on RHEL 8.
This workaround disables HTTPS while keeping CRUD functionality.

Workaround for HTTPS issues with Kie server OpenShift tests

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/ConvertUtilsTest.java

Changing ConvertUtils to include subject in return values

[JBPM-9126] Missing "subject" attribute in the UserTaskInstanceDesc

---

kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/main/java/org/kie/server/services/taskassigning/core/model/TaskAssigningSolution.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/main/java/org/kie/server/services/taskassigning/core/model/solver/condition/TaskAssigningConditions.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/main/java/org/kie/server/services/taskassigning/core/model/solver/filter/TaskByGroupAndSkillsChangeMoveFilter.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/main/resources/org/kie/server/services/taskassigning/solver/taskAssigningDefaultSolverConfig.xml
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/main/resources/org/kie/server/services/taskassigning/solver/taskAssigningScoreRules.drl
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/test/java/org/kie/server/services/taskassigning/core/model/TestUtil.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/test/java/org/kie/server/services/taskassigning/core/model/solver/TaskHelperTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/test/java/org/kie/server/services/taskassigning/core/model/solver/condition/TaskAssigningConditionsTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-core/src/test/java/org/kie/server/services/taskassigning/core/model/solver/filter/TaskByGroupAndSkillsChangeMoveFilterTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolverBuilder.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolverDef.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningConstants.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/SolverBuilderTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/SolverHandlerTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionTest.java

- Adds optimizations resulting from the benchmarker results

PLANNER-1980: Create a benchmark of task assigning solver

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessUserTaskServicesSecurityIntegrationTest.java

Added a couple of tests for the new APIs to create process from nodeIds in the security container to check 403 Response for non-allowed users.

[JBPM-9129] Add tests for security container

---

kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee8-container.xml

Including CXF jar that was reported as missing

[JBPM-9174] CXF warning exception because of class loading

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/local-date-unary-check/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/local-date-unary-check/src/main/java/org/example/localdateunarytest/Person.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/local-date-unary-check/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/local-date-unary-check/src/main/resources/test.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNLocalDateIntegrationTest.java

This PR is not a fix.
For more details see: https://issues.redhat.com/browse/JBPM-9173

JBPM-9173: Create reproducer test for dmn date on kie server evaluation

---

kie-server-parent/kie-server-tests/pom.xml

Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350

Manage postgresql version with kie-parent

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java

Change integration test to check for 404 rather than for 200
Depends on [jbpm#1668](https://github.com/kiegroup/jbpm/pull/1668)

JBPM-9151 API return 200 if containerId does not exist

---

process-migration-service/pom.xml

Exclusions to avoid classes duplications after upgrading to Thorntail 2.7.0.Final
Refers to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1352

[RHPAM-2977] Upgrade thorntail

---

kie-osgi/kie-karaf-features/pom.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java

Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1352

[RHPAM-2977] upgrade jackson to version 2.10.4

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceAdminServiceIntegrationTest.java

Covering integration scenarios for updating SLA Timer.
Notice that currently SLA Due Date is only persisted (after updated) when process is finished (completed or aborted).

[RHPAM-2980] Add integration tests for update SLA timer

---

process-migration-service/pom.xml

Signed-off-by: Jakub Schwan <jschwan@redhat.com>

[RHPAM-3000] Attach classes for Process migration service war

---

process-migration-service/pom.xml
process-migration-service/src/test/filtered-resources/project-test.yml

https://issues.redhat.com/browse/JBPM-9196

[JBPM-9196] configure port in properties

---

kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-runtime/src/main/java/org/kie/server/services/taskassigning/runtime/command/DelegateAndSaveCommand.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-runtime/src/test/java/org/kie/server/services/taskassigning/runtime/command/DelegateAndSaveCommandTest.java

(cherry picked from commit 19822d8c7b83f7624dcf8563d10192f0057df80c)

PLANNER-2047: Using Task Assigning with DDL prevents users from completing tasks

---

kie-spring-boot/pom.xml

https://issues.redhat.com/browse/RHPAM-2734

RHPAM-2734: deps for SB 2.2.6 upgraded

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/JACCIdentityProvider.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/security/JACCIdentityProviderWildFlyTomcatTest.java

A proper implementation for hasRole has been implemented

[JBPM-9229] hasRole implementation shouldn't return always false

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/JMXQuartzSchedulerTest.java

Depends on [jbpm#1672](https://github.com/kiegroup/jbpm/pull/1672)
Added a springboot test using JMX to obtain jobName containing the node name for an "Intermediate Catch Event"

[JBPM-6574] Test with JMX that timer node name has been added to jobName

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithCaseCorrelationKey.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithCaseDefinitionId.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithCaseDeploymentId.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithCasePrefixId.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithLpadPrefixIdExpression.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithNoSequenceCorrelationKey.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithRpadPrefixIdExpression.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithTruncatePrefixIdExpression.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/case-id-generator/src/main/resources/org/kie/server/testing/EmptyCaseWithUpperPrefixIdExpression.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseIdGeneratorIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/src/main/java/org/kie/server/generator/CustomCaseIdExpressionFunctions.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/src/main/java/org/kie/server/generator/CustomNumberPrefixCaseIdGenerator.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/src/test/filtered-resources/kjars-sources/case-insurance/src/main/resources/org/kie/server/testing/EmptyCaseIdExpressionPrefixVariableLowerCapitalize.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/src/test/java/org/kie/server/integrationtests/generator/CaseIdBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/src/test/java/org/kie/server/integrationtests/generator/CustomCaseIdIntegrationTest.java

Backporting [droolsjbpm-integration#2149](https://github.com/kiegroup/droolsjbpm-integration/pull/2149) to 7.39.x

[7.39.x] [JBPM-9094] Integration tests for new customCaseIdPrefix ability

---

camel-container-tests/camel-container-integration-tests/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml
kie-server-parent/kie-server-tests/pom.xml
process-migration-service/pom.xml

https://issues.redhat.com/browse/JBPM-9227
Parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1390

JBPM-9227: update wildfly 19.x cargo container

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/MarshallingFormat.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/MarshallingFormatTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/QueryServiceRestOnlyIntegrationTest.java

[JBPM-9225] Wrong HTTP media type separator used in Kie server

---

kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/CaseServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/CaseServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseAdminResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseQueryResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/main/java/org/kie/server/remote/rest/casemgmt/CaseResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/test/java/org/kie/server/remote/rest/casemgmt/CaseQueryResourceTest.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/CaseManagementRuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

Depends on [jbpm:1697](https://github.com/kiegroup/jbpm/pull/1697)
Adding new "withData" flag to CaseAdminResource.getCaseInstances. Whenthis flag is true, caseFile information will be include in the response items

[JBPM-9223] include case file

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/exception-handling/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/exception-handling/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/exception-handling/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/exception-handling/src/main/resources/ScriptChildProcess.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/exception-handling/src/main/resources/ScriptMainProcess.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/exception-handling/src/main/resources/WorkDefinitions.wid
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ExceptionHandlingIntegrationTest.java

[JBPM-9184] Subprocess excepcion handling tx rollback causes main process to fail

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/admin/EmailNotification.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/admin/TaskNotification.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/docs/ParameterSamples.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/UserTaskAdminServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/jpa/META-INF/persistence.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/UserTaskAdminServiceIntegrationTest.java

Added logic for integration notifications.

[JBPM-9197] Allow the introduction of emails in Tasks notifications

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/query-definition-project/src/main/resources/query-definitions.json
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

[JBPM-9237] Test queries with columns 'PROCESS_INST_ID', 'ACTIVITY_ID'

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/resources/META-INF/jbpm-persistence.xml

Fixing leftover from https://github.com/kiegroup/droolsjbpm-integration/pull/2168

[JBPM-9197] Add EmailImpl into SpringBoot persistence xml

---

kie-server-parent/kie-server-api/src/test/resources/FunctionDefinition.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/filtered-resources/kjars-sources/decision-project/src/main/resources/0020-vacation-days.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/filtered-resources/kjars-sources/function-definition/src/main/resources/FunctionDefinition.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-scenario-simulation/src/test/filtered-resources/kjars-sources/input-data-string/src/main/resources/input-data-string.dmn

DROOLS-5565 Review remaining kie-server-parent DMN examples version in..

---

camel-container-tests/camel-container-integration-tests/pom.xml
kie-server-parent/kie-server-controller/kie-server-controller-standalone/pom.xml
kie-server-parent/kie-server-tests/pom.xml
process-migration-service/pom.xml

(cherry picked from commit 9ba0d252cdff31c193df80e37795ad8f5627fb6d)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1437
* https://github.com/kiegroup/jbpm/pull/1728
* https://github.com/kiegroup/droolsjbpm-integration/pull/2195
* https://github.com/kiegroup/jbpm-wb/pull/1453
* https://github.com/kiegroup/kie-wb-distributions/pull/1051
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex …

JBPM-9227: update wildfly 19.x cargo container (#2150)

---

kie-maven-plugin/pom.xml
kie-maven-plugin/src/main/java/org/kie/maven/plugin/ArtifactItem.java
kie-maven-plugin/src/main/java/org/kie/maven/plugin/PackageKjarDependenciesMojo.java
kie-maven-plugin/src/main/resources/META-INF/plexus/components.xml
kie-plugins-testing/pom.xml
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/ContainerManager.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/InmutableContainerStartupStrategy.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerScannerEventListener.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/storage/memory/InMemoryKieServerStateRepository.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/resources/META-INF/services/org.kie.server.services.api.StartupStrategy
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/AbstractKieServerImplTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplInitTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/KieServerImplOperationTest.java
kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/DroolsKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/ImmutableSpringBootKieServerImpl.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/InmutableSpringBootKieContainerInstanceImpl.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/SpringBootKieServerImpl.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerProperties.java
kie-takari-plugin/pom.xml

Jira
https://issues.redhat.com/browse/JBPM-9178

[JBPM-9178] Immutable SpringBoot Deployment

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/services/SpringRegisterableItemsFactory.java

Jira:
https://issues.redhat.com/browse/JBPM-9308

[JBPM-9308] EventEmitter is not working in spring boot

---

drools-ha/ha-core-infra/src/main/java/org/kie/hacep/core/infra/election/LeaderElectionImpl.java
jbpm-simulation/src/main/java/org/jbpm/simulation/converter/SimulationFilterPathFormatConverter.java
jbpm-simulation/src/main/java/org/jbpm/simulation/impl/JBPMBAMSimulationDataProvider.java

Kie Server uses obselete/to be deleted Java APIs
Automated updates to Java9
https://j2eeguys.com/updater/index.html

DROOLS-5578: Kie Server uses obselete/to be deleted Java APIs

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/DeadlinesNotificationTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/TestAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/events/listeners/CountDownLatchNotificationListener.java

**JIRA**:  [JBPM-9317](https://issues.redhat.com/browse/JBPM-9317)
Added springboot test for checking saveContent accesibility during deadline notification

[JBPM-9317] Add test for springboot userTaskService.saveContent

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java

Change exists to exist and put the space after the question mark
* link 2
* link 3 etc.
<pre>
How to retest a PR or trigger a specific build: …

Update warning messages

---

camel-container-tests/camel-container-integration-tests/pom.xml
camel-container-tests/camel-container-tests-module/src/main/webapp/WEB-INF/camel-context.xml

**JIRA**:
Related to [https://issues.redhat.com/browse/RHPAM-3128](https://issues.redhat.com/browse/RHPAM-3128)
<pre>
How to retest a PR or trigger a specific build:
</pre>

2 EAP instances test for Fuse integration

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/JACCIdentityProvider.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/security/JACCIdentityProviderWildFlyTomcatTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/main/java/org/jbpm/notification/listeners/CustomNotificationListener.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/main/resources/META-INF/services/org.jbpm.services.task.deadlines.NotificationListener
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/notification-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/notification-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/notification-project/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/notification-project/src/main/resources/notification.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/NotificationSaveContentIntegrationTest.java

**JIRA**: [JBPM-9331](https://issues.redhat.com/browse/JBPM-9331)

[JBPM-9331] JACCIdentityProvider must support contextUsers

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KieServerMigrationTest.java

In original migration test, abort process was always performed over target containerId, but if for some reason migration fail, instance will still be open over original container id. Exception were rearranged, so if problem occurs again, original exception will not be hidden by abort one.
**JIRA**:
[JBPM-9325](https://issues.redhat.com/browse/JBPM-9325)

[JBPM-9325] Unstable KIE-SERVER SpringBoot test

---

drools-ha/pom.xml

**JIRA**:
[https://issues.redhat.com/browse/RHPAM-3142](https://issues.redhat.com/browse/RHPAM-3142)
adding Maven pom.xml schema declaration

RHPAM-3142: fixed pom.xml project element

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-case-id-generator/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/pom.xml

**JIRA**: [JBPM-9333](https://issues.redhat.com/browse/JBPM-9333)

[JBPM-9333] Integ tests should unzip kie-server war files per profile

---

kie-osgi/kie-karaf-itests/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
kie-spring-boot/pom.xml

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-846 
parent PR https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1456
<pre>
How to retest a PR or trigger a specific build:
</pre>

BXMSPROD-846: upgrade of cxf-core to 3.2.14

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/ProcessServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/ProcessServiceBaseTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java

Throw exception when container id associated with that process id does
not match the container id specified in the request
**JIRA**:
[JBPM-9206](https://issues.redhat.com/browse/JBPM-9206)

[JBPM-9206] container id should be checked when retrieving process

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/KafkaBaseTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/KafkaFixture.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/KafkaProxySampleTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/KafkaSampleTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/KafkaSerializationTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/entities/Box.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/events/listeners/CountDownLatchEventListener.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/serialization/BoxDeserializer.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/utils/KieJarBuildHelper.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/application-test.properties
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/src/main/java/com/myspace/kafka_process/Box.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/src/main/java/com/myspace/kafka_process/BoxSerializer.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/src/main/resources/META-INF/kmodule.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/src/main/resources/META-INF/persistence.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka-process.bpmn
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/kjars/kafka-process/src/main/resources/com/myspace/kafka_process/kafka_flow.bpmn
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/templates/kie-deployment-descriptor.template

**JIRA**: [JBPM-9357](https://issues.redhat.com/browse/JBPM-9357)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1466

[JBPM-9357] Add springboot Kafka WIH tests

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java

**JIRA**:  [JBPM-9394](https://issues.redhat.com/browse/JBPM-9394)

[JBPM-9394] Fix typo at KIE_SERVER_NOTIFY_UPDATES_TO_CONTROLLERS

---

kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/pom.xml
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/pom.xml
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/java/org/kie/integration/testcoverage/instrumentation/model/Cat.java
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/java/org/kie/integration/testcoverage/instrumentation/model/Dog.java
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/java/org/kie/integration/testcoverage/instrumentation/model/Person.java
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/java/org/kie/integration/testcoverage/instrumentation/model/Pet.java
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/resources/META-INF/kmodule.xml
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/src/main/resources/org/kie/integration/testcoverage/instrumentation/rules.drl
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/pom.xml
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/test-suite/pom.xml
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/test-suite/src/test/filtered-resources/test-kie-maven-settings.xml
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/test-suite/src/test/filtered-resources/test.properties
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/InstrumentationTest.java
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/test-suite/src/test/java/org/kie/integration/testcoverage/instrumentation/TestUtil.java
kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/test-suite/src/test/resources/logback-test.xml
kie-integration-test-coverage/pom.xml

**JIRA**:  https://issues.redhat.com/browse/DROOLS-5663
pending for https://github.com/kiegroup/droolsjbpm-integration/pull/2247 to merge
then will rebase,
skip 985a295
and submit only 4fdfa93
<details>
<summary>
</summary>
</details>

DROOLS-5663 additional test suite only for default=exec model

---

kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManager.java

Move changes in separate branch: https://github.com/kiegroup/droolsjbpm-integration/pull/2254

Fix NPE on KieSpringTransactionManager#begin

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java

**JIRA**: [JBPM-9429](https://issues.redhat.com/browse/JBPM-9429)
<details>
<summary>
</summary>
</details>

JBPM-9429 - DocumentCollection doesn't work in generated forms

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieContainerCommandServiceImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/util/KieServerUtils.java
kie-server-parent/kie-server-services/kie-server-services-drools/src/main/java/org/kie/server/services/drools/RulesExecutionService.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/filtered-resources/kjars-sources/stateless-session-kjar/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/StatefulSessionUsageIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-drools/src/test/java/org/kie/server/integrationtests/drools/StatelessSessionUsageIntegrationTest.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-996
<details>
<summary>
</summary>
</details>

[DROOLS-996] Default Stateless Session in Kie Server

---

.github/workflows/pull_request.yml

<details>
<summary>
</summary>
</details>

pull request flow free disk space step

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java

Jira:
https://issues.redhat.com/browse/JBPM-9447

[JBPM-9447] No session found for context in case SLA on user task is violated

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/AbstractKieServerImplTest.java

**JIRA**: _(https://issues.redhat.com/browse/JBPM-9435)_

[JBPM-9435] /server/state REST endpoint prints kie server user and controller user/password in clear text

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

[link](https://issues.redhat.com/browse/JBPM-9273)
* link 2
* link 3 etc.
<pre>
How to retest a PR or trigger a specific build:
</pre>

JBPM-9273 System error occurred while adding deployment unit

---

kie-camel/src/main/java/org/kie/camel/embedded/dmn/DMNEvaluateAllLocalBatchCommand.java
kie-camel/src/main/java/org/kie/camel/embedded/dmn/DecisionsToHeadersProcessor.java
kie-camel/src/main/java/org/kie/camel/embedded/dmn/ToDMNEvaluateAllCommandProcessor.java
kie-camel/src/main/java/org/kie/camel/embedded/dmn/ToMapProcessor.java
kie-camel/src/test/java/org/kie/camel/embedded/camel/component/KieEmbeddedEndpointDMNTest.java
kie-camel/src/test/resources/dmn/canDrink.dmn
kie-camel/src/test/resources/logback-test.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-5756
**referenced Pull Requests**: none
<details>
<summary>
</summary>
</details>

DROOLS-5756 DMN kie-camel local/embedded execution capability and demo

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-starters/jbpm-spring-boot-starter-basic/pom.xml

**JIRA**: [JBPM-9453](https://issues.redhat.com/browse/JBPM-9453)

[JBPM-9453] Exclusions at spring-boot-starter-test after junit bumped to 4.13.1

---

kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerRestImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/main/java/org/kie/server/remote/rest/jbpm/ui/FormResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/swagger/SwaggerIntegrationTest.java

**JIRA**: [JBPM-9410](https://issues.redhat.com/browse/JBPM-9410)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1510
Added a test for checking if all get/post methods contain schema inside successful responses.
Fixed missing methods detected when adding the test.

[JBPM-9410] Add Swagger test and fix missing methods

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/services/SpringKModuleDeploymentService.java

Jira: https://issues.redhat.com/browse/JBPM-9407
Overwrite for spring boot for adding custom entity managers
depends on:
https://github.com/kiegroup/jbpm/pull/1769

[JBPM-9407] Spring Boot - Multiple Data Sources and Pluggable Variable Persistence

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-kafka/.gitignore
kie-server-parent/kie-server-services/kie-server-services-kafka/pom.xml
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/CloudEvent.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/resources/META-INF/services/org.kie.server.services.api.KieServerExtension
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/CloudEventTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/resources/logback-test.xml
kie-server-parent/kie-server-services/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-wars/kie-server/pom.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee8-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-servlet-container.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/java/org/kie/server/springboot/autoconfiguration/jbpm/KafkaKieServerAutoConfiguration.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/resources/META-INF/spring.factories

Implementing Kafka server extension 
**JIRA**: 
[JBPM-9436](https://issues.redhat.com/browse/JBPM-9436)
Depends on: 
[#drools-build-bootstrap:1502](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1502) and [#jbpm:1785](https://github.com/kiegroup/jbpm/pull/1785)

[JBPM-9436] AMQ Streams (Kafka) listener functionality / consumer

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java

Correct server state cherry pick

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/util/QueryParamFactory.java

Jira : https://issues.redhat.com/browse/JBPM-9461
depends on https://github.com/kiegroup/jbpm/pull/1800

[JBPM-9461] Add a flag/switch to include or exclude process variables

---

kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/ProcessServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/ProcessServiceBaseTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java

issue: https://issues.redhat.com/browse/JBPM-9488

[JBPM-9408] revert as container alias does not work

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/CloudEvent.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/CloudEventTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionConsumerTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionProducerTest.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/java/org/kie/server/springboot/autoconfiguration/jbpm/KafkaKieServerAutoConfiguration.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/java/org/kie/server/springboot/autoconfiguration/jbpm/extensions/SpringBootKakfaServerExtension.java

Modifying kafka server extension to publish events
**JIRA**: 
[JBPM-9474](https://issues.redhat.com/browse/JBPM-9474)
**depends on**: 
https://github.com/kiegroup/droolsjbpm-knowledge/pull/486
https://github.com/kiegroup/jbpm/pull/1808
https://github.com/kiegroup/drools/pull/3264

[JBPM-9474] Produce events to Kafka by Signal or Messages Events

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/.gitignore
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/ClusteredJobFailOverListener.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/EJBCacheInitializer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/JBPMClusterKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/ReoccurringLongPrintOutCommand.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/resources/META-INF/kie.conf
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/resources/META-INF/services/org.kie.server.services.api.KieServerExtension
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/test/resources/default-jgroups-udp.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/test/resources/infinispan.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/test/resources/log4j.properties
kie-server-parent/kie-server-services/pom.xml

Jira: https://issues.redhat.com/browse/JBPM-9399
depends on:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1521
https://github.com/kiegroup/droolsjbpm-knowledge/pull/468
https://github.com/kiegroup/jbpm/pull/1765

[JBPM-9399] Add support to jBPM and runtime/cluster environments detection

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionConsumerTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionProducerTest.java

Using new addProcessListener API to register the processEventListener
**JIRA**: 
[JBPM-9504](https://issues.redhat.com/browse/JBPM-9504)
https://github.com/kiegroup/droolsjbpm-knowledge/pull/489
https://github.com/kiegroup/jbpm/pull/1818

[JBPM-9504] Exception on unDeploy at KafkaServerExtension

---

kie-maven-plugin/src/it/kie-pmml-trusty-integration-tests/pom.xml

@danielezonca @mariofusco @jiripetrlik

Removing "pom" type definition for kie-pmml-dependencies

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/BuildMojo.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-5865

[DROOLS-5865] exclude test classes from kie-maven-plugin build

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

https://issues.redhat.com/browse/JBPM-9273
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

Revert "JBPM-9273 System error occurred while adding deployment unit"

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

…(#2329)"
This reverts commit c7efcee942c3c1814ae503db69b293b983d26991.
[JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
* …

Revert "JBPM-9273 System error occurred while adding deployment unit (#2329)"

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/resources/kjars/user-task-case/pom.xml

Seems to contain accidentally copied code.
* fixing https://github.com/kiegroup/droolsjbpm-integration/pull/2313
<details>
<summary>
</summary>
</details>

[JBPM-9457] Fix user-task-case pom file

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/resources/kjars/user-task-case/pom.xml

Cherrypick of https://github.com/kiegroup/droolsjbpm-integration/pull/2350
Seems to contain accidentally copied code.
fixing #2313
<details>
<summary>
</summary>
</details>

[7.48.x] [JBPM-9457] Fix user-task-case pom file

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

This reverts commit d62f583c7a86933b5d9dba0b68e1d54a77825a16.
**JIRA**: 
[JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)
* https://github.com/kiegroup/kie-wb-common/pull/3533
<details>
<summary>
</summary> …

[7.48.x]Revert "JBPM-9273 System error occurred while adding deployment unit"

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/kjars/alt-project/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/kjars/send-project/pom.xml
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/kjars/signalling-project/pom.xml

<details>
<summary>
</summary>
</details>

Fix Kie server SpringBoot samples

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml

locally passing with local Fuse
**JIRA**: https://issues.redhat.com/browse/RHPAM-3382
**referenced Pull Requests**: none
<details>
<summary>
</summary>
</details>

RHPAM-3382 It is not possible to create DMN runtime in OSGI environment

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaProducerHappyPathTest.java

**[JBPM-9553](https://issues.redhat.com/browse/JBPM-9553)**
* link 2
* link 3 etc.
<details>
<summary>
</summary>
</details>

[JBPM-9553] - KieServerTest failing after adding Kafka tests

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterBrokerDownTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/ProxyAwareKafkaEmitterTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaProducerHappyPathTest.java

**JIRA**:  [JBPM-9552](https://issues.redhat.com/browse/JBPM-9552)

[JBPM-9552] Disable testcontainers tests on windows and rhel8

---

kie-spring-boot/kie-spring-boot-samples/.gitignore
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/README.md
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KeycloakKieServerTest.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakContainer.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakFixture.java

**JIRA**: [JBPM-9557](https://issues.redhat.com/browse/JBPM-9557)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1567

[JBPM-9557] Enable sb keycloak test with testcontainers

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterBrokerDownTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/ProxyAwareKafkaEmitterTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaConsumerHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaProducerHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/resources/logback-test.xml

**JIRA**: [JBPM-9567](https://issues.redhat.com/browse/JBPM-9567)

[JBPM-9567] Stabilize Kafka Consumer/Producer tests

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter/pom.xml

Jira https://issues.redhat.com/browse/JBPM-9549
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1565

[JBPM-9549] Upgrade SpringBoot to 2.3.4

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakIdentityProvider.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakVariableGuardProcessEventListener.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/resources/application.properties
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KeycloakKieServerTest.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakContainer.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakFixture.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakSampleConstants.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KieJarBuildHelper.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/resources/kjars/keycloak-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/resources/kjars/keycloak-sample/src/main/resources/HumanTaskWithRestrictedVar.bpmn
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/resources/kjars/keycloak-sample/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/resources/kjars/keycloak-sample/src/main/resources/META-INF/kmodule.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/resources/kjars/keycloak-sample/src/main/resources/evaluation.bpmn2

**JIRA**: [JBPM-9564](https://issues.redhat.com/browse/JBPM-9564)

[JBPM-9564] Add tests with restricted variable tag and keycloak

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/Marshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/CloudEvent.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/CloudEventReader.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/CloudEventWriter.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/DefaultEventProcessorFactory.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaEventProcessorFactory.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaEventReader.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaEventWriter.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaJsonUtils.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerEventProcessor.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerProducer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerUtils.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/RawJsonEventReader.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/RawJsonEventWriter.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/CloudEventTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/JavaSerializationEventProcessorFactory.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaEventWriterReaderTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionConsumerTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionProducerTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/Person.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaConsumerHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java

Refactoring into several classes
Adding possibility of supporting more message formats that are not cloud events. 
**JIRA**: 
[JBPM-9541](https://issues.redhat.com/browse/JBPM-9541)

[JBPM-9541] Kafka extension to support custom format

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml
kie-spring-boot/kie-spring-boot-starters/kie-server-spring-boot-starter/pom.xml

This reverts commit e46d9d4975ae60f115fe3c93ba3a38950ac3d309.
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1579
https://github.com/kiegroup/droolsjbpm-integration/pull/2383
https://github.com/kiegroup/jbpm-work-items/pull/172
<details>
<summary>
</summary>
* <b>a full …

Revert "[JBPM-9549] Upgrade SpringBoot to 2.3.4 (#2370)"

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/CloudEventWriter.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/DefaultEventProcessorFactory.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaEventProcessorFactory.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaEventReader.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaEventWriter.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerUtils.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaEventWriterReaderTest.java

Add property
Add Missing javadoc
Fix leak in default factory implementation
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9574)

[JBPM-9574] property to change  kafka reader&writer for all topics

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ContainerInfo.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigurationMarshaller.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java

This reverts commit 59f3ef9.
Jira https://issues.redhat.com/browse/RHPAM-3419

Revert "[JBPM-9423] Duplicate container-info entries in kie-server-router.json file if we create containers with unique container-alias"

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakContainer.java

**JIRA**: [JBPM-9573](https://issues.redhat.com/browse/JBPM-9573)

[JBPM-9573] Keycloak image not found in tests

---

.github/workflows/pull_request.yml

https://issues.redhat.com/browse/BXMSPROD-1202
- https://github.com/kiegroup/optaweb-employee-rostering/pull/560
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/421
- https://github.com/kiegroup/kie-wb-distributions/pull/1083
- https://github.com/kiegroup/droolsjbpm-integration/pull/2392
- https://github.com/kiegroup/optaweb-employee-rostering/pull/561
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/422
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add …

BXMSPROD-1202 ubuntu-latest to ubuntu-18.04

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/src/main/java/org/kie/server/spring/boot/autoconfiguration/audit/replication/AuditDataReplicationProcessEventProducer.java

Jira: https://issues.redhat.com/browse/JBPM-9530

[JBPM-9530] AuditDataReplicationPEP.slaProcessInstanceViolated and slaNodeInstanceViolated swap the EventType semantic

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceIntegrationTest.java

Integration test
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9579)
https://github.com/kiegroup/droolsjbpm-knowledge/pull/499
https://github.com/kiegroup/jbpm/pull/1853

[JBPM-9579] Adding a pagination parameter to LogCleanupCommand

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/KieServerInstanceManager.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/KieServerInstanceManagerTest.java

[JBPM-9273](https://issues.redhat.com/browse/JBPM-9273)
* https://github.com/kiegroup/kie-wb-common/pull/3548
<details>
<summary>
</summary> …

[7.48.x]JBPM-9273 System error occurred while adding deployment unit

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakContainer.java

**JIRA**: [JBPM-9618](https://issues.redhat.com/browse/JBPM-9618)

[JBPM-9618] Filter list images deprecated from docker 20.10

---

kie-server-parent/kie-server-controller/kie-server-controller-impl/src/main/java/org/kie/server/controller/impl/service/SpecManagementServiceImpl.java
kie-server-parent/kie-server-controller/kie-server-controller-impl/src/test/java/org/kie/server/controller/impl/service/SpecManagementServiceImplTest.java

**JIRA**: _(https://issues.redhat.com/browse/RHPAM-3362)_

[RHPAM-3362] Business-central REST API is allowing container creation with empty container id

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/JbpmRestApplicationComponentsService.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/ProcessAdminResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/java/org/kie/server/springboot/autoconfiguration/jbpm/extensions/SpringBootJBPMKieServerExtension.java

Jira https://issues.redhat.com/browse/JBPM-9583
depends on https://github.com/kiegroup/jbpm/pull/1854

[JBPM-9583] Enhance migration service to check parent/sub-process relations

---

kie-server-parent/kie-server-tests/pom.xml

<details>
<summary>
</summary>
</details>

Fix Kie server integration test database profiles

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KeycloakKieServerTest.java

**JIRA**: [JBPM-9634](https://issues.redhat.com/browse/JBPM-9634)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1603

[JBPM-9634] Upgrade testcontainers to 1.15.2

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KeycloakKieServerTest.java

**JIRA**: [JBPM-9658](https://issues.redhat.com/browse/JBPM-9658)

[JBPM-9658] Fix NPE in keycloak test when no docker available

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-dmn/src/main/java/org/kie/server/services/dmn/modelspecific/OASGenerator.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-6085
**referenced Pull Requests**: none
<details>
<summary>
</summary>
</details>

DROOLS-6085 DMN fix OAS server default url when embedded as Spring Boot

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/variables.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JbpmKieServerBaseIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java

Integration test
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9641)
https://github.com/kiegroup/jbpm/pull/1890

[JBPM-9641] Convert process variable to right data type

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/CustomNotificationListenerTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/DeadlinesNotificationTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/JMXQuartzSchedulerTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/TimerInProcessMigrationTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/TimerProcessTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaConsumerHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaProducerHappyPathTest.java

**JIRA**: [JBPM-9580](https://issues.redhat.com/browse/JBPM-9580)

[JBPM-9580] Stabilize CustomNotificationListenerTest

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/admin/MigrationProcessSpecification.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/admin/MigrationSpecification.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/ProcessAdminServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/impl/ProcessAdminServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/admin/ProcessAdminResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/docs/ParameterSamples.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/admin/ProcessAdminServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/parentCallingMultipleSubProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/parentWithIndependentSubProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/parentWithNonIndepententSubProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/subprocess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project-101/src/main/resources/subprocessCallingAnotherSubprocess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/parentCallingMultipleSubProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/parentWithIndependentSubProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/parentWithNonIndepententSubProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/subprocess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/subprocessCallingAnotherSubprocess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/ProcessInstanceMigrationIntegrationTest.java

Jira : https://issues.redhat.com/browse/JBPM-9654

[JBPM-9654] Migration of all subprocess of a parent process fails

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/ProcessServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/ProcessServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/ProcessResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/StartProcessServiceIntegrationTest.java

depends on https://github.com/kiegroup/jbpm/pull/1904

rename sync process api

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java

**JIRA**: https://issues.redhat.com/browse/DROOLS-6256

remove flow dsl from executable model

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/travelAgencyWrappedParamsProcess.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceWrappedParamsIntegrationTest.java

**JIRA**: [JBPM-9682](https://issues.redhat.com/browse/JBPM-9682)

[JBPM-9682] Add test for webservice call with wrapped params

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KieServerMigrationTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KieServerTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/RulesOnlyKieServerTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/TaskAssigningKieServerTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/rest/KieServerWithExtraEndpointTest.java

**[JBPM-9648](https://issues.redhat.com/browse/JBPM-9648)**: Improve some flaky tests around Spring boot projects in droolsjbpm-integration repo
<details>
<summary>
</summary>
</details>

[JBPM-9648] Improve some flaky tests around Spring boot projects in droolsjbpm-integration repo

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseUserTaskWithVariables.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/ProcessInstanceUserTaskWithVariables.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java

**JIRA**: 
[https://issues.redhat.com/browse/JBPM-9684](https://issues.redhat.com/browse/JBPM-9684)
* https://github.com/kiegroup/jbpm/pull/1903
Add task description to `ProcessInstanceUserTaskWithVariables` POJO and mapping

[JBPM-9684] Add task description mapping

---

kie-camel/src/test/java/org/kie/camel/embedded/camel/component/CamelEndpointWithMarshallersTest.java
kie-camel/src/test/java/org/kie/camel/embedded/camel/component/XStreamBatchExecutionTest.java

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6282
<details>
<summary>
</summary>
</details>

[DROOLS-6282] Fix ForbiddenClassException in kie-camel tests

---

kie-camel/src/test/java/org/kie/camel/embedded/camel/component/CamelEndpointWithMarshallersTest.java
kie-camel/src/test/java/org/kie/camel/embedded/camel/component/XStreamBatchExecutionTest.java

**JIRA**: 
https://issues.redhat.com/browse/RHDM-1703
backport of DROOLS-6282
<details>
<summary>
</summary>
</details>

[7.52.x] [DROOLS-6282] Fix ForbiddenClassException in kie-camel tests (#2456)

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GeneratePMMLModelMojo.java

@danielezonca @kostola @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-6274

[DROOLS-6274] Fixing resource filtering

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GeneratePMMLModelMojo.java

@danielezonca @kostola @jiripetrlik

[7.52.x][DROOLS-6274] Fixing resource filtering

---

kie-maven-plugin/IntegrationTests.md
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/src/test/java-filtered/org/kie/maven/plugin/ittests/BuildPMMLTrustyTestIT.java

@danielezonca @kostola  @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-6275
Depends on https://github.com/kiegroup/drools/pull/3538

[DROOLS-6275] Fixing BuildPMMLTrustyTestIT.

---

kie-maven-plugin/IntegrationTests.md
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/src/test/java-filtered/org/kie/maven/plugin/ittests/BuildPMMLTrustyTestIT.java

@danielezonca @kostola @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-6275
Depends on kiegroup/drools#3539

[7.52.x][DROOLS-6275] Fixing BuildPMMLTrustyTestIT.

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/cases/CaseUserTaskWithVariables.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/instance/ProcessInstanceUserTaskWithVariables.java
kie-server-parent/kie-server-services/kie-server-services-case-mgmt/src/main/java/org/kie/server/services/casemgmt/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java

**JIRA**: 
[https://issues.redhat.com/browse/RHPAM-3584](https://issues.redhat.com/browse/RHPAM-3584)
* https://github.com/kiegroup/jbpm/pull/1913
* https://github.com/kiegroup/droolsjbpm-integration/pull/2440 (cherry-pick)
backport for 7.52.x

(GSS) [7.11.1] [RHPAM-3584] Add task description mapping

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/ProcessDefinition.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormRendererBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/js/kieserver-ui.js
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/FormRendererBaseTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/DefinitionServiceBase.java

* Added "required" and "readonly" property to FormField by tags
* Fixed validation for input box in ProcessInstance form
**JIRA**: 
[AF-2811](https://issues.redhat.com/browse/AF-2811)
[RHPAM-3047](https://issues.redhat.com/browse/RHPAM-3047)
**Referenced Pull Requests**:
* https://github.com/kiegroup/kie-wb-common/pull/3592
* https://github.com/kiegroup/jbpm-wb/pull/1484
<details>
<summary>
</summary>
* <b>an upstream …

AF-2811: Required Process Variable Tags shouldn't be accepted in forms when empty

---

kie-maven-plugin/IntegrationTests.md
kie-maven-plugin/pom.xml

@danielezonca @mariofusco @jiripetrlik

[DROOLS-6338] Add documentation about invoker-test skipping

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-100/src/main/resources/air-conditioning-control.dmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/filtered-resources/kjars-sources/import-itemdef-101/src/main/resources/air-conditioning-control.dmn

**JIRA**: https://issues.redhat.com/browse/DROOLS-6335
**referenced Pull Requests**: none
<details>
<summary>
</summary>
</details>

DROOLS-6335 DMN amend wording in examples -integration

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaConsumerHappyPathTest.java

**JIRA**: [JBPM-9734](https://issues.redhat.com/browse/JBPM-9734)

[7.52.x][JBPM-9734] KafkaConsumerHappyPathTest flaky tests

---

.github/workflows/pull_request.yml

**JIRA**:
https://issues.redhat.com/browse/BXMSPROD-1342
**referenced Pull Requests**: https://github.com/kiegroup/droolsjbpm-integration/pull/2485
<details>
<summary>
</summary>
</details>

[BXMSPROD-1342][7.52.x] Free disk space new approach

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/KafkaConsumerHappyPathTest.java

**JIRA**: [JBPM-9734](https://issues.redhat.com/browse/JBPM-9734)
Cherry-pick from 95dc6a7c589109a5c231e32a5cc68063296be423

[JBPM-9734] KafkaConsumerHappyPathTest flaky tests

---

jbpm-process-svg/src/main/java/org/jbpm/process/svg/processor/StunnerSVGProcessor.java

… map in the SVG file which is returned by url /server/containers/{containerId}/images/processes/{processId}
-- make the PR can compatible with the old svg file
[RHPAM-3655](https://issues.redhat.com/browse/RHPAM-3655)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
* <b>a full …

JBPM-9708 Allow navigation from the parent process instance to the child process instance using Process Diagram

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java

Jira: https://issues.redhat.com/browse/JBPM-9784

[JBPM-9784] Fieldname Case Unexpected Modification

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java

https://github.com/kiegroup/drools/pull/3660
<details>
<summary>
</summary>
</details>

DO-NOT-SQUASH Port of Executable Model 7.11.1 RHDMs 

---

kie-spring-boot/pom.xml

Jira: https://issues.redhat.com/browse/JBPM-9785

[JBPM-9785] narayana starter version mismatch after upgrading springboot to 2.4.3

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ByPassUserTaskServiceIntegrationTest.java

**[JBPM-9764](https://issues.redhat.com/browse/JBPM-9764)**: Test is missing for fix in RHPAM-3712 (empty user when bypass is set)

[JBPM-9764] Test is missing for fix in RHPAM-3712 (empty user when bypass is set)

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

Jira: https://issues.redhat.com/browse/JBPM-9783
dmn was incorrectly updated in last commit.
depends on https://github.com/kiegroup/jbpm/pull/1953

[JBPM-9783] Incorrect object type returned in a DMN business-rule task of a BPMN (RuleSetNode Instance)

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/ProxyAwareKafkaEmitterTest.java

**JIRA**: [JBPM-9716](https://issues.redhat.com/browse/JBPM-9716)
* https://github.com/kiegroup/jbpm/pull/1925
* https://github.com/kiegroup/kie-docs/pull/3501

[JBPM-9716] Wrong bootstrap servers property in the Kafka Emitter

---

kie-spring-boot/pom.xml

Jira: https://issues.redhat.com/browse/JBPM-9785

[QE] [7.52.x] [JBPM-9785] narayana starter version mismatch after upgrading springboot to 2.4.3

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java

cherry pick https://github.com/kiegroup/droolsjbpm-integration/pull/2513

[GSS] [7.52.x] [JBPM-9784] Fieldname Case Unexpected Modification

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/UserTaskServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/UserTaskServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/UserTaskResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ConvertUtils.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

Adding query param and test
**JIRA**: 
[link](https://github.com/fjtirado/droolsjbpm-integration/pull/new/JBPM-9786)
https://github.com/kiegroup/jbpm/pull/1955

[JBPM-9786] Add REST Endpoint for claiming tasks in bulk

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java

…st if we set BYPASS_AUTH_USER to true
**JIRA**: _(https://issues.redhat.com/browse/RHPAM-3712)_

[7.52.x] [JBPM-9745] The REST API (queries/tasks/instances)returns an empty list if we set BYPASS_AUTH_USER to true

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerProducer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionConsumerTest.java

**JIRA**
https://issues.redhat.com/browse/JBPM-9805

[7.52.X] [JBPM-9805] Fixing NPE on consumer

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerProducer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionConsumerTest.java

Catching throwable rather than exception
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9805)

[JBPM-9805] Fixing NPE on KafkaConsumer

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java

(cherry picked from commit ecdc7cdab48a1f158baf60c43dbf8307f73bd0e9)
**JIRA**: 
[RHPAM-3454](https://issues.redhat.com/browse/RHPAM-3454)
[AF-2860](https://issues.redhat.com/browse/AF-2860)
<details>
<summary>
</summary>
</details>

[7.52.x] AF-2860: Process form renderer for Date objects doesn't submit the correct data (#2501)

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerProcessListener.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerProducer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/resources/META-INF/kafka-deployment-descriptor-defaults.xml
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionProducerTest.java

Switching from programmatic to declarative approach
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9812)

[JBPM-9812] publish events when using singleton runtime strategy

---

kie-maven-plugin/src/main/java/org/kie/maven/plugin/PackageKjarDependenciesMojo.java

Jira: https://issues.redhat.com/browse/JBPM-9829

[JBPM-9829] Spring Boot jar containing kjar and commons-beanutils causes "Could not read pom in jar" error

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouterConstants.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouterEnvironment.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouterResponsesUtil.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/KieServerInfoHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/utils/HttpUtils.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/handlers/KieServerInfoHandlerInvalidPortTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/handlers/KieServerInfoHandlerTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/proxy/aggregate/KieServerProxyClientTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterAuthNoIdPTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterAuthTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterCommandTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterMultiNodeTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterUnavailabilityIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-router/src/test/java/org/kie/server/integrationtests/router/rest/KieServerRouterUnavailabilityRecoveryTest.java

Jira: https://issues.redhat.com/browse/JBPM-9831

[JBPM-9831] Use the encrypted values for the user and/or keystore password when starting smart router

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java

Jira: https://issues.redhat.com/browse/JBPM-9839

[JBPM-9839] synchronize the contents (system properties) from standalone-*.xml with the default-kieserver.xml

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java

* Added input type file check
**JIRA**:
[AF-2881](https://issues.redhat.com/browse/AF-2881)
[RHPAM-3515](https://issues.redhat.com/browse/RHPAM-3515)
<details>
<summary>
</summary>
</details>

AF-2881 : When try to attach a document the upload button is not showing

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/travelAgencyProcessWithHeaders.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersDumbEscapeIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersNoEscapeIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersNoEscapeNoMatchIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/pom.xml
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/AcmeDemoInterfaceImpl.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/HeaderInInterceptor.java

**JIRA**:
[link](https://issues.redhat.com/browse/JBPM-9738)
https://github.com/kiegroup/jbpm/pull/1992

[JBPM-9738] Adding integrations test

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/java/org/kie/server/services/impl/AbstractKieServerImplTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/test/resources/kie-server-impl-test.xml

**JIRA**: [JBPM-9839](https://issues.redhat.com/browse/JBPM-9839)
cherry-pick of bc764acc0b2308b86eb4ae5177739e9656011227

[7.59.x][JBPM-9839] Add unit test and remove completely configItem from state when envValue is null

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNJsonApplicantIntegrationTest.java

Reproducer on kie-server for DROOLS-6571
**JIRA**: https://issues.redhat.com/browse/DROOLS-6571
* https://github.com/kiegroup/drools/pull/3803
<details>
<summary>
</summary>
</details>

DROOLS-6571 reproducer for EvalHelper accessorCache on kie server

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/EventEmitterTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/TestAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/events/emitters/CountDownLatchEmitter.java

**JIRA**: [JBPM-9790](https://issues.redhat.com/browse/JBPM-9790)

[JBPM-9790] Add integration test for emitter admin operations

---

kie-server-parent/kie-server-controller/kie-server-controller-openshift/pom.xml
kie-server-parent/kie-server-services/kie-server-services-openshift/pom.xml

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2581

[7.59.x][JBPM-9872] Banned classes in kie-server-services-openshift artifact

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerWithSystemPropertyTest.java

Jira: https://issues.redhat.com/browse/DROOLS-6592

[DROOLS-6592] Kie Server Marshalling changes Pojo field UpperCase begin and JSON

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerWithSystemPropertyTest.java

Jira: https://issues.redhat.com/browse/DROOLS-6592
backport from https://github.com/kiegroup/droolsjbpm-integration/pull/2599

[7.59.x] [DROOLS-6592] Kie Server Marshalling changes Pojo field UpperCase begin and JSON

---

kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/blueprint/KieBlueprintjBPMPersistenceKarafIntegrationTest.java

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6600
<details>
<summary>
</summary>
</details>

[DROOLS-6600] Raise timeout for KarafIntegrationTest injection

---

kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/src/test/java-filtered/org/kie/maven/plugin/ittests/BuildPMMLTrustyTestIT.java

@danielezonca @kostola @jiripetrlik
See https://issues.redhat.com/browse/DROOLS-6382
Depends on https://github.com/kiegroup/drools/pull/3829

[DROOLS-6382] Switch scorecard/tree default implementations

---

droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-brms-distribution/pom.xml
kie-server-parent/kie-server-tests/pom.xml
kie-spring/pom.xml

Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1768
* https://github.com/kiegroup/jbpm/pull/2016
* https://github.com/kiegroup/drools/pull/3832
* https://github.com/kiegroup/jbpm-work-items/pull/215
* https://github.com/kiegroup/kie-jpmml-integration/pull/64
* https://github.com/kiegroup/optaplanner/pull/1574
* https://github.com/kiegroup/kie-soup/pull/227
* https://github.com/jboss-integration/rhba-installers/pull/92

RHPAM-3897: switch to jboss-transaction-spi-jakarta

---

droolsjbpm-bpms-distribution/pom.xml
droolsjbpm-brms-distribution/pom.xml
kie-server-parent/kie-server-tests/pom.xml
kie-spring/pom.xml

**JIRA**: [RHPAM-3897](https://issues.redhat.com/browse/RHPAM-3897)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1775
* https://github.com/kiegroup/jbpm/pull/2028
* https://github.com/kiegroup/drools/pull/3839
* https://github.com/kiegroup/jbpm-work-items/pull/218
* https://github.com/kiegroup/kie-jpmml-integration/pull/67
* https://github.com/kiegroup/optaplanner/pull/1580
* https://github.com/kiegroup/kie-soup/pull/230
* https://github.com/jboss-integration/rhba-installers/pull/93

[7.59.x] RHPAM-3897: switch to jboss-transaction-spi-jakarta

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java

**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9903)

[JBPM-9903] Adding trace for kafka event

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/ProcessServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/locator/ByContextMappingInfoContainerLocator.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/locator/ByProcessInstanceIdContainerLocator.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/locator/ContainerLocatorFactory.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/locator/ProcessContainerLocator.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/locator/ProcessContainerLocatorProvider.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/locator/ByContextMappingInfoContainerLocatorTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/locator/ByProcessInstanceIdContainerLocatorTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/locator/ContainerLocatorFactoryMock.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/locator/ProcessContainerLocatorProviderTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/resources/META-INF/services/org.kie.server.services.jbpm.locator.ContainerLocatorFactory
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/src/main/java/org/kie/server/springboot/jbpm/ContainerAliasResolver.java

https://issues.redhat.com/browse/JBPM-9859

[JBPM-9859] Use different query in ByProcessInstanceIdContainerLocator

---

kie-server-parent/kie-server-api/pom.xml
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerWithSystemPropertyTest.java

**JIRA**: [JBPM-9906](https://issues.redhat.com/browse/JBPM-9906)

[JBPM-9906] Stabilize JSONMarshallerTest in windows

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerExtensionConsumerTest.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/test/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistrationTest.java

If message or signal is associated with start node, consider that two deployments with the same version are the same one and use the one that is deployed the latest
**JIRA**: 
[link](https://issues.redhat.com/browse/JBPM-9898)
**Referenced pull request**
https://github.com/kiegroup/droolsjbpm-knowledge/pull/552

[JBPM-9898] Container upgrade is not properly handled by Kafka server

---

kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/security/adapters/JMSSecurityAdapter.java

(cherry picked from commit 34f3cd675c3960e60268bef293ec6d778d1ac13e)
**JIRA**:  
[JBPM-9935](https://issues.redhat.com/browse/JBPM-9935)
<details>
<summary>
</summary> …

JBPM-9935 : JMS login is using JAAS to get username and roles

---

jbpm-process-svg/src/test/java/org/jbpm/process/svg/EvalutionSVGTest.java

[https://issues.redhat.com/browse/JBPM-9848](https://issues.redhat.com/browse/JBPM-9848)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
* <b>an upstream build</b> please add …

JBPM-9848 droolsjbpm-integration jbpm-process-svg tests are not executed

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/EventEmitterTest.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/TestAutoConfiguration.java
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/java/org/jbpm/springboot/samples/events/emitters/CountDownLatchEmitter.java

Cherry picked from da78992906a97505c678100ceff51b2f3845d112
**JIRA**: [JBPM-9790](https://issues.redhat.com/browse/JBPM-9790)
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.59.x][JBPM-9790] Add integration test for emitter admin operations

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-controller/src/test/java/org/kie/server/integrationtests/controller/KieControllerSwaggerIntegrationTest.java

[JBPM-9959](https://issues.redhat.com/browse/JBPM-9959)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …

[JBPM-9959] Add Authorization header for controller Swagger UI requests

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapter.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/META-INF/services/org.jbpm.services.task.identity.adapter.UserGroupAdapter
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapterTest.java

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

JBPM-9973: [RHSSO] User with process-admin role cannot see tasks

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/pom.xml
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapter.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/resources/META-INF/services/org.jbpm.services.task.identity.adapter.UserGroupAdapter
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapterTest.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2666
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and …

[7.59.x] JBPM-9973: [RHSSO] User with process-admin role cannot see tasks

---

kie-spring-boot/pom.xml

…
https://issues.redhat.com/browse/RHPAM-4012
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1848
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code …

[RHPAM-4012] exclude jakarta-validation from cxf-spring-boot-starter-jaxrs

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project-101/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project-101/src/main/java/com/self/exceptionhandbpm/CustomWorkItemHandler.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project-101/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project-101/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project-101/src/main/resources/asyncCustomWIH.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project/src/main/resources/META-INF/kmodule.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/async-exec-project/src/main/resources/asyncCustomWIH.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceMigrationIntegrationTest.java

**JIRA**: [JBPM-9970](https://issues.redhat.com/browse/JBPM-9970)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
[build-chain …

[JBPM-9970] Test for Process instance migration does not update command data

---

kie-server-parent/kie-server-services/kie-server-services-prometheus/src/main/java/org/kie/server/services/prometheus/PrometheusKieServerEventListener.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/prometheus/PrometheusIntegrationTest.java

JIRA: https://issues.redhat.com/browse/RHPAM-3784
cherry-picks https://github.com/kiegroup/droolsjbpm-integration/pull/2646

[7.59.x] [RHPAM-3784] Prometheus exporter: KiE Server gives wrong count 

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

**[JBPM-9977](https://issues.redhat.com/browse/JBPM-9977)**: Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task
* https://github.com/kiegroup/jbpm/pull/2079
<details>
<summary>
</summary>
[build-chain …

[JBPM-9977] - Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/FormServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java

**[JBPM-9977](https://issues.redhat.com/browse/JBPM-9977)**:  Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task
* https://github.com/kiegroup/jbpm/pull/2080
<details>
<summary>
</summary> …

[7.59.x][JBPM-9977] - Test case is missing for ticket RHPAM-3778 - Getting potential owners for a case task

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapter.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapterTest.java

Jira: https://issues.redhat.com/browse/JBPM-9987

[JBPM-9987] Incorrect response for REST service when org.kie.server.bypass.auth.user used with JAASUserGroupCallbackImpl

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationManager.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AbstractAggregateHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/ContainersHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/DocumentsHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/JobsHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/OptionsHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/QueriesDataHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/QueriesHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/KieServerProxyClient.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/proxy/aggregate/KieServerProxyClientTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java

Jira https://issues.redhat.com/browse/JBPM-9986

[JBPM-9986] Smart router is sending requested to stopped server in RHPAM 7

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/Configuration.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationManager.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AbstractAggregateHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/AdminHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/ContainersHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/DocumentsHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/JobsHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/OptionsHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/QueriesDataHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/handlers/QueriesHttpHandler.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/proxy/KieServerProxyClient.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/ConfigFileWatcher.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/repository/FileRepository.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/ConfigurationTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/proxy/aggregate/KieServerProxyClientTest.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java

Jira: https://issues.redhat.com/browse/JBPM-9986

[7.59.x] [JBPM-9986] Smart router is sending requested to stopped server in RHPAM 7

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapter.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/security/ElytronUserGroupAdapterTest.java

Jira: https://issues.redhat.com/browse/JBPM-9987

[7.59.x] [JBPM-9987] Incorrect response for REST service when org.kie.server.bypass.auth.user used with JAASUserGroupCallbackImpl

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/timer-project/src/main/resources/timer-rollback.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java

Jira: https://issues.redhat.com/browse/JBPM-9988
depends on https://github.com/kiegroup/jbpm/pull/2083

[JPBM-9988] Boundary timer not triggered after rollback

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/timer-project/src/main/resources/timer-rollback.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java

Jira: https://issues.redhat.com/browse/JBPM-9988
depends on https://github.com/kiegroup/droolsjbpm-integration/pull/2682

[7.59.x] [JPBM-9988] Boundary timer not triggered after rollback

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/FormReader.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/FormRendererTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/various-fields-taskform.json

* [JBPM-9948] Adding Java 8 date classes support in FreeMarker template
* [JBPM-9948] Alternative approach using browser "datetime-local"
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …

[7.59.x] [JBPM-9948] Adding Date classes support in forms (#2653)

---

kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/KeyStoreHelperUtil.java

JIRA: https://issues.redhat.com/browse/DROOLS-6781

[DROOLS-6781] make KeyStoreHelper a singleton

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java

**JIRA**: [JBPM-9995](https://issues.redhat.com/browse/JBPM-9995)
<details>
<summary>
</summary> …

[JBPM-9995] TimerIntegrationTest failure

---

kie-spring-boot/pom.xml

https://issues.redhat.com/browse/RHPAM-4111
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1872
- https://github.com/kiegroup/droolsjbpm-integration/pull/2693
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/641
- https://github.com/kiegroup/optaweb-employee-rostering/pull/755
Closes #2680.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …

[RHPAM-4111]-Certify Spring Boot 2.4.x

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/script/setup.cli
kie-server-parent/kie-server-tests/script/setup.cli

**JIRA**: [JBPM-10000](https://issues.redhat.com/browse/JBPM-10000)
<details>
<summary>
</summary> …

[JBPM-10000] Disable annoying jagger traces in wildfly integration tests

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/EJBCacheInitializer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java

Jira: https://issues.redhat.com/browse/JBPM-9985

[JBPM-9985] ISPN000926 errors caused by ConcurrentModificationException when using ClusteredJobFailOverListener

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/NotificationSaveContentIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskEscalationIntegrationTest.java

**JIRA**: [JBPM-9999](https://issues.redhat.com/browse/JBPM-9999)
<details>
<summary>
</summary> …

[JBPM-9999] Dispose containers in some jbpm integration tests

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java

Jira :https://issues.redhat.com/browse/JBPM-9997

[JBPM-9997] TimerRollbackRegressionIntegrationTest throws PSQLException on PostgreSQL database

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/JobServiceMigrationIntegrationTest.java

**JIRA**: [JBPM-10003](https://issues.redhat.com/browse/JBPM-10003)
<details>
<summary>
</summary> …

[JBPM-10003] Stabilize JobServiceMigrationIntegrationTest

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-dmn/src/test/java/org/kie/server/integrationtests/dmn/DMNJsonApplicantIntegrationTest.java

backport to 7.59.x
**JIRA**:  https://issues.redhat.com/browse/RHDM-1877
* https://github.com/kiegroup/drools/pull/4164
* https://github.com/kiegroup/droolsjbpm-integration/pull/2707
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) …

RHDM-1877 DMN evaluation errors when the same FEEL object-access invocation is used by two kie containers

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/EJBCacheInitializer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java

Jira: https://issues.redhat.com/browse/JBPM-9985

[7.59.x] [JBPM-9985] ISPN000926 errors caused by ConcurrentModificationException when using ClusteredJobFailOverListener

---

kie-spring-boot/pom.xml

**[JBPM-10012](https://issues.redhat.com/browse/JBPM-10012)**: Right Springboot version should be 2.3.10
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1886
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1886
<details>
<summary>
</summary> …

[7.59.x][JBPM-10012] - Right Springboot version should be 2.3.10

---

kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/UserTaskServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/UserTaskServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/UserTaskResource.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

Jira: https://issues.redhat.com/browse/JBPM-10015
depends on https://github.com/kiegroup/jbpm/pull/2100

[JBPM-10015] Allow to set suspendUntil during user task suspend operation as parameter.

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakContainer.java

**[JBPM-10018](https://issues.redhat.com/browse/JBPM-10018)**: Keycloak container tests fail to start-up when using latest tag
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …

[JBPM-10018] - Keycloak container tests fail to start-up when using latest tag

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/script/setup.cli
kie-server-parent/kie-server-tests/script/setup.cli

**JIRA**:  [JBPM-10021](https://issues.redhat.com/browse/JBPM-10021)
<details>
<summary>
</summary> …

[JBPM-10021] Fix integration tests for EAP after JBPM-10000

---

kie-osgi/kie-karaf-features/pom.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-core.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml
kie-osgi/kie-karaf-itests/pom.xml
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/camel/kiecamel/KieCamelRemoteIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/java/org/kie/karaf/itest/kieserver/KieServerClientKarafIntegrationJaxbIntegrationTest.java
kie-osgi/kie-karaf-itests/src/test/resources/META-INF/Taskorm.xml
kie-osgi/kie-karaf-itests/src/test/resources/org.apache.karaf.features.xml
kie-spring/pom.xml

[DROOLS-6842] Adjust Karaf features and test configuration to Camel 2.24.0 and CXF 3.4.x
[DROOLS-6842] Add optional JPA import to kie-spring to fix KieSpringjBPMPersistenceKarafIntegrationTest
[DROOLS-6842][JBPM-9920] Synchronize test-accessible Taskorm.xml with jbpm
[DROOLS-6842][RHPAM-4038] Add required httpcore-osgi bundle to kie-server-client feature
Signed-off-by: Grzegorz Grzybek <gr.grzybek@gmail.com>
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does …

[DROOLS-6842] Fix Karaf integration tests

---

drools-ha/ha-core-infra/pom.xml
drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtilTest.java
drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtils.java
drools-ha/pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-3940
I had to upgrade `scala-collection-compat_2.12:2.3.0` coming from new `kafka:2.8.1` to  `scala-collection-compat_2.12:2.6.0` due to 
```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BanDuplicateClasses failed with message:
Duplicate classes found:
Found in:
org.scala-lang.modules:scala-collection-compat_2.12:jar:2.3.0:test
org.scala-lang:scala-library:jar:2.12.13:test
Duplicate classes:
scala/annotation/nowarn.class
scala/annotation/nowarn$.class
```
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1895
* https://github.com/kiegroup/droolsjbpm-integration/pull/2723
<details> …

RHPAM-3940 kafka version to 2.8.1

---

kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

**JIRA**:
[RHPAM-4201](https://issues.redhat.com/browse/RHPAM-4201)

[7.59.x] [RHPAM-4201] Add httpcore-osgi bundle to kie-server-client features

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java

https://issues.redhat.com/browse/BAPL-2000

Fix empty payload

---

kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/test/java/org/kie/server/springboot/samples/utils/KeycloakContainer.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2713

[7.59.x][JBPM-10018] - Keycloak container tests fail to start-up when using latest tag

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationManager.java
kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/KieServerRouter.java

**JIRA**: [JBPM-10036](https://issues.redhat.com/browse/JBPM-10036)
<details>
<summary>
</summary> …

[JBPM-10036] Exception when removing from CopyOnWriteArrayList

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/main/java/org/kie/server/remote/rest/common/resource/KieServerRestImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/test/java/org/kie/server/remote/rest/common/resource/KieServerRestImplTest.java
kie-server-parent/kie-server-services/kie-server-services-common/src/main/java/org/kie/server/services/impl/KieServerImpl.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/JbpmKieServerExtensionTest.java

Jira: https://issues.redhat.com/browse/JBPM-10040

[JBPM-10040] Cleanup Orphan Process Instances in RHPAM DB

---

drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaFullTopicsTests.java

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6874
7.67.x back-port PR of https://github.com/kiegroup/droolsjbpm-integration/pull/2735
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …

[DROOLS-6874] Investigate flaky HACEP test (#2735)

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/ServiceResponse.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/CountDefinition.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/QueryServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/docs/ParameterSamples.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerIntegrationTest.java

**JIRA**: 
[RHPAM-4028](https://issues.redhat.com/browse/RHPAM-4028)
* https://github.com/kiegroup/process-migration-service/pull/45
* https://github.com/kiegroup/jbpm/pull/2124

[RHPAM-4028] Add countProcessInstances query

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/jaxb/JaxbMarshaller.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/model/definition/CountDefinition.java
kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/main/java/org/kie/server/controller/websocket/client/WebSocketKieServerClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/QueryServicesClient.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/RuntimeDataResource.java
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/main/java/org/kie/server/remote/rest/jbpm/docs/ParameterSamples.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/RuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerIntegrationTest.java

**JIRA**: 
[RHPAM-4028](https://issues.redhat.com/browse/RHPAM-4028)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2741

[7.67.x][RHPAM-4028] Add countProcessInstances query

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/JbpmKieServerExtension.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/JbpmKieServerExtensionTest.java

Jira: https://issues.redhat.com/browse/JBPM-10046

[JBPM-10046] Missing PreUndeployOperations.doNothing call for development mode and no dispose flag

---

kie-server-parent/kie-server-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-api/src/build/revapi-config.json
kie-server-parent/kie-server-controller/kie-server-controller-rest/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-client/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-case-mgmt/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-common/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-dmn/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-drools/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm-ui/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-jbpm/src/build/revapi-config.json
kie-server-parent/kie-server-remote/kie-server-rest/kie-server-rest-optaplanner/src/build/revapi-config.json

**JIRA**: [BAQE-2253](https://issues.redhat.com/browse/BAQE-2253)
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1925
<details>
<summary>
</summary> …

[7.67.x] BAQE-2253 - Change revapi to check against 7.59.0.Final

---

kie-server-parent/kie-server-wars/kie-server/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-drools/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-optaplanner/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-task-assigning-planning/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-task-assigning-runtime/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakResolverConfig.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakWebSecurityConfig.java

https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1939
* https://github.com/kiegroup/optaplanner/pull/1920
* https://github.com/kiegroup/droolsjbpm-integration/pull/2764
* https://github.com/kiegroup/openshift-drools-hacep/pull/128
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle …

[7.59.x] BXMSPROD-1673 jakarta.el:jakarta.el-api excluded due to spring 5.3.18

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationManager.java

**JIRA**: [JBPM-10044](https://issues.redhat.com/browse/JBPM-10044)
<details>
<summary>
</summary> …

[JBPM-10044] pingFailedHost should distinguish scheduled task to cancel

---

kie-server-parent/kie-server-wars/kie-server/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-drools/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-jbpm/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-optaplanner/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-task-assigning-planning/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-task-assigning-runtime/pom.xml
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/pom.xml
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakResolverConfig.java
kie-spring-boot/kie-spring-boot-samples/keycloak-kie-server-spring-boot-sample/src/main/java/org/kie/server/springboot/samples/KeycloakWebSecurityConfig.java

https://issues.redhat.com/browse/BXMSPROD-1673
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1938
* https://github.com/kiegroup/optaplanner/pull/1916
* https://github.com/kiegroup/droolsjbpm-integration/pull/2760
* https://github.com/kiegroup/openshift-drools-hacep/pull/131
* https://github.com/kiegroup/optaweb-employee-rostering/pull/787
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/677
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …

[7.67.x] [BXMSPROD-1673] jakarta.el:jakarta.el-api excluded from org.kie.server:kie-server-services-common

---

kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/main/java/org/kie/server/controller/websocket/WebSocketKieServerControllerImpl.java
kie-server-parent/kie-server-controller/kie-server-controller-websocket/src/main/java/org/kie/server/controller/websocket/management/WebSocketKieServerMgmtControllerImpl.java

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-6898
Backport to 7.67.x -> https://github.com/kiegroup/droolsjbpm-integration/pull/2773
<details>
<summary>
</summary> …

[DROOLS-6898] WebSockets for Kie server controller broken for JWS 5.6.1

---

kie-camel/pom.xml

**JIRA**:  https://issues.redhat.com/browse/BXMSPROD-1694
* https://github.com/kiegroup/droolsjbpm-integration/pull/2736
<details>
<summary>
</summary>
[build-chain …

BXMSPROD-1694 com.sun.xml.bind:jaxb duplicated classes removal from kie-camel

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/LoadBalancer.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/LoadBalancerClientTest.java

Jira: https://issues.redhat.com/browse/JBPM-9933

[JBPM-9933] Queries getting appended if org.kie.controller.ping.alive disable is set true.

---

kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/executor/KieExecutorMDB.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/prometheus/PrometheusIntegrationTest.java

Jira: https://issues.redhat.com/browse/JBPM-10060

[JBPM-10060] ClusteredJobFailOverListener fails to remove data from cache

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java

**JIRA**: [JBPM-10043](https://issues.redhat.com/browse/JBPM-10043)

[JBPM-10043] Test for EventEmitter status after delegate

---

kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/KieServerHttpRequest.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2787/commits/7ba06e0fd8b4669b0e0cf6706164331c25ab9dc8

[7.67.x][RHPAM-4389] Add client certificate regardless of the hostname

---

kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/KieServerHttpRequest.java
kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring/.gitignore
kie-spring/src/main/java/org/kie/spring/manager/SpringRuntimeManagerFactoryImpl.java

Cherry-pick of https://github.com/kiegroup/droolsjbpm-integration/pull/2798/commits/6eb67daa813ee801330dcbc87ad7889acceb7b95

[7.67.x][JBPM-10089] - Fix some issues when using plain Spring framework to resolve the Transaction Manager 

---

kie-spring-boot/pom.xml

**JIRA**: https://issues.redhat.com/browse/RHPAM-4413
* https://github.com/kiegroup/droolsjbpm-integration/pull/2794
* https://github.com/kiegroup/droolsjbpm-integration/pull/2795
* https://github.com/kiegroup/droolsjbpm-integration/pull/2796 
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure …

[7.67.x-blue] RHPAM-4413 narayana-spring-boot-starter to 2.6.3

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring/.gitignore
kie-spring/src/main/java/org/kie/spring/manager/SpringRuntimeManagerFactoryImpl.java

**[JBPM-10089](https://issues.redhat.com/browse/JBPM-10089)**: Fix some issues when using plain Spring framework to resolve the correct Transaction Manager
Related to:
* https://github.com/kiegroup/jbpm/pull/2155
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) …

[JBPM-10089] - Fix some issues when using plain Spring framework to resolve the Transaction Manager

---

kie-osgi/kie-karaf-features/pom.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features-fuse.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7071
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …

[DROOLS-7071] Fix kie-karaf-itests failures because of poi version

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/marshalling/json/JSONMarshaller.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/marshalling/JSONMarshallerTest.java
kie-server-parent/kie-server-api/src/test/resources/supportedDateType.json
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/AbstractFormRenderer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/model/FormField.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/java/org/kie/server/services/jbpm/ui/form/render/model/LayoutItem.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/bootstrap/input-form-group-template.html
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/js/kieserver-ui.js
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/main/resources/form-templates-providers/patternfly/input-form-group-template.html
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/BootstrapFormRendererTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/java/org/kie/server/services/jbpm/ui/form/render/FormRendererTest.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/date-form.json
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/date-type-check-form.json
kie-server-parent/kie-server-services/kie-server-services-jbpm-ui/src/test/resources/dateTime-local-form.json

[https://issues.redhat.com/browse/JBPM-10058](https://issues.redhat.com/browse/JBPM-10058)
[https://issues.redhat.com/browse/JBPM-10077](https://issues.redhat.com/browse/JBPM-10077)
[https://issues.redhat.com/browse/JBPM-10079](https://issues.redhat.com/browse/JBPM-10079)
[https://issues.redhat.com/browse/JBPM-9942](https://issues.redhat.com/browse/JBPM-9942)
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the …

[7.67.x-blue] Backport PRs for form rendering issues

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java

Jira: https://issues.redhat.com/browse/JBPM-9747
depends on https://github.com/kiegroup/kie-soup/pull/224/files

[JBPM-9747] Support springboot buildpack immutable images

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/LoadBalancer.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/LoadBalancerClientTest.java

Jira: https://issues.redhat.com/browse/JBPM-9933

[7.67.x-blue] [JBPM-9933] Queries getting appended if org.kie.controller.ping.alive disable is set true.

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/KieServerConstants.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/balancer/LoadBalancer.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/test/java/org/kie/server/client/LoadBalancerClientTest.java

Jira: https://issues.redhat.com/browse/JBPM-9933

[7.67.x] [JBPM-9933] Queries getting appended if org.kie.controller.ping.alive disable is set true.

---

kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/executor/KieExecutorMDB.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/prometheus/PrometheusIntegrationTest.java

Jira: https://issues.redhat.com/browse/JBPM-10060

[7.67.x] [JBPM-10060] ClusteredJobFailOverListener fails to remove data from cache

---

kie-server-parent/kie-server-remote/kie-server-jms/src/main/java/org/kie/server/jms/executor/KieExecutorMDB.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/prometheus/PrometheusIntegrationTest.java

Jira: https://issues.redhat.com/browse/JBPM-10060

[7.67.x-blue] [JBPM-10060] ClusteredJobFailOverListener fails to remove data from cache

---

kie-spring-boot/kie-spring-boot-autoconfiguration/jbpm-spring-boot-autoconfiguration/src/main/java/org/jbpm/springboot/autoconfigure/JBPMAutoConfiguration.java
kie-spring/.gitignore
kie-spring/src/main/java/org/kie/spring/manager/SpringRuntimeManagerFactoryImpl.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2798/commits/6eb67daa813ee801330dcbc87ad7889acceb7b95

[7.67.x-blue][JBPM-10089] - Fix some issues when using plain Spring framework to resolve the Transaction Manager

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java

Jira: https://issues.redhat.com/browse/JBPM-9747
depends on https://github.com/kiegroup/kie-soup/pull/253

[7.67.x] [JBPM-9747] Support springboot buildpack immutable images

---

kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration/src/main/java/org/kie/server/springboot/autoconfiguration/KieServerAutoConfiguration.java

Jira: https://issues.redhat.com/browse/JBPM-9747
depends on https://github.com/kiegroup/kie-soup/pull/254

[7.67.x-blue] [JBPM-9747] Support springboot buildpack immutable images

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

**JIRA**: https://issues.redhat.com/browse/JBPM-10109

JBPM-10109: Add support for container alias in user task claim operation

---

kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/invoker.properties
kie-integration-test-coverage/kie-maven-plugin-no-execmodel-tests/kjar-with-instrumentation-no-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-no-execmodel/invoker.properties
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/kjar-with-separate-instrumentation-wrapper/src/test/resources/kjar-with-separate-instrumentation/invoker.properties
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/model-wrapper/src/test/resources/model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-13/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-2/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-3/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-4/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-5/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-6/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/kie-maven-plugin-test-kjar-common/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/kie-maven-plugin-test-kjar-parent/invoker.properties

Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2027
- https://github.com/kiegroup/droolsjbpm-integration/pull/2836
- https://github.com/kiegroup/kie-wb-common/pull/3760
- https://github.com/kiegroup/kie-wb-distributions/pull/1178
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023

[7.67.x] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

---

kie-integration-test-coverage/kie-maven-plugin-default-execmodel-tests/kjar-with-instrumentation-default-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-default-execmodel/invoker.properties
kie-integration-test-coverage/kie-maven-plugin-no-execmodel-tests/kjar-with-instrumentation-no-execmodel-wrapper/src/test/resources/kjar-with-instrumentation-no-execmodel/invoker.properties
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/kjar-with-separate-instrumentation-wrapper/src/test/resources/kjar-with-separate-instrumentation/invoker.properties
kie-integration-test-coverage/kie-maven-plugin-separate-model-tests/model-wrapper/src/test/resources/model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-13/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-2/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-3/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-4/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-5/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-6/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/kie-maven-plugin-test-kjar-common/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/kie-maven-plugin-test-kjar-parent/invoker.properties

Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2028
- https://github.com/kiegroup/droolsjbpm-integration/pull/2837
- https://github.com/kiegroup/kie-wb-common/pull/3761
- https://github.com/kiegroup/kie-wb-distributions/pull/1179
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023

[7.67.x-blue] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

**JIRA**: https://issues.redhat.com/browse/RHPAM-4453

[7.67.x][JBPM-10109] Add support for container alias in user task claim operation (#2818)

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/UserTaskServiceBase.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/UserTaskServiceIntegrationTest.java

**JIRA**: https://issues.redhat.com/browse/RHPAM-4453

[7.67.x-blue][JBPM-10109] Add support for container alias in user task claim operation (#2818)

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/UserTaskAdminServiceIntegrationTest.java

**[JBPM-10110](https://issues.redhat.com/browse/JBPM-10110)**
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send …

[JBPM-10110] - Need to exclude some bypass integration integration test for specific servers

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/UserTaskAdminServiceIntegrationTest.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2821/commits/865d0159701324349538c8866bb6168fdd87e019

[7.67.x][JBPM-10110] - Need to exclude some bypass integration integration test for specific servers

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-all/src/test/java/org/kie/server/integrationtests/jbpm/cases/CaseRuntimeDataServiceIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/TimerRollbackRegressionIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/admin/UserTaskAdminServiceIntegrationTest.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2821/commits/865d0159701324349538c8866bb6168fdd87e019

[7.67.x-blue][JBPM-10110] - Need to exclude some bypass integration integration test for specific servers

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/RuntimeDataServiceBaseTest.java

[RHPAM-3893](https://issues.redhat.com/browse/RHPAM-3893)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2846
* https://github.com/kiegroup/droolsjbpm-integration/pull/2826

[7.67.x-blue][RHPAM-3893] Return empty collection of processDefinitions

---

kie-server-parent/kie-server-services/kie-server-services-jbpm/src/main/java/org/kie/server/services/jbpm/RuntimeDataServiceBase.java
kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/RuntimeDataServiceBaseTest.java

[RHPAM-3893](https://issues.redhat.com/browse/RHPAM-3893)
* https://github.com/kiegroup/droolsjbpm-integration/pull/2826

[7.67.x][RHPAM-3893] Return empty collection of processDefinitions

---

drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtilTest.java
drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtils.java

Jira: https://issues.redhat.com/browse/JBPM-10101
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2038

[JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version

---

kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/KieServerHttpRequest.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/pull/2787/commits/7ba06e0fd8b4669b0e0cf6706164331c25ab9dc8

[7.67.x-blue][RHPAM-4389] Add client certificate regardless of the hostname

---

drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtilTest.java
drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtils.java

Jira: https://issues.redhat.com/browse/JBPM-10101
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2045

[7.67.x] [JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version (#2844)

---

drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtilTest.java
drools-ha/ha-core-infra/src/test/java/org/kie/hacep/KafkaUtils.java

Jira: https://issues.redhat.com/browse/JBPM-10101
depens on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2046

[7.67.x-blue] [JBPM-10101] kafka-clients misalignment with any supported AMQ Streams version (#2844)

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/java/org.jbpm.data/CustomAbortWorkItemHandler.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/customWIH.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java

**JIRA**:  [JBPM-10071](https://issues.redhat.com/browse/JBPM-10071)
cherry-picked from f4b51ec263781a1211ddf1bcf3b43cdc14118c0b
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …

[7.67.x][JBPM-10071] test for WIH's abortWorkItem method should be called

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/java/org.jbpm.data/CustomAbortWorkItemHandler.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/META-INF/kie-deployment-descriptor.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/definition-project/src/main/resources/customWIH.bpmn
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/rest/ProcessServiceRestOnlyIntegrationTest.java

**JIRA**: [JBPM-10071](https://issues.redhat.com/browse/JBPM-10071)
cherry-picked from https://github.com/kiegroup/droolsjbpm-integration/commit/f4b51ec263781a1211ddf1bcf3b43cdc14118c0b
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …

[7.67.x-blue][JBPM-10071] test for WIH's abortWorkItem method should be called

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/IntegrationTestsWebSecurityConfig.java

* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …

Fix typo in Spring boot integration test sample

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/IntegrationTestsWebSecurityConfig.java

* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …

[7.67.x] Fix typo in Spring boot integration test sample

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-integ-tests-sample/src/main/java/org/kie/server/springboot/samples/IntegrationTestsWebSecurityConfig.java

* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use …

[7.67.x-blue] Fix typo in Spring boot integration test sample

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/travelAgencyProcessWithHeaders.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersNoEscapeIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/AcmeDemoInterfaceImpl.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/HeaderInInterceptor.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/ReceiveInInterceptor.java

**JIRA**: [JBPM-10118](https://issues.redhat.com/browse/JBPM-10118)
* https://github.com/kiegroup/jbpm/pull/2212
<details>
<summary>
</summary> …

[JBPM-10118] Test Wrap into CDATA to avoid escape chars in SOAP headers

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/travelAgencyProcessWithHeaders.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersNoEscapeIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/HeaderInInterceptor.java

**JIRA**:  [JBPM-10125](https://issues.redhat.com/browse/JBPM-10125)
* [jbpm#2219](https://github.com/kiegroup/jbpm/pull/2219)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …

[JBPM-10125] Test for write raw to avoid escape chars in SOAP headers

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java

Jira: https://issues.redhat.com/browse/JBPM-10114

[JBPM-10114] ISPN000474 error thrown with java.lang.ClassNotFoundException when container is created

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java

Backport of https://github.com/kiegroup/droolsjbpm-integration/commit/0ce396f7d7a31fd5d44b5ed3b9c9b0a1807687f1

[7.67.x][JBPM-10114] ISPN000474 error thrown with java.lang.ClassNotFoundException when container is created

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/EJBCacheInitializer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java

Jira: https://issues.redhat.com/browse/JBPM-10127
https://github.com/kiegroup/droolsjbpm-integration/pull/2868

[7.,67.x] [JBPM-10127] Performance downgrade in cluster extension

---

kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/EJBCacheInitializer.java
kie-server-parent/kie-server-services/kie-server-services-jbpm-cluster/src/main/java/org/kie/server/services/jbpm/cluster/InfinispanClusterAwareService.java

Jira: https://issues.redhat.com/browse/JBPM-10127
https://github.com/kiegroup/droolsjbpm-integration/pull/2868

[7.67.x-blue] [JBPM-10127] Performance downgrade in cluster extension

---

kie-server-parent/kie-server-services/kie-server-services-openshift/src/main/java/org/kie/server/services/openshift/impl/OpenShiftStartupStrategy.java

…OpenShift Startup Strategy to warning]
- this message does not need to be a warning, in fact it could be
ignored, but, it is better to keep it ias debug in case it became
needed to debug any issue that could appear.
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …

[7.67.x][RHPAM-4519] - Set KubernetesClientException in Kie Server's

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/travelAgencyProcessWithHeaders.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersNoEscapeIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/AcmeDemoInterfaceImpl.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/HeaderInInterceptor.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/ReceiveInInterceptor.java

Backported from bc2298b236027bc88daf5caa8a0e99d49a1163b0 and 8f2609d04c43877b8123c6f0fd86d9405c5ac652
**JIRA**: [JBPM-10125](https://issues.redhat.com/browse/JBPM-10125)
referenced Pull Requests:
- jbpm#2226(https://github.com/kiegroup/jbpm/pull/2226)
<details>
<summary>
</summary>
[build-chain …

[7.67.x][JBPM-10125] Test for write raw to avoid escape chars in SOAP headers

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/travelAgencyProcessWithHeaders.bpmn2
kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/WebServiceHeadersNoEscapeIntegrationTest.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/AcmeDemoInterfaceImpl.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/HeaderInInterceptor.java
kie-server-parent/kie-server-tests/kie-server-test-web-service/src/main/java/com/jboss/soap/service/acmedemo/impl/ReceiveInInterceptor.java

Backported from bc2298b236027bc88daf5caa8a0e99d49a1163b0 and 8f2609d04c43877b8123c6f0fd86d9405c5ac652
**JIRA**: [JBPM-10125](https://issues.redhat.com/browse/JBPM-10125)
- [jbpm#2227](https://github.com/kiegroup/jbpm/pull/2227)
<details>
<summary>
</summary>
[build-chain …

[7.67.x-blue][JBPM-10125] Test for write raw to avoid escape chars in SOAP headers

---

kie-spring/src/main/java/org/kie/spring/persistence/KieSpringTransactionManager.java

Jira: https://issues.redhat.com/projects/JBPM/issues/JBPM-9450

[JBPM-9450] Jbpm7 spring boot business application: No active transaction after arjuna transaction timeout

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java

**JIRA**: [JBPM-10043](https://issues.redhat.com/browse/JBPM-10043)
backported from https://github.com/kiegroup/droolsjbpm-integration/commit/7030fe692118ed836a19b1cd0dabebadaafbc53a
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be …

[7.67.x-blue][JBPM-10043] Test for EventEmitter status after delegate

---

kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaEmitterHappyPathTest.java
kie-spring-boot/kie-spring-boot-samples/kie-server-spring-boot-kafka-sample/src/test/java/org/kie/server/springboot/samples/KafkaFixture.java

**JIRA**: [JBPM-10043](https://issues.redhat.com/browse/JBPM-10043)
backported from 7030fe692118ed836a19b1cd0dabebadaafbc53a
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …

[7.67.x][JBPM-10043] Test for EventEmitter status after delegate

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java

**JIRA**: [JBPM-10064](https://issues.redhat.com/browse/JBPM-10064)
<details>
<summary>
</summary> …

[JBPM-10064] Flaky test at FileRepositoryTest

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java

**JIRA**: [JBPM-10064](https://issues.redhat.com/browse/JBPM-10064)
backported from https://github.com/kiegroup/droolsjbpm-integration/commit/c23f3f7ccce6ae559f1cfd37bd21ce5d745c6303
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always …

[7.67.x-blue][JBPM-10064] Flaky test at FileRepositoryTest

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/test/java/org/kie/server/router/repository/FileRepositoryTest.java

**JIRA**:  [JBPM-10064](https://issues.redhat.com/browse/JBPM-10064)
backported from c23f3f7ccce6ae559f1cfd37bd21ce5d745c6303
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions …

[7.67.x][JBPM-10064] Flaky test at FileRepositoryTest

---

kie-server-parent/kie-server-router/kie-server-router-proxy/src/main/java/org/kie/server/router/ConfigurationManager.java

**JIRA**: [JBPM-10044](https://issues.redhat.com/browse/JBPM-10044)
back-ported from c28804898fa5361f6c1be1a3afd50215f70ee35c
* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x][JBPM-10044] pingFailedHost should distinguish scheduled task to cancel

---

kie-server-parent/kie-server-api/src/main/java/org/kie/server/api/rest/RestURI.java
kie-server-parent/kie-server-api/src/test/java/org/kie/server/api/rest/RestURITest.java
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/KieServerHttpRequest.java
kie-server-parent/kie-server-common/src/main/java/org/kie/server/common/rest/KieServerHttpRequestException.java
kie-server-parent/kie-server-common/src/test/java/org/kie/server/common/rest/KieServerHttpRequestTest.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/admin/impl/ProcessAdminServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/AbstractKieServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/QueryServicesClientImpl.java
kie-server-parent/kie-server-remote/kie-server-client/src/main/java/org/kie/server/client/impl/UserTaskServicesClientImpl.java

**JIRA**: 
https://issues.redhat.com/browse/JBPM-10159

[JBPM-10159] Escaping variable name in path

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/ProcessServiceIntegrationTest.java

correlationKey
**JIRA**: [JBPM-9508](https://issues.redhat.com/browse/JBPM-9508)

[JBPM-9508] Test creation for duplicated processes with same

---

jbpm-process-svg/pom.xml

https://issues.redhat.com/browse/RHPAM-4593
The idea is about excluding `org.apache.xmlgraphics:batik-anim` and be able to execute PME `dependencyRelocations.xalan:xalan@xalan:xalan-bcel-6.6.1={{xalanBcelVersion}}`
<details>
<summary>
</summary>
[build-chain …

RHPAM-4593 xalan dependency excluded from batik-anim

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/QueryDataServiceIntegrationTest.java

<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …

kie-server-tests: list ExecutionErrorInstance returned in unstable test

---

jbpm-process-svg/pom.xml

After productized relocation, `xalan:serializer` is no more brought as transitive dependecy (as it is using upstream version) therefore I think the best solution is to explicitly include `xalan:serializer` dependency.
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4702
* https://github.com/kiegroup/droolsjbpm-integration/pull/2947
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …

[RHPAM-4702] Added explicit xalan:serializer

---

kie-server-parent/kie-server-wars/kie-server/src/main/ee-resources/WEB-INF/jboss-deployment-structure.xml

- force jackson version in kie-server war rather than wildfly
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2296
* https://github.com/kiegroup/optaplanner/pull/2838
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is …

[RHPAM-4700] upgrade snakeyaml

---

camel-container-tests/camel-container-integration-tests/src/test/filtered-resources/org/kie/camel/container/integration/tests/kjar/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
kie-server-parent/kie-server-tests/kie-server-integ-tests-optaplanner/src/test/filtered-resources/kjars-sources/cloudbalance/pom.xml
pom.xml

[BXMSPROD-2083](https://issues.redhat.com/browse/BXMSPROD-2083)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2347
* https://github.com/kiegroup/droolsjbpm-integration/pull/2979
* https://github.com/kiegroup/kie-wb-common/pull/3816
* https://github.com/kiegroup/kie-wb-distributions/pull/1231
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …

BXMSPROD-2083: use of OptaPlanner final version

---

kie-osgi/kie-karaf-features/pom.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4781
This is a backport PR of https://github.com/kiegroup/droolsjbpm-integration/pull/2993 for 7.67.x
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be …

[7.67.x] [RHPAM-4781] KIE-OSGI: Inconsistent h2 version upgrade (#2993)

---

kie-osgi/kie-karaf-features/pom.xml
kie-osgi/kie-karaf-features/src/main/filtered-resources/repository/features.xml

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4781
This is a backport PR of https://github.com/kiegroup/droolsjbpm-integration/pull/2993 for 7.67.x-blue
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …

[7.67.x-blue] [RHPAM-4781] KIE-OSGI: Inconsistent h2 version upgrade (#2993)

---

kie-osgi/kie-karaf-features/pom.xml

Replaces https://github.com/kiegroup/droolsjbpm-integration/pull/2992
<details>
<summary>
</summary> …

Bump org.apache.santuario:xmlsec from 2.1.7 to 2.2.6 in /kie-osgi/kie-karaf-features

---

kie-tomcat-integration/pom.xml

**JIRA**: 
https://issues.redhat.com/browse/DROOLS-7598
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2413
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or …

[DROOLS-7598] Upgrade tomcat version

---

kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolverHandler.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolverHandlerConfig.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningConstants.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionHelper.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionMessages.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningServiceConfig.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/SolverHandlerConfigTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/SolverHandlerTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionHelperTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/TaskAssigningServiceConfigTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/pom.xml

**JIRA**: [JBPM-10217](https://issues.redhat.com/browse/JBPM-10217)
<details>
<summary>
</summary> …

[JBPM-10217] Authentication fails on Oracle WLS in TaskAssigningIntegrationTest

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-rest/src/main/java/org/kie/server/extension/custom/CustomDroolsKieServerApplicationComponentsService.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-rest/src/main/java/org/kie/server/extension/custom/CustomJsonResource.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/java/org/kie/server/integrationtests/extension/custom/CustomExtensionIntegrationTest.java
kie-server-parent/kie-server-wars/kie-server/pom.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee8-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/ee-resources/WEB-INF/jboss-deployment-structure.xml

- Add resteasy-jackson2-provider in kie-server.war
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4876
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …

[RHPAM-4876] exclusion on kie server affect custom endpoints

---

kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolverHandler.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/SolverHandlerConfig.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningConstants.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionHelper.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionMessages.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/main/java/org/kie/server/services/taskassigning/planning/TaskAssigningServiceConfig.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/SolverHandlerConfigTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/SolverHandlerTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/TaskAssigningPlanningKieServerExtensionHelperTest.java
kie-server-parent/kie-server-services/kie-server-services-task-assigning/kie-server-services-task-assigning-planning/src/test/java/org/kie/server/services/taskassigning/planning/TaskAssigningServiceConfigTest.java
kie-server-parent/kie-server-tests/kie-server-integ-tests-task-assigning/pom.xml

IntegrationTest
**JIRA**: [JBPM-10217](https://issues.redhat.com/browse/JBPM-10217)
cherry_picked from f446eb302847bdf8a89536aa0b09a7e3656535e6
<details>
<summary>
</summary> …

[7.67.x][JBPM-10217] Authentication fails on Oracle WLS in TaskAssigning

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-custom-extension/kie-server-integ-tests-custom-extension-test/src/test/java/org/kie/server/integrationtests/extension/custom/CustomExtensionIntegrationTest.java
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-ee7-container.xml
kie-server-parent/kie-server-wars/kie-server/src/main/assembly/assembly-servlet-container.xml

**JIRA**: [JBPM-10221](https://issues.redhat.com/browse/JBPM-10221)
<details>
<summary>
</summary> …

[JBPM-10221] Fix assembly for webc,ee7 after RHPAM-4876

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/filtered-resources/kjars-sources/webservice-project/src/main/resources/com/jboss/soap/service/acmedemo/jaxb.index

**JIRA**: [JBPM-10222](https://issues.redhat.com/browse/JBPM-10222)
<details>
<summary>
</summary> …

[JBPM-10222] Fix WebService integration tests by adding jaxb.index

---

kie-maven-plugin/pom.xml
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-13/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-2/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-3/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-4/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-5/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-6/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/invoker.properties

Fix broken build of kie-maven-plugin integration tests projects.

[7.67.x-blue] Fix maven plugin tests

---

kie-maven-plugin/pom.xml
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-10-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-default/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-11-yes-generate/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-12/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-13/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-2/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-3/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-4/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-5/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-6/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-7-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-8-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-9-no-exec-model/invoker.properties
kie-maven-plugin/src/it/kie-maven-plugin-test-kjar-setup/invoker.properties

Fix failing integration tests build of kie-maven-plugin.

[7.67.x] - fix maven tests

---

kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerConsumer.java
kie-server-parent/kie-server-services/kie-server-services-kafka/src/main/java/org/kie/server/services/jbpm/kafka/KafkaServerRegistration.java

Copy of https://github.com/kiegroup/droolsjbpm-integration/pull/3034 (main) against the 7.67.x-blue branch.
Related JIRA: https://issues.redhat.com/browse/RHPAM-4898

[7.67.x-blue][RHPAM-4898] Fix concurrency issue in KafkaServerRegistration

---

kie-server-parent/kie-server-tests/kie-server-integ-tests-jbpm/src/test/java/org/kie/server/integrationtests/jbpm/SLAComplianceIntegrationTest.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/src/main/java/org/kie/server/spring/boot/autoconfiguration/audit/replication/AuditDataReplicationProcessEventProducer.java
kie-spring-boot/kie-spring-boot-autoconfiguration/kie-server-spring-boot-autoconfiguration-audit-replication/src/main/java/org/kie/server/spring/boot/autoconfiguration/audit/replication/MessageType.java

(cherry picked from commit b19df698554ce45b07c6a0ba5a5322b687b7fe93 4279f84ce27c1c345a050c3e29f3a04da69fb30c)
**JIRA**:  [RHPAM-4779](https://issues.redhat.com/browse/RHPAM-4779)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/648
* https://github.com/kiegroup/drools/pull/63
* https://github.com/kiegroup/jbpm/pull/2431
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …

[7.67.x-blue] RHPAM-4779: SLA due date value in ProcessInstanceLog table is not updated after updating process SLA

---

kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/src/test/resources/application-quartz.properties

**referenced Pull Requests**: _https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2468_
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …

[7.67.x blue] Fixing deprecated properties for Spring boot 2.7.18

---

kie-server-parent/kie-server-tests/pom.xml
kie-spring-boot/kie-spring-boot-samples/jbpm-spring-boot-sample-basic/pom.xml

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2488
* https://github.com/kiegroup/droolsjbpm-integration/pull/3063
* https://github.com/kiegroup/appformer/pull/1422
* https://github.com/kiegroup/jbpm/pull/2438
* https://github.com/kiegroup/kie-wb-distributions/pull/1245
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/649
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …

[7.67.x-blue] Updating mysql connector gav

---

kie-server-parent/kie-server-api/src/build/revapi-config.json

* link 2
* link 3 etc.
<details>
<summary>
</summary> …

[7.67.x-blue] NO-ISSUE: Bump `xstream` to version `1.4.21`

---

kie-spring-boot/pom.xml

Exclude tomcat-embed version inherited from springboot, and explicitly add required ones.
Needs https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2558
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …

[NO_ISSUE] Embed-tomcat related multiple CVES
